### ISSUE TITLE
Unable to make remote connection on windows

### ISSUE THREAD

**Issue by Dm94st** [sassoftware/saspy#105]
I'm follow this instruction [Installation and configuration](https://sassoftware.github.io/saspy/install.html ) and try to make Remote connection. 
My configuration:
Client: Windows server 2008r2;
Server: Windows server 2012r2 and SAS 9.4;

![Error](https://user-images.githubusercontent.com/15802388/36776261-3b351bb6-1c76-11e8-9ea1-00db68e248f5.jpg)

Here is the error code returned when I try to run a SAS session with "winiomwin". So, I can tell that the connection is established("The client has connected to a SAS Metadata Server (v1.0) when it intended to connect to a SAS Workspace Server."), however further I get an error: 
SAS process has terminated unexpectedly. RC from wait was: 4294967290 
SAS Connection failed. No connection established. Double check you settings in sascfg.py file. 
Please tell me what I'm doing wrong or what could be a mistake.

**Comment by FriedEgg** [comment]
This error message typically means you have defined the incorrect port and possibly the incorrect host as well.  As the error message says, you have defined a host and port that is for the SAS Metadata Server.  SASPy is looking for a connection to your SAS Workspace Server.  The default port for this is 8591.  Your winiomwion configuration has 8561, which is the default for Metadata, so the simplest thing to do would be to try 8591 instead.  If your Workspace server is not on the same host as your Metadata server, the host would also require an update.

**Comment by tomweber-sas** [comment]
@Dm94st , the problem here is that you are connecting to your metadata server instead of the object spawner (requesting a workspace server). In your configuration definition (winiomwin, in this case), you need  iomhost= to point to a host where the object spawner is running (this may be correct already is it's running the same host as metadata server), and your iomport has to be that of the workspace server, not the metadata server; this is wrong for sure, I expect. 
If you have a simple setup, that's all you will need. If you have multiple App Servers (different sets of workspace servers configured, and maybe multiple object spawners), you can use the following info from the doc to see what the hosts and ports are: 
https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports

If you have multiple sets of servers defined, then you'll also need to specify the one you're trying to connect to with the appserver= option (https://sassoftware.github.io/saspy/install.html#remote)

Just using the right port will probably get you running.
Thanks,
Tom

**Comment by Dm94st** [comment]
@FriedEgg, @tomweber-sas, thanks guys! It helps me! I just changed port and it works now!

**Comment by tomweber-sas** [comment]
Good deal! Let me know if you have any other questions or issues!
Tom

**Comment by Dm94st** [comment]
@tomweber-sas, ok!) thank you again!)
