### ISSUE TITLE
Containerized SAS + SASpy with IOM

### ISSUE THREAD

**Issue by sylus** [sassoftware/saspy#113]
Hi there,

I was curious if I am doing something wrong related to IOM or if it only works via SAS grid.

https://github.com/govcloud/docker-sas4c/blob/master/studio/Dockerfile

I have the following containerized SAS which is setup to run SAS studio and can be accessed without issue at http://localhost:38080/SASStudio/. I then wanted to try connecting a local remote jupyter notebook to my container through a IOM port. I opted to quickly test with python and calling saspy.SASsession() which does work and I can see is trying to set up a node via object spawner logs. I was hoping it would just connect to existing sas kinda of like a local connection? Am i misunderstanding how IOM can be leveraged? I really don't want to add ssh to my container to facilitate that method.

## Object Spawner Logs

```sh
2018-03-16T04:00:22,198 INFO  [00000032] :sas - New client connection (5) accepted from server port 38591 for user sas. Encryption level is Credentials using encryption algorithm SASPROPRIETARY. Peer IP address and port are [::ffff:172.17.0.1]:44552 for APPNAME=SASPy.
2018-03-16T04:00:22,210 INFO  [00000032] :sas - Created process 270 using credentials sas (child id 1).
2018-03-16T04:00:22,374 INFO  [00000033] :root - New out call client connection (6) for launched server (child 1).  Peer IP address and port are [::ffff:172.17.0.2]:60914.
2018-03-16T04:00:22,384 INFO  [00000033] :root - Client connection 5 for user sas closed.
2018-03-16T04:00:22,903 INFO  [00000049] :root - Client connection 6 for user sas closed.
2018-03-16T04:00:23,034 INFO  [00000031] :root - Process 270 owned by user sas (child id 1) has ended.
sh-4.2# 
```

## saspy.cfg

```sh
# build out a local classpath variable to use below for Linux clients
cpL  =  "/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.svc.connection.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/log4j.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.security.sspi.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.core.jar"
cpL += ":/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/saspyiom.jar"

iomlinux = {'java'      : '/usr/bin/java',
            'iomhost'   : 'localhost',
            'iomport'   : 8591,
            'encoding'  : 'utf8',
            'classpath' : cpL,
            "javaparms": ["--add-modules=java.corba"]
            }  
```

## SASPY execution

```sh
>>> saspy.SASsession(iomport=38591)
Using SAS Config named: iomlinux
Please enter the IOM user id: sas
Please enter the password for IOM user : 

SAS process has terminated unexpectedly. Pid State= (17540, 256)
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '--add-modules=java.corba', '-classpath', '/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.svc.connection.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/log4j.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.security.sspi.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.core.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '52720', '-stdoutport', '52721', '-stderrport', '52722', '-iomhost', 'localhost', '-iomport', '38591', '-user', 'sas', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
Access Method         = IOM
SAS Config name       = iomlinux
WORK Path             = /
SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
SASPy Version         = 2.2.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = No
Python Encoding value = utf8
```

**Comment by tomweber-sas** [comment]
Ok, let me see if I understand. I probably don't. Home sick today and my brain isn't all the way up to speed today,

You're running python in the container and there's a local SAS install in the container also? I'm not sure where the ObjSpawner/OMR and that is running. 
Or you're outside the container with python, and OMR, ObjSpawner and all of that is in the container, but you're looking for the saspy session to just use the local SAS deployment in the container instead of connecting to the ObjSpawner and getting a workspace server?

One thing I can tell you, till I get this picture straight in my head, is the 2 ways IOM can connect, LOCAL or REMOTE. Local only works on Windows and it doesn't use OMR or Object spawers or any of that, just a regular SAS deployment like you would run sas.exe from.
The remote, which is what you're running, is the other and does need OMR/ Objspawn Workspace...
It looks like it's trying to all run remotely, but failing somehow that I don't see. This appears to be the failure point?
```
2018-03-16T04:00:22,374 INFO  [00000033] :root - New out call client connection (6) for launched server (child 1).  Peer IP address and port are [::ffff:172.17.0.2]:60914.
```

I need the picture of where each of these parts live and what the path you're thinking should happen is.
Now I'm thinking python is outside the container, a local SAS deployment is in the container, OMR... is remote on a third system. And you're trying to have saspy connect to SAS in the container (remotely) and it's getting to the container, but from there trying a remote connection to a workspace server elsewhere?

Sorry, I'm confused. But we'll figure it out. Tell me what's where and how you're thinking it should flow again.
Tom

**Comment by sylus** [comment]
Hi there!

Appreciate the response and absolutely no worries!

Essentially I have python on my mac with saspy connecting to the complete SAS install which is all inside of a container running locally for the moment. 

# docker run

```sh
docker run --name sas -d -p 8561:8561 -p 8591:8591 -p 38080:38080 -p 38591:38591 -p 52861:52861 sas4c:9.4-studio    
```

So for example say we are talking about my studio container which has the complete SAS install along with SAS Studio and Deployment manager etc. This is all inside the container.

When the container is launched the the "/start.sh" script is executed. This script simply does the following:

```sh
/usr/local/SASHome/SASFoundation/9.4/utilities/bin/setuid.sh
/usr/local/SASHome/sas/studioconfig/sasstudio.sh start

tail -f /dev/null
```

So in the container it will execute SASS studio which in terms executes the obj spawner and all the other dependencies. I can then go to localhost:38080/SASSStudio and I am able to login and everything works as expected.

**Comment by tomweber-sas** [comment]
Ok, that helps. So is it just that it's failing to connect up the workspace server with the IOM client (java process of saspy)? Is that an issue with the port not being exposed back between the two?

I have to tell you I haven't played around with docker yet, so I'm sure I'm not aware of some of the interactions between the container and your mac, that are implied as part of docker.
But what it looks like is that the IOM client can connect in and successfully request a workspace server, but it's not connecting up with it, which smells like the socket connection isn't happening; like from inside the container it can't get back to the client side to connect up. 

I'm sorry I don't know docker yet, so maybe there wouldn't be an issue like this. Or, does this sound like a problem it could have.

Gotta go get kids from school, but I'll investigate more this afternoon.
Tom

**Comment by sylus** [comment]
Thanks again for your insight I really appreciate it. You are correct that I think it is just failing when being exposed back but I am not 100%.

I can say wrt to docker that it is entirely closed off except for the ports that I included in the docker run. So if the connect back was using a different port it would indeed be blocked. The only ports I have open and that can be seen from mac are:

```sh
8561:8561
8591:8591
38080:38080
38591:38591
52861:52861
```

The one thing I found out and could possible be the problem is if you look at this log:

```sh
2018-03-16T19:02:13,198 INFO  [00000004] :root - SAH021999I Server SAS Object Spawner Daemon III, State, running
2018-03-16T19:03:25,335 INFO  [00000012] :sas - New client connection (3) accepted from server port 38591 for user sas. Encryption level is Credentials using encryption algorithm SASPROPRIETARY. Peer IP address and port are [::ffff:172.17.0.1]:55308 for APPNAME=SASPy.
2018-03-16T19:03:25,359 INFO  [00000012] :sas - Created process 172 using credentials sas (child id 0).
2018-03-16T19:03:25,634 INFO  [00000013] :root - New out call client connection (4) for launched server (child 0).  Peer IP address and port are [::ffff:172.17.0.2]:57930.
2018-03-16T19:03:25,652 INFO  [00000013] :root - Client connection 3 for user sas closed.
2018-03-16T19:03:26,140 INFO  [00000009] :root - Client connection 4 for user sas closed.
2018-03-16T19:03:26,254 INFO  [00000031] :root - Process 172 owned by user sas (child id 0) has ended.
```

I was curious about [::ffff:172.17.0.1]:55308 and [::ffff:172.17.0.2]:57930 and exactly what it is trying to do at this point? I don't have those ports open in my container but they change every time so can't manually specify them in the docker run.

**Comment by tomweber-sas** [comment]
This does really look like it just can't connect up because of the port's not being exposed, to me. I'll have to look into the spawner log messages to be sure what they imply, but I think it's really just the following.

I think 172.17.0.1 is your mac (python client side) and it's using port 55308, which I think is the port the workspace server would be trying to connect back to. I think 172.17.0.2 is the container and it's side of the socket uses port 57930, which is inside the container and probably wouldn't need to be exposed.
And yes, these ports will change every time, on both sides. I think the failure is the workspace server trying to connect back to 172.17.0.1:55308. Or the reverse, If the client was told to connect to the workspace server at 172.17.0.2:57930. In that case 57930 would need to be exposed. I'm just not positive which way the IOM client/server connects up. But I think either way it's just a firewall issue with one of those ports not being exposed.

So, there is a simple way to make this work though. Don't know if it's what you want. If you had jupyter in the container (asd saspy), and ran the jupyter server in there, then you just expose the port it's listening on and open a notebook on you mac, which will all look the same. This is how Studio is working; it's inside and you just connect from outside over http on the exposed port. Then everything (SAS and IOM wise) are inside and there are no port issues with the connections between the saspy java iom client and the workspace server. No dynamic port not exposed issues.

I can definitely dig into this more next week and see if there's a means to have IOM work in this situation. Let me know if jupyter inside is ok or not too. I'm pretty sure that would run without problem in this case.

Tom

**Comment by sylus** [comment]
Yup that all makes sense to me, and agree this is likely just down to a port issue. I can specify a range of port via `docker run -p 49000-49500:49000-49500` but have to guess at what the range would be and hasn't worked out. You can also just do `--net=host` in docker which will forward all ports but doesn't work for docker for mac as expected due to xhyve virtualization layer.

Also agreed that Jupyter Notebook would 100% work in the container, and would work great for quick dev, but unfortunately doesn't suit the model we want to go with. Where jupyter notebook is connected to a variety of docker containers based on user selection. So far have containers for SAS, Pachyderm, Python and colocated Hadoop + Spark in the same cluster. If helps I tried to quickly summate below.

# Zero to JupyterHub K8s

https://github.com/jupyterhub/zero-to-jupyterhub-k8s

## Architecture

![architecture](https://user-images.githubusercontent.com/984304/37542817-dcdb663e-2935-11e8-828a-efad53703c3a.png)

Leveraging the LDAP Authenticator the moment the user logs and picks their profile it will launch the appropriate Notebook Server alongside with the specific docker container selected.

## Spawner

<img width="400" alt="3_spawner" src="https://user-images.githubusercontent.com/984304/37542842-e9233084-2935-11e8-9a11-61ff6a75c67b.png">

Where the spawner based on what is selected launches the appropriate container. Other options can be passed such as cpu / network and memory constraints. The values entered above are simply entered in Helm:

```sh
  extraConfig: |
    c.KubeSpawner.cmd = ['jupyter-labhub']
    c.KubeSpawner.single_user_profile_list = [
        {
            'display_name': 'Training Env - Python',
            'kubespawner_overrride': {
                'image_spec': 'jupyterhub/python:0.8',
                'cpu_limit': 10,
            }
        },
        {
            'display_name': 'Training Env - SAS',
            'kubespawner_overrride': {
                'image_spec': 'jupyterhub/sas:0.8',
                'cpu_limit': 10,
            }
        }, {
            'display_name': 'DataScience - Pachyderm',
            'kubespawner_overrride': {
                'image_spec': 'jupyterhub/pachyderm:0.8',
                'cpu_limit': 10,
            }
        }
    ]
```

Then finally you then land in your notebook.

<img width="400" alt="4_intro" src="https://user-images.githubusercontent.com/984304/37542920-338b44fe-2936-11e8-9e4f-db0e5769b6d2.png">

**Comment by sylus** [comment]
Hi there! @tomweber-sas let me know if wanted me to file an issue through official channels on my end, if that helps!

**Comment by tomweber-sas** [comment]
I've reached out to TS myself this morning. Trying to find the right contact, as I can't find documentation that helps with this at all. It wouldn't hurt for you to open a track. If you do, let me know the number so I can get on it too and make sure we get a quick resolution.
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Well, I've heard back from tech support, and it doesn't sound like I understand how IOM uses ports. I've seen some different behavior than what I've been told happens, but I think there's still something more going on here. Please do open a track with TS, because I'm no expert on IOM and I think we will need their expertise to be sure of what's happening for this case. 
Thanks,
Tom

**Comment by sylus** [comment]
Hmm interesting, yeah the ports definitely are dynamic so be interesting to see what they say, I have submitted an email and just waiting for one of my co-workers who has privileges to file it.

**Comment by tomweber-sas** [comment]
Roger that.

Actually, it seems the initial connection stays on the same port (8591, or rather 38591 in your case), so there isn't an ephemeral port in that mix. I don't know what the 'New outcall client connection' message means, but looking at this now, that appears to be a connections local to the container, in your case. I think it's connection between the spawner and workspace server. So that's not a problem, W.R.T. non-exported port. So, I don't think my guess about it being a non exported port is correct. I think there's something else.  

I had just been implementing #99 and after reconnecting, the port on the SAS side does change from 8591 to something else, each time I reconnected it changed; stayed in the 88xx range though. So, that would then be an issue, but I don't see that being the issue you're having now. But, that's what I was looking at on my side with the ports and didn't see it as 8591.

Trying it here now, I see the connection stay 8591 on the SAS side, and I see that ephemeral port from that other message be a local connection between the obj spawn and workspace server. I don't see any other connection back to the client side. 

Can you enable workspace server logging and maybe set both it and the object spawner logging to debug so we can see is that shows us what error is actually happening? TS suggested that and also to try the following.

run ./WorkspaceServer.sh –nodms using the sas account from command line (in the container) and see if it shows anything. 

Again, Let me know what track you get so I can get on it from here,
Tom

**Comment by tomweber-sas** [comment]
@sylus Just got pinged from TS, so they have your track, and I'm hooked up there. Seeing as this is not a dynamic port issue; I have played with it to see that as well as have TS educate me too :)
Have you gotten the logging set up for the workspace server/ object spawner? That is the next step so we can see what the failure actually is. I don't know exactly what to do to get that set up. TS will, so I will ask them to provide those instructions in case you aren't already doing that.

BTW, with the reconnect case I was mentioning, it does appear to just reuse 8801, 8811, 8821 so even that situation (which you aren't hitting), should easilly be addresed by just adding those few ports to the export list. Again, that's not the problem currently, but that's why I thought ther ewere ephemeral ports between the workspace sevrver and the client (cuz for reconnect those are), but you'r connect should use the 38591 you configured.

Let's get the logging set up so we see what's happening, and if we need to jump on a web-X I totally good with that.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Actually, I was wrong, that wasn't a tech support person. That was sales??? I don't know if you have a tech support track or not yet. 
Tom

**Comment by sylus** [comment]
Hi there thanks again for all your help. I have added the remaining ports but maybe if you have a chance today can pop on web-ex as not sure where to proceed next.

Just wanted to say again, truly appreciate all of your help! :)

**Comment by tomweber-sas** [comment]
Great, I see the track now. I'll send you a webex link in a few minutes if that works.
Tom

**Comment by tomweber-sas** [comment]
Oh, I thought I had an email from you, but I don't seem to. Here's the link
https://sas.webex.com/join/Tom.Webersas.com

**Comment by sylus** [comment]
So me and @tomweber-sas took a look at this and noticed even though SAS Studio does start up we aren't able to execute code. We enabled tracing for both objectspawner + workspacerserver and notice an interesting entry in the workspace server logs when executing saspy.SASsession().

```sh
2018-03-21T13:09:09,058 DEBUG [00000004] 1:sas - IOM CALL {compRef:7f2f801717a0}->Workspace::LanguageServiceGet()
2018-03-21T13:09:09,058 TRACE [00000004] 1:sas - puddleEnqueue(0x7f2f976a35a0, 0x7f2f71573ac0, 0x0, 0x0, 0x0)
2018-03-21T13:09:09,058 TRACE [00000004] 1:sas - puddleEnqueue(0x7f2f976a35a0) gave request to worker 0x7f2f900aac80
2018-03-21T13:09:09,058 TRACE [00000004] 1:sas - 0x0=threadPoolEnqueue(0x7f2f976a35a0)
2018-03-21T13:09:09,058 DEBUG [00000004] 1:sas - IOM LOGIC VOIMapWrcodeToWoiStatus() Mapping error severity wrcode: 0x8003c822
2018-03-21T13:09:09,058 DEBUG [00000004] 1:sas - IOM LOGIC VOIMapWrcodeToWoiStatus() No wrcode mapping - using generic error (WOIRAISE): wrcode=0x8003c822
2018-03-21T13:09:09,058 TRACE [00000004] 1:sas - puddleEnqueue(0x7f2f976a35a0, 0x7f2f71573a40, 0x0, 0x0, 0x0)
2018-03-21T13:09:09,058 TRACE [00000004] 1:sas - puddleEnqueue(0x7f2f976a35a0) gave request to worker 0x7f2f900aac80
2018-03-21T13:09:09,059 TRACE [00000004] 1:sas - 0x0=threadPoolEnqueue(0x7f2f976a35a0)
2018-03-21T13:09:09,059 DEBUG [00000004] 1:sas - IOM RETURN -1={compRef:7f2f801717a0}->Workspace::LanguageServiceGet(): text=<?xml version="1.0" ?><Exceptions><Exception><SASMessage severity="Error">The requested function was not performed due to an invalid or expired product license.</SASMessage></Exception></Exceptions>
2018-03-21T13:09:09,059 DEBUG [00000030] 1:sas - tcpSockWriteVector sent 342 bytes on socket 3.
2018-03-21T13:09:09,526 TRACE [00000009] :sas - Select wait on handle 2 found activity on 1 sockets
2018-03-21T13:09:09,526 TRACE [00000009] :sas - Select handle 2 no longer waiting on E0000000 for socket 3
2018-03-21T13:09:09,526 TRACE [00000009] :sas - puddleEnqueue(0x7f2f976a35a0, 0x7f2f90170960, 0x0, 0x80000000, 0x0)
2018-03-21T13:09:09,527 TRACE [00000009] :sas - puddleEnqueue(0x7f2f976a35a0) gave request to worker 0x7f2f900aab80
2018-03-21T13:09:09,527 TRACE [00000009] :sas - 0x0=threadPoolEnqueue(0x7f2f976a35a0)
2018-03-21T13:09:09,527 TRACE [00000009] :sas - Select handle 2 entering wait for -1 ms
2018-03-21T13:09:09,527 TRACE [00000009] :sas - About to wait on select list id=2 [s:4(28)r-x]
2018-03-21T13:09:09,527 TRACE [00000033] 1:sas - tcpSockRead returning 0 bytes as requested on socket 3
2018-03-21T13:09:09,527 DEBUG [00000033] 1:sas - Peer has disconnected.
2018-03-21T13:09:09,527 DEBUG [00000033] 1:sas - Bridge PE [7f2f900ab6c0] Unregistered
2018-03-21T13:09:09,527 TRACE [00000033] 1:sas - socket 3 being closed
2018-03-21T13:09:09,527 TRACE [00000033] 1:sas - socket 3 closed complete
2018-03-21T13:09:09,527 DEBUG [00000033] 1:sas - Bridge PE [7f2f900ab6c0] Connection destroyed
2018-03-21T13:09:09,527 TRACE [00000033] 1:sas - IOM CALL {compRef:7f2f80151340}->LaunchedIOMServer::ClientOut():
```

**Comment by tomweber-sas** [comment]
@sylus is going to redeploy SAS with the sas user id (instead of root). Knowing that his license is still valid, it is suspected that the workspace server, running as the sas id can't get at a file, as some of the deployment has permissions of root. So it looks like a mismatch of root/sas id permissions problems.
Other than that, it all is actually connecting and starting up and looks like this should just work once this issue is addressed. SAS Studio seems to have a similar problem.
Tom

**Comment by sylus** [comment]
Okay so documenting the full steps.

1) Install CentOS in Virtual machine
2) Copy SAS depot inside share folder
3) Create sas user + sasstaff group
4) Install SAS to /usr/local/SASHome as sas user via:

```sh
./setup.sh -console -deploy -record 
```

5) Install SAS Software -> SASFoundation + SAS Studio Basic + Hadoop libraries
6) Unselect Obsolete Maps Data
7) Installation all the way through but configuring SAS Studio to install under `/usr/local/SASHome/sas/studioconfig`
8) Following license was printed

```sh
Licensed SAS Foundation Software  Expiration Date
Base SAS                                             14FEB2019      
SAS Analytics Pro                               14FEB2019      
SAS/ACCESS Interface to Hadoop    14FEB2019      
SAS/GRAPH                                        14FEB2019      
SAS/STAT                                            14FEB2019  
```

9) Upload *.tar.gz to Azure Storage Blob
10) Docker build

```sh
docker run --name sas -d -p 8561:8561 -p 8591:8591 -p 38080:38080 -p 38591:38591 -p 52861:52861 -p 8801:8801 -p 8811:8811 -p 8821:8821 sas4c:9.4-studio
```

11) Go to SAS Studio at localhost:38080
12) Run the following example

```sh
/* A simple Hello World SAS program */

/* Print Hello World */
data _null_;
   put "Hello, World!";
run;

/* Output current version of SAS */
proc product_status;
run;

/* Get license information */
proc setinit noalias;
run;

/* Output total memory size default value */
proc options option=MEMSIZE value;
run;

/* Output total sort size default value */
proc options option=SORTSIZE value;
run;

/* Output number of threads default value */
proc options option=CPUCOUNT value;
run;
``` 

```sh

 1          OPTIONS NONOTES NOSTIMER NOSOURCE NOSYNTAXCHECK;
 72         
 73         /* A simple Hello World SAS program */
 74         
 75         /* Print Hello World */
 76         data _null_;
 77            put "Hello, World!";
 78         run;
 
 Hello, World!
 NOTE: DATA statement used (Total process time):
       real time           0.00 seconds
       cpu time            0.00 seconds
```

Note: I think Studio worked before wasn't hitting the correct run before.

13) For Spawner + Workspace Server enable trace in logs
14) On local computer running saspy via python3

```sh
>>> saspy.SASsession(iomport=38591)
Using SAS Config named: iomlinux
Please enter the IOM user id: sas
Please enter the password for IOM user : 

SAS process has terminated unexpectedly. Pid State= (17050, 256)
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '--add-modules=java.corba', '-classpath', '/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.svc.connection.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/log4j.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.security.sspi.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.core.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '54904', '-stdoutport', '54905', '-stderrport', '54906', '-iomhost', 'localhost', '-iomport', '38591', '-user', 'sas', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
Access Method         = IOM
SAS Config name       = iomlinux
WORK Path             = /
SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
SASPy Version         = 2.2.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = No
Python Encoding value = utf8
```
## Spawner Log

```sh
2018-03-21T17:35:39,607 INFO  [00000063] :sas - New client connection (9) accepted from server port 38591 for user sas. Encryption level is Credentials using encryption algorithm SASPROPRIETARY. Peer IP address and port are [::ffff:172.17.0.1]:33202 for APPNAME=SASPy.
2018-03-21T17:35:39,618 INFO  [00000063] :sas - Created process 439 using credentials sas (child id 3).
2018-03-21T17:35:39,844 INFO  [00000064] :root - New out call client connection (10) for launched server (child 3).  Peer IP address and port are [::ffff:172.17.0.2]:48944.
2018-03-21T17:35:39,857 INFO  [00000064] :root - Client connection 9 for user sas closed.
2018-03-21T17:35:40,385 INFO  [00000079] :root - Client connection 10 for user sas closed.
2018-03-21T17:35:40,502 INFO  [00000062] :root - Process 439 owned by user sas (child id 3) has ended.
2018-03-21T17:39:24,305 INFO  [00000074] :sas - New client connection (11) accepted from server port 38591 for user sas. Encryption level is Credentials using encryption algorithm SASPROPRIETARY. Peer IP address and port are [::ffff:172.17.0.1]:33852 for APPNAME=SASPy.
2018-03-21T17:39:24,317 INFO  [00000074] :sas - Created process 486 using credentials sas (child id 4).
2018-03-21T17:39:24,505 INFO  [00000083] :root - New out call client connection (12) for launched server (child 4).  Peer IP address and port are [::ffff:172.17.0.2]:49592.
2018-03-21T17:39:24,513 INFO  [00000083] :root - Client connection 11 for user sas closed.
2018-03-21T17:39:24,994 INFO  [00000098] :root - Client connection 12 for user sas closed.
2018-03-21T17:39:25,111 INFO  [00000081] :root - Process 486 owned by user sas (child id 4) has ended.
```

## Workspace Server

[saspy.txt](https://github.com/sassoftware/saspy/files/1834507/saspy.txt)

**Comment by sylus** [comment]
Here is log will full trace.

[WorkspaceServer_2018-03-21_c166b2a672d2_720.log.txt](https://github.com/sassoftware/saspy/files/1834569/WorkspaceServer_2018-03-21_c166b2a672d2_720.log.txt)

**Comment by sylus** [comment]
Saw in a recent email that is appears we do need SAS Integration Technologies for this call to work (licensed function is a Workspace Server for Local Access). At least tracked this down though wonder why this never made it into standard logs and needed tracing to debug it. Thank you so much for your assistance!

Was recommended in email that we can leverage STDIO which since this is a docker container isn't suitable as can only either leverage STDIO via SSH, or IOM. The IOM method is vastly preferred since is just port based and doesn't require me to install SSH in the container etc.

Technically this is still local communication but yay licensing :S

**Comment by tomweber-sas** [comment]
So it does turn out that the local only access is the issue. Usually when IOM fails, there's an error message that gets back to saspy. In this circumstance, that didn't happen. I will investigate that to see if I can address that. Looking through the logs where the error occurs, make me think that the point in my java client where this is failing, may not be returning that error to saspy. I've never seen this fail there before.
@sylus if you wouldn't mind, I can give you a new version of the saspy jar, with changes to catch this error (I have to assume I'm getting it from IOM) and see if that works. I don't have an environment here with that constraint to test this out. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
[saspyiom.jar.tar.gz](https://github.com/sassoftware/saspy/files/1838645/saspyiom.jar.tar.gz)
@sylus Here is a new saspyiom.jar built for 2.2.1, which is what you are running. Can you possibly swap this out for the one you have and try 2 tests for me (with workspace server trace logging)?
1) just try connecting, and send me the workspace server trace log, and the saspy error output from the attempt.
2) same thing, but provide the wrong password when trying to connect. This way I can compare the logs to try to better understand the timing of the failure you are getting.

I think this is still in the initial connection from my client code, but I can't prove that. I want to tell whether I'm getting an error but not getting it back to saspy or if IOM isn't giving me the error.
Thanks you very much!
Tom

**Comment by tomweber-sas** [comment]
Actually, if you haven't gotten to this yet, try this jar, I was able to get a little better diagnostic in this I believe.
[saspyiom.jar.tar.gz](https://github.com/sassoftware/saspy/files/1838855/saspyiom.jar.tar.gz)
Thanks,
Tom

**Comment by sylus** [comment]
I gave this a shot and get the error of invalid license right away, which is great!

```sh
/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz
❯ python3                                                                                 
Python 3.6.4 (default, Mar 13 2018, 08:32:25) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> saspy.SASsession(iomport=38591)
Using SAS Config named: iomlinux
Please enter the IOM user id: sas
Please enter the password for IOM user : 
We failed in Languare Service setup
The requested function was not performed due to an invalid or expired product license.

SAS process has terminated unexpectedly. Pid State= (1482, 256)
SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '--add-modules=java.corba', '-classpath', '/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.svc.connection.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/log4j.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.security.sspi.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/sas.core.jar:/opt/sasinside/SASHome/SASDeploymentManager/9.4/products/deploywiz__94400__prt__xx__sp0__1/deploywiz/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '49811', '-stdoutport', '49812', '-stderrport', '49813', '-iomhost', 'localhost', '-iomport', '38591', '-user', 'sas', '']

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
Access Method         = IOM
SAS Config name       = iomlinux
WORK Path             = /
SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
SASPy Version         = 2.2.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = No
Python Encoding value = utf8
```

**Comment by tomweber-sas** [comment]
Awesome! Thanks William! That saved me a ton of time to try to reproduce that here.
I will enhance saspy to catch and return these errors. This shows it is happening in some interface calls that have no exceptions defined for them, which is why I wasn't catching them in my code. But, now I can.

Thanks!
Tom

**Comment by sylus** [comment]
Okay I have tested this out now with the SAS integration technologies installed and it now works via saspy!

```sh
❯ python3                                                                                                                 
Python 3.6.4 (default, Mar 13 2018, 08:32:25) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> saspy.SASsession(iomport=38591)
Using SAS Config named: iomlinux
Please enter the IOM user id: sas
Please enter the password for IOM user : 
SAS Connection established. Subprocess id is 24353

Access Method         = IOM
SAS Config name       = iomlinux
WORK Path             = /tmp/SAS_work88C800000099_151b176af8e6/SAS_workBBC500000099_151b176af8e6/
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 2.2.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = UTF-8
Python Encoding value = utf8
```

@tomweber-sas  Thank you so much for your help on debugging this and taking the time. Your awesome! :)

**Comment by tomweber-sas** [comment]
That's fantastic William! I'm so glad this fits into the architecture you're using. That is really cool!
I have to give hats off to our Tech Support team; they've seen it all and were able to accurately tell the problem, and know what the answer was, and the account team got you the piece you needed to validate this quickly. I bet you guys are going to do some cool stuff with this!

Thanks!
Tom
