### ISSUE TITLE
Can SASPy be access from Jupyter Hub running on a Grid gsub node?

### ISSUE THREAD

**Issue by jrmathieu63** [sassoftware/saspy#119]
We are planning on installing SASPy on our Grid platform and would prefer to manage the access from our SAS GSUB node.
We do not currently have Python 3 + installed and need to also determine the best way to install both Python and Jupyter Hub.  This appears to be best handled with an Anaconda distribution since tit would handled both.
Would be able to access SAS using Jupyter Hub from this node through an IOM configuration?
Since SAS batch and scheduled jobs run on this server for all Grid gsub submission, it appears to be best solution to simplify the installation and configuration requirements.

**Comment by tomweber-sas** [comment]
Ok, I'm not sure if 
```
manage the access from our SAS GSUB node.
```
implies anything about how saspy runs on the grid. Is it implying that saspy wouldn't be connecting to a workspace server, but rather to a 'batch' server or something different like that (if there even is something like that)? That would be an issue.
If it's really just about 'where' saspy and jupyter... are installed, then that shouldn't be an issue. saspy uses IOM to connect to an object spawner and request a workspace server. As long as that's still what you will have it do, it shouldn't matter where the client side (jupyter, python, saspy) lives; either on the Grid or off. It should still be configures as Remote; specify the IOMHOST= object spawner machine, and IOMPORT= workspace server port.

Yes to anaconda. I've found that tends to have all of the pieces already there and ready to go. I haven't used/installed Jupyter Hub, so I'm not positive that's in there, but it very well may be. I know Jupyter Notebook is. 

Others are using Jupyter Hub and SAS Grid already, so that can all work. One think I can mention, is that I think the end users each might need their own home directories on the Juptyer Hub machine. I don't know if that is something you want or don't want on that particular node. Or if that's already set up?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, so as long as you're not thinking you can run saspy via SASGSUB or anything like that, this all sounds fine. Already having users's home dirs there should make this easy.
Jared has more experience with Jupyter Hub. I've never used it or set it up. I'll check with him @jld23 (Ha, just did :)). He would have a better recommendation if it makes a difference, for JH and which Anaconda.

saspy has support for a number of things W.R.T. SAS Grid. (just FYI)
1) it supports Grid HA (you can list multiple objspawn nodes, in case one's down, it will try others) 
2) you can use grid option set to direct saspy work to specific LSF work queues (see #82)
3) users can store their credentials in a .authinfo file in their home dir, so saspy (from Jupyter Hub) will not need to prompt for metadata cred's when starting a session. Another reason user home dirs where jupyter Hub is is a good thing.
4) the Appname for grid submitted jobs is 'SASPy'. This is how number 2 above routes saspy jobs to the queus you set, and how you can tell these are saspy jobs when looking at the running jobs in grid manager.

Don't hesitate to ask if you have any other questions setting this up and getting running! Or if there's anything else you need ahead of time. It sounds like you should be good.
Tom

**Comment by jrmathieu63** [comment]
Tom,

We are Kerberos enabled so there is no requirement for credentials for us.  Hopefully SASPy can leverage the kerberos configuration we have in place for the environment.
Might have to review the LSF work queue option since this would be help to identify the activity to assist with any issues.

Thanks for all your help and recommendations,

**Comment by tomweber-sas** [comment]
Ah, what OS is your grid running on? IOM supports single signon (sspi ?) via Integrated Windows Authentication (IWA), But that only exists on Windows client. I believe it supports Kerberose for that case too. IOM doesn't have an sspi module for Linux as a client, so I don't think IOM Java client supports this from a Linux client. 
Tom

**Comment by jrmathieu63** [comment]
RHEL 6.9  / Linux.
We are using VAS/QAS/ Dell Authentication services.
The ObjectSpawner is setup to leverage SSPI.
Will have to investigate this since it would be Java IOM for SASPy.
Should have expected this.

Thanks.

**Comment by tomweber-sas** [comment]
Let me dig a little here and see if there's been any work on getting support for this on a Linux client. You're not the first to request this. I have found another tech support track and even a defect for this enhancement request. I'll check and see if anything's been done.
Tom

**Comment by tomweber-sas** [comment]
Well, we have one Tech Support (TS) track open with this request. And development has a defect for enhancing this. But, the defect is for our next release which isn't till the end of the year. To try to expedite this, would you want to open a TS track for this, requesting the enhancement, and maybe with multiple tracks, we can get some leverage to get make this higher priority? It would probably need to be a hot fix too, so you can use it with your existing system; what version of SAS are you running?

In the mean time, will it be ok for users to create the .authinfo file in their home directories (one time setup), and use that until SSPI gets done on Linux?

Thanks,
Tom

**Comment by jrmathieu63** [comment]
We are SAS 9.4 M3 at the moment but working on migrating to SAS 9.4 M5.    No an issue with the ,authinfo file, just would like to avoid it.

Thanks,
John Mathieu

**Comment by jld23** [comment]
From a Jupyter perspective. I would Jupyter Lab instead of Jupyter notebook (Lab includes notebook so you aren't loosing anything). I haven't set up the combination buy here is a [repo](https://github.com/jupyterhub/jupyterlab-hub) with instructions.
We have found some rendering issues with recent component updates of Jupyter Notebook that don't appear in Jupyter Lab. If you use Lab then any version of Anaconda should be fine. 

The connection mechanism for SASPy to SAS will be the same regardless of using Notebook or Lab. There is also a [SAS Kernel](https://github.com/sassoftware/sas_kernel) if you have SAS programmers that want to use this environment

**Comment by jrmathieu63** [comment]
Jared,
Thanks for this feedback since has cleared questions I had regarding Anaconda.  I noticed that Jupyter Lab was include but not Jupyter Hub, which is what I was planning on installing and using at first. Will have to determine which is best for us since we do not know the actual use case yet but have received a few end users looking for access to SASPy.  A big plus about the SAS Kernel since I not aware that this would be required to enable Jupyter notebook functionality for SAS.   Hopefully once I have Anaconda installed I can get this all configurated and operational quickly.

**Comment by jld23** [comment]
To clarify, jupyter hub is an authentication framework that wraps lab or notebook. The user must authenticate then there experience will be the same as if they were using lab or notebook directly. 
		
		

		
	




On Thu, Mar 29, 2018 at 9:49 AM -0400, "John Mathieu" <notifications@github.com> wrote:












Jared,

Thanks for this feedback since has cleared questions I had regarding Anaconda.  I noticed that Jupyter Lab was include but not Jupyter Hub, which is what I was planning on installing and using at first. Will have to determine which is best for us since we do not know the actual use case yet but have received a few end users looking for access to SASPy.  A big plus about the SAS Kernel since I not aware that this would be required to enable Jupyter notebook functionality for SAS.   Hopefully once I have Anaconda installed I can get this all configurated and operational quickly.
