### ISSUE TITLE
Cannot install saspy: Cache entry deserialization failed, entry ignored

### ISSUE THREAD

**Issue by vivi1233** [sassoftware/saspy#134]
Hi

My environment: 
Python:3.6
Pip: 9.0.3
SAS Enterprise Guide: 7.1 (32-bit)

I tried to install SASPy using 'pip install saspy' and 'pip install https://github.com/sassoftware/saspy/releases/download/v2.2.4/saspy.tar.gz' but both way failed. 

The error message: Cache entry deserialization failed, entry ignored

I tried to upgrade my pip but it shows up-to-date and Cache entry deserialization failed, entry ignored again. 

I am not sure what's wrong and how to fix it. Please someone help me with this issue.

Thank you in advance,

Vi

**Comment by vivi1233** [comment]
Hi Tom,

I tried pip install --no-cache-dir saspy and it solved the issue of Cache entry deserialization failed, entry ignored, however, I am still not able to install saspy.

The error: **Could not find a version that satisfied the requirement saspy (from version :) No matching distribution found for saspy.**

From my research, I am not sure is it because my sas enterprise guide is 7.1, which  does not match the requirement (sas 9.4)? 

Thanks,

Vi

**Comment by tomweber-sas** [comment]
Well, the pip install for saspy won't know anything about SAS (right or wrong versions), so that's not the problem this time. This is still likely the next part of whatever problem is going on that --no-cach-dir didn't happen to work around. I just don't know what all is messed up with your pip/python system, so I don't know what might fix it.

I expect you'l be running saspy from windows, connecting to a workspace server (given EG), so the IOM access method? When you get this installed, you will need a few jars for the IOM client, which can be found in a SAS install directory. You may find these in your local EG install (same named jars), and they may or may not work. I've see some cases where they didn't. But, you can try them and see, and if not, copy the jars from a regular SAS install (the workspace servers count as that, so you have them there).
Tom

**Comment by vivi1233** [comment]
Hi Tom,

So I called the IT team in my department and they successfully installed it. I think this is the fire wall issue ,which block my installation previously. 

The warning 'Cache entry deserialization failed, entry ignored' was still there but after all the installation has completed.

Thanks,

Vi

**Comment by tomweber-sas** [comment]
ok, great. At least you got it installed. Really not sure what was going on with pip, Let me know if you have any other troubles.
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Seems like you're up and running. If you have any other issues or questions, just let me know. Gonna close this one.
Thanks!
Tom
