### ISSUE TITLE
PROC PRINT OVERLAP ISSUE

### ISSUE THREAD

**Issue by lyncodes** [sassoftware/saspy#140]
![sas_print_cahr_overlap](https://user-images.githubusercontent.com/34979383/41189671-3aff8f36-6c04-11e8-9d13-35204d1a620f.JPG)

when a dataset have too many columns,the display will be squeeze with the jupyter notebook,but with jupyter lab is fine and i have not try more columns

![sas_print_cahr_overlap_with_lab](https://user-images.githubusercontent.com/34979383/41189667-3164de68-6c04-11e8-8723-c82bc330da41.JPG)

maybe you don't need to fix this,cause i think the lab is the future!

**Comment by tomweber-sas** [comment]
@lyncodes Yes, this is a bug in ipython notebook:
https://github.com/jupyter/notebook/issues/3413#issuecomment-385018995
Jupyter Lab doesn't have this problem, so using it is the best solution for now. Previous versions of jupyter noteboook also don't have this problem.  The only workaround for that version of notebook is to return tables as pandas data frames instead of HTML. The rendering of dataframes in that version doesn't have this overlap problem, it was just HTML that got broke.
Tom

**Comment by tomweber-sas** [comment]
@lyncodes I'm cleaning up some old issue. I'm going to close this as I can't fix Notebook, but there are versions of it out there without this issue. I simply have to use a version without this problem too, myself.
If there's anything else I can do, just let me know!
Thanks,
Tom
