### ISSUE TITLE
Missing - SAS to Pandas

### ISSUE THREAD

**Issue by PaalSchau** [sassoftware/saspy#154]
Hi Tom,

I run this code in SAS:

libname Mylib "C:\tmp";

data Mylib.NyTest ;
  length a 8. b $10.; 
  a=1;   b='Data1'; output;
  a=.;   b=''; output;
  a=3;  b=''; output;
  a=.;   b='Data4'; output;
run;

And this code in Python:
import pandas as pd
import saspy
sas1 = saspy.SASsession(cfgname='winlocal')
sas1.saslib('Mylib', path="C:\\\tmp")
dataset_sas=sas1.sasdata('NyTest','mylib')
dataset_pd1=dataset_sas.to_df()
dataset_pd2=dataset_sas.to_df_CSV()

And:
`dataset_pd1.isnull().sum()`
Out= a=2 and b=0

And:
`dataset_pd2.isnull().sum()`
Out= a=2 and b=2

Why is missing treated differently and what is the difference between "to_df()" and "to_df_CSV()" ?

**Comment by MagicalAsh** [comment]
It looks like to_df_csv() actually converts empty strings to NaN, which shouldn't happen. Strange, I'll look into it more.

**Comment by PaalSchau** [comment]
Thanks, but I thought it was csv() that was correct! // Paal

**Comment by tomweber-sas** [comment]
Hey, sorry, I've actually been looking into this but hadn't posted back. Yes, I believe that the 'correct' behavior should be NaN's for character data, from pythons perspective. 
In fact is you do the following, it also corroborates that conclusion:
```
#given ds1 is the SAS data set in question
>>> ds1.dsopts={'where':'b is null'}
>>> ds1
Libref  = WORK
Table   = a
Dsopts  = {'where': 'b is null'}
Results = text

>>> ds1.head()


                                                           The SAS System                         09:40 Thursday, August 9, 2018   3

                                                           Obs    a    b

                                                            2     .
                                                            3     3
```
I see that my data step in the sd2df() case is sending over a single blank for the SAS Missing (whichis all blanks) for character data. I need to either adjust the data step so that when I get the data, the dataframe creation method I use gets what it needs to create NaN's instead of 1 char long blank or convert those to NaN's after the final DF is created. I still need to play around to see what the best implementation is. 
But, I believe the sd2df() should be producing the same as the _CSV() version for this issue.
I will fix this and get it to master before I build a new Pypi package; having the NLS fixes that are at master and ready to go. Get that and this into the next 2.2.7 release.
Thanks for finding this and letting me know!
Tom

**Comment by tomweber-sas** [comment]
Ok, I've pushed a fix for this to master. Can you give it a try.

Here's my test code (both access methods; STDIO and IOM):
```
import saspy
sas = saspy.SASsession(cfgname='sdssas')
#sas = saspy.SASsession(cfgname='iomj')
sas


ll = sas.submit('''
data a;
length a 8. b $10.;
a=1; b='Data1'; output;
a=.; b=''; output;
a=3; b=''; output;
a=.; b='Data4'; output;
run;
''')

print(ll['LOG'])

ds1 = sas.sasdata('a', results='text')
df1 = ds1.to_df()
df2 = ds1.to_df_CSV()

ds1.head()
df1.head()
df2.head()

df1.dtypes
df2.dtypes

ds1.dsopts={'where' : 'b is null'}
ds1.head()
```

Before:
```
>>> df1.head()
     a      b
0  1.0  Data1
1  NaN
2  3.0
3  NaN  Data4
>>> df2.head()
     a      b
0  1.0  Data1
1  NaN    NaN
2  3.0    NaN
3  NaN  Data4
>>>
>>> df1.dtypes
a    float64
b     object
dtype: object
>>> df2.dtypes
a    float64
b     object
dtype: object
>>>
>>> ds1.dsopts={'where' : 'b is null'}
>>> ds1.head()

                                                           The SAS System                         12:00 Thursday, August 9, 2018   3

                                                           Obs    a    b

                                                            2     .
                                                            3     3

>>>
```
after:
```
>>> df1.head()
     a      b
0  1.0  Data1
1  NaN    NaN
2  3.0    NaN
3  NaN  Data4
>>> df2.head()
     a      b
0  1.0  Data1
1  NaN    NaN
2  3.0    NaN
3  NaN  Data4
>>>
>>> df1.dtypes
a    float64
b     object
dtype: object
>>> df2.dtypes
a    float64
b     object
dtype: object
>>>
>>> ds1.dsopts={'where' : 'b is null'}
>>> ds1.head()


                                                           The SAS System                         12:01 Thursday, August 9, 2018   2

                                                           Obs    a    b

                                                            2     .
                                                            3     3
>>>
```

**Comment by tomweber-sas** [comment]
BTW, the method used to create the data frame in sd2df (from_records) doesn't create NaNs even when the value is a null string ('') instead of ' ' (which I was passing). So, I had to convert these post DF creation. The read_csv pandas method does convert NaN's, as you see, when it had null strings for values.
This change makes the behavior the same, which also matches SAS regarding Missing Char values. In SAS, all blank is considered Missing.

Thanks,
Tom

**Comment by PaalSchau** [comment]
Wow Tom, tanks for quick response, I have downloaded "Master" and has tried this issue (154) and issue (147) and it all seems good. Thanks

By the way, the version number in "version.py" is '2.2.6.01' is that correct or should it be '2.2.7.01'?

// Paal

**Comment by tomweber-sas** [comment]
Closing this, as it's fixed :)
Tom
