### ISSUE TITLE
saspy and Kerberos

### ISSUE THREAD

**Issue by hani1814** [sassoftware/saspy#158]
Hello,

We have been successfully using saspy embedded in python or a jupyter SAS kernel using IOM. Our environment is kerborised but the user is prompted for a user and password when first used in a session. 

We are planning to schedule some of the saspy code we have developed using apache airflow and want to leverage kerberos (i.e. not embed a username / password).

We are using linux command line python and / or Jupyter.

Look forward to your reply on how we can use kerberos with saspy

**Comment by tomweber-sas** [comment]
Hey, sorry for the delay. I was out last week.
The IOM access method does support the ability to use Kerberos or IWA (Integrated Windows Authentication) for connections to Workspace servers that are configured for that. However, the IOM client only has support for that from Windows, not Linux; there's a special library that was written for the IOM client code for this (but only on Windows). The Workspace server can be running on either system and have that authentication mechanism in place, but there was not an interface library written for this for the Linux side of the IOM client. 

There is, however, the ability to use an .authinfo file with credentials so that you don't have to be prompted or enter user/password from both the linux and windows clients. I know that isn't Kerberos support from Linux, but it does at least eliminate having to enter credentials.

This isn't the first time this has come up, I'm not sure if the IOM client folks are working on support for this for the Linux client. I'll try to check on this and see if there's been any assesment for doing this.

Tom

**Comment by tomweber-sas** [comment]
As a follow up, there is an open defect (our bug / feature system), for implementing this on linux. However, there is no active work or even a commitment to do this reflected in that. If this is something you need and can't work around, I would suggest contacting tech support and requesting this. Customer requests hold more weight then me telling other groups that they should implement features :)
The defect was actually created due to another customer requesting this same feature. 
Let me know if there's anything else I can do. I'm going to close this, as there's nothing I can do to make this work, from the saspy end.
Thanks!
Tom
