### ISSUE TITLE
Output "proc sql" results as a CSV?

### ISSUE THREAD

**Issue by moshekaplan** [sassoftware/saspy#161]
I'm currently retrieving data as a CSV by creating a temporary table with `proc sql; CREATE TABLE lib.table AS SELECT ...` and then using `to_df_CSV` to convert it to CSV.

Is it possible to directly get the output of a SAS job that begins with `proc sql; SELECT ...` as a CSV file?

Ideally, something like `session.submit(job, results='csv')` would be best.

**Comment by moshekaplan** [comment]
> proc sql, temp file, csv:

That's what is currently being done.

The reason the other methods don't work is because there's some processing being performed in the SELECT statement itself: CASE statements, TRIM, UPPER, and the like.

**Comment by tomweber-sas** [comment]
Ok, so you're sql is more than what dsopts can do.
So, does the proposed method look like what you'd want?
```
lst = sas.sql2csv(query=’proc sql …’, file=‘file path for csv file', table=’temp1’, libref=’work’)
```

**Comment by moshekaplan** [comment]
Yes,

My only concern is the potential for a 'stale' table left over in the database, if the script was abruptly terminated.

**Comment by tomweber-sas** [comment]
what database? I'm not sure I understand.

**Comment by moshekaplan** [comment]
If you're effectively creating a temporary table and then dumping that to CSV, what would happen if the Python script failed after the temporary table was created, but before it was deleted? My understanding is that the temporary table would be left on the SAS backend.

**Comment by tomweber-sas** [comment]
Hey @moshekaplan. I'm cleaning up and going to close this one. Never really got to the point of creating a dedicated method for this specific case. But, there have been many enhancements since we were on this thread, including better support for Views. I think the existing API provides a number of ways to accomplish this with only two methods. And you could always wrap those in a function you define so you just use that, too.
Thanks,
Tom
