### ISSUE TITLE
translating SAS code into Python (proc forest) - need better doc please...

### ISSUE THREAD

**Issue by sascis** [sassoftware/saspy#179]
I'm trying to use the saspy and swat packages together to ultimately implement this sort of thing in as much python as possible:
/* -------------------------- */
cas; 
caslib \_all\_ assign; 
 
data casuser.pricedata; 
    set sashelp.pricedata; 
run; 
 
proc forest data=CASUSER.PRICEDATA; 
     target sale / level=interval; 
     input price / level=interval; 
     savestate rstore=casuser.myAstore; 
     id price; 
run; 
/* -------------------------- */

But the saspy documentation (surrounding the forest proc) is not really helping me figure things out.
1. There is no specific example of how to pass parameters to the forest() method, guessing is only getting me so far.  An example for any of the proc-targeted methods would probably suffice, and I can extrapolate the rest. (Perhaps addressing #3 fixes this too)
2. The 'savestate' parameter is new for Viya, but isn't specifically accepted by the method, so I need to know how to pass additional information ultimately onto the proc.  Is there an 'other_args' parameter?
3. The link in the doc to more information:  (https://support.sas.com/documentation/solutions/miner/emhp/14.1/emhpprcref.pdf) takes me to a password-protected page which I can't figure out how to log into.

**Comment by jld23** [comment]
@sascis I'm finishing up a pull request that will change how this is done. So I would recommend holding off a few days. There is a `stmtpassthrough` that allow a user to directly send code to the SAS server within the procedure. In the specific case of `Forest` the code if broken and [calling Proc HPCLUS](https://github.com/sassoftware/saspy/blob/master/saspy/sasViyaML.py#L90). This will also be fixed in the pull request.

**Comment by jld23** [comment]
@sascis Now that version 2.4.0 has been released you will see better documentation on the methods along with tab-complete. Please update your install and give it a try
