### ISSUE TITLE
Revise Mutable Default Arguments

### ISSUE THREAD

**Issue by hhubbell** [sassoftware/saspy#180]
This isn't really a bug, but it should be addressed to avoid potential issues in the future.

Certain method signatures contain default arguments that are mutable data types (`list`, `dict`).  This is a "Common Gotcha" that could cause inconsistent behavior if any of these arguments are modified by the method.

See the following: [Common Gotchas](https://docs.python-guide.org/writing/gotchas/)

**Example:**
```python
def submit(self, ..., prompt: dict = {}):
    ...
```
The correct signature should be:
```python
def submit(self, ..., prompt: dict = None):
    prompt = prompt if prompt is not None else {}
    ...
```

I have a commit that I will submit as a PR to fix this issue.

**Addtional:**
Tangentially, `sasbase.py`'s `submit()` method defaults `prompt` to a `list`, not a `dict`.  This is inconsistent with the type hint.  In my PR I have updated `prompt` to be a `dict`.

**Comment by tomweber-sas** [comment]
Thanks for catching that and cleaning all of those up! I've merged this in and I ran the test suite against it for both access methods. That did turn up one cut-n-paste error. In read_csv it was setting prompt instead of opts. Prompt was in the previous method you fixed. I've tweaked that so it's all passing.

Thanks again for fixing this for me and contributing!
Tom

**Comment by hhubbell** [comment]
Thanks Tom!

Sorry about that error - it totally slipped by.
