### ISSUE TITLE
Table locked by another SAS session

### ISSUE THREAD

**Issue by Rhadadi** [sassoftware/saspy#199]
I created a SAS session on Jupyter notebook using SASPY and ran a process. It took a long time and got stuck, hence I restarted the Kernel. When I created a new session and wanted to access the source table, I received an error message that another process has the lock. 

**ERROR: A lock is not available for X.DATA.  ERROR: Lock held by process 23243.**

How may I unlock the table above by accessing the other session or process and stop/close it?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. Linux]
 - SAS Version: [e.g. 9.4M3]
 - SASPy Version: [e.g. 2.2.7]

**Additional context**

**Comment by tomweber-sas** [comment]
Sorry to hear that. Where is SAS running? on your same machine as python? A remote machine? Windows or Linux? Normally, restarting the kernel in jupyter (which terminated the python process) will cause saspy to terminate the SAS session it's connected to. It sounds like something didn't happen in this circumstance. You have the process id, are you able to access that system and kill that process yourself? If not, depending on what OS it is, we may be able to do it remotly.
Tom

**Comment by tomweber-sas** [comment]
Also worth mentioning. Jupyter has an 'interrupt kernel' feature, which is basically a keyboard interrupt (CTL-C).  If you are in a situation where a saspy method is executing, using that should allow you to interrupt saspy such that you can either stop the current method, or, at least subsequently restart the kernel with saspy going through the normal shutdown process.
Tom

**Comment by tomweber-sas** [comment]
Any updates on this? 
Thanks,
Tom

**Comment by Rhadadi** [comment]
Tom, here is my responses:

Where is SAS running? **on local machine but running the code to the SAS remote. a winlocal SAS session with singon to the remote SAS.**

```
import saspy
import getpass
sas = saspy.SASsession(cfgname='winlocal')
MDC_pass = getpass.getpass(prompt='Password for MDC: ', stream=None) 

```
next cell:

```
%%SAS sas
%let test=xxxxxxxx 7551;                                                                                                                                                         
options comamid=TCP remote=test;                                                                                                                                                               
signon username=xxxxxxxpassword=MDC_pass ; 
```
 on your same machine as python? **Python is on my personal machine. SAS session is on my local but it send the codes to the remote SAS.**
A remote machine? **Yes**
 Windows or Linux? **Local is windows, remote is Linux**
 You have the process id, are you able to access that system and kill that process yourself? **I am not sure how to use ID to kill the session and unlock the data table.**

Thanks Tom again

**Comment by tomweber-sas** [comment]
Oh, ok. So it's a table on the remote linux system that's locked. And, are you sure it's locked because of the session you had? It's been decades since I used SAS/Connect, but I would think if the connection was broken it would shutdown on the remote side, and tables wouldn't remain locked. But I don't have enough info to know what has or hasn't happened. 

Can you log on to that linux system to see what that process is? To see if it was your Connect server side process, as opposed to someone else, who's connected and accessing that file? Can you submit X commands on the remote system? If that's allowed, then you can at least explore the system remotely that way, if you can't ssh to the machine directly.

If none of this make sense, or you can't do any of it, is there an administrator for that system who could do these things and verify that process it says has it locked was your connect session that is still running and terminate it for you? Can you reconnect to that session (I don't know if that's a possibility or not)?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
The other though is if your client side SAS process didn't actually shut down somehow. It's conceivable that, even though the python process went away when you restarted the kernel, and the java process saspy uses to talk IOM to the local SAS went away, that if that SASsession was in the middle of some SAS/Connect work, it might still be running on your machine; orphaned, but still keeping the server side connected. 
Again, I don't have enough to know if this could be the case. But you can look at the processes on your machine to see if this happens to be it or not. That's easy enough.

**Comment by Rhadadi** [comment]
Thanks. I terminated the session by connecting to the SAS server directly.

**Comment by tomweber-sas** [comment]
Ok, good deal. This is an interesting case, using SAS/Connect. I do find it interesting to see all the different ways people are using this. Hopefully, if you interrupt the kernel, instead of terminating it, this might be able to shut down cleanly. I'd have to actually try using connect in this case to see what might be happening though. So I can't say for sure.
Would you like to dig into this deeper, or are you ok for now, seeing as you solved this issue?
Thanks!
Tom

**Comment by Rhadadi** [comment]
Tom-- It is solved on my end.  


--
Rooholah Hadadi
Phone: 786.361.5888
E-mail: R.Hadadi@gmail.com

**Comment by tomweber-sas** [comment]
Cool, I'll close this. Just let me know if you need anything else!
Tom
