### ISSUE TITLE
Is possible that saspy execute a .egp?

### ISSUE THREAD

**Issue by ur-mayara** [sassoftware/saspy#202]
At now, I did an example to open a Sas Session and get the data from a SasHelp table locally to test. However, I need to do a python code to connect and starts an exists .egp process. After that, get the output and do more somethings on python to conclude.

I would like to know if saspy has any method to execute a .egp, like an user starts on sas client. 

Basically, what I need to do is reduce users manual interventions to guarantee more speed to finish a big process, without rewrite sas code on python. 

Thank you for any help.

**Comment by tomweber-sas** [comment]
I'm afraid saspy doesn't know anything about EG Project archive files. You can use saspy to interact between running SAS code, and moving data or variables between python and SAS and getting results, and doing other python work; all intermixed. But it can't somehow execute whatever's in an .egp file. 
Are you thinking of saspy just having a method to actually execute EG pointing to a .egp file (like a batch job), so it's part of an overall python/saspy script? Or more of saspy somehow trying to do something with the .egp file itself, doing some processing of what's in the file?
I can imagine the first case being plausible. But not really the second.

Thanks,
Tom

**Comment by ur-mayara** [comment]
Hello Tom.

Yes, I need only to execute an .egp and after that get the results. Is more like an batch behavior as you said.

I saw that is possible "consume" a sas process with a web service, but I really would consider this as a last option, because ask any change in sas project requires a burocratic process with an other company responsible for this one.

Have you any other idea for help me?

Thank you again.

**Comment by tomweber-sas** [comment]
Ok. I'll need to investigate this a little more. I had to google to find out what a .egp file was :)
So, I have no experience with them as of yet. A couple of questions though.
1) If I can cause the .egp to execute, EG will be running that on some SAS session somewhere. Local or remote. In either case, that SAS session will not be the same SAS session saspy is connected to (or even can connect to). So, anything that project did, for you to subsequently interact with, would need to basically be permanent data that another SAS session could then access. Is this what your projects do (create permanent data for later access)?
2) I ran EG and created a simple .egp file. I see that if I double click it, it opens in EG. So that looks good so far. I'll see how to run EG pointing at one of these file so it runs it (batch mode). If I can do that, then, if  # 1 above is ok, I think this could work.

Tom

**Comment by tomweber-sas** [comment]
Well, I've looked into this further, including talking with our resident EG expert. Turns out that batch submitting an EG Project archive file isn't something you can do directly, because that doesn't really make sense. It's not equivalent to batch submitting a SAS program (sas.exe my_prog.sas). That does run SAS in batch and executes the .sas program.
An EG Project file isn't simply a program that runs by itself. There's many different things that can be in one of those files and EG doesn't just 'run it all'. EG has an automation framework that you can use to orchestrate this. It can be done in Visual Basic or in .net or powershell, but there isn't a python interface for it currently. Maybe you could use that to put together a program to run what you want from the .egp files, and then execute that program from python?

Here's a couple links to some info on this EG Automation:
http://support.sas.com/resources/papers/proceedings12/298-2012.pdf
https://github.com/cjdinger/sas-eg-automation

Executing a command (program) from python isn't hard. So is if using this framework to create a program that runs whichever parts of the projects need to be run, it would be easy to 'batch submit' that program in the python/saspy script. Again, the only thing that jumps out at me that you would be able to then interact with would be data that those jobs created, which would need to be accessible from a separate SAS session that saspy would be using. 

Does that sound like something that would work to accomplish what you are trying to do?

Tom

**Comment by cjdinger** [comment]
If you have SAS Enterprise Guide **and** Python on the same Windows machine, then you should be able [to use pywin32](https://github.com/mhammond/pywin32) to automate EG like in the VBScript examples that @tomweber-sas mentioned.  I'm sorry that I don't have an official example of that right now, but I've heard from other users that this can work.

By automating EG, you can get access to the SAS code objects that are part of the project, or run process flows, or export results into your local environment.  All of this would be independent of the saspy infrastructure, which provides a direct connection between Python and SAS.

**Comment by ur-mayara** [comment]
Thank you so much @tomweber-sas  and @cjdinger 

The explanation of you helped me to better understand the purpose of saspy.

As the main idea is to run .egp as a step in a larger process, I will follow the tips that you gave, I believe it will work.

Thanks again for the quick return and help.

**Comment by lgpintomkt** [comment]
An EGP file is simply a zip file containing SAS programs and XML that describe the Process Flows. It's possible to execute EGPs using saspy, all you need is a custom script to interpret the process flow metadata from the XML and execute the SAS Programs in the correct order.

**Comment by kjnh10** [comment]
@ur-mayara 
I have the same complaint as you, so I created a tool to execute egp file from python or command line. 
https://github.com/kjnh10/saseg_runner

I hope this would help.

**Comment by cjdinger** [comment]
Nice job @kjnh10 ! Good to see a Python approach to using EG automation.
