### ISSUE TITLE
to_df_CSV is not parsing the sas dataset

### ISSUE THREAD

**Issue by mailbagrahul** [sassoftware/saspy#210]
Hi Tom,

I was trying to move sas dataset to dataframe by to_df which is larger in size(more than 1000 columns) and took more than expected. then I tried with to_df_CSV () but it couldn't parse it. see the screenshot.

file_info and list_tables are throwing index out of range exception. I need your assistance to fix this.

![image](https://user-images.githubusercontent.com/15937179/53136714-cae3a980-3534-11e9-8959-e787b7c9f29f.png)

Thanks!

**Comment by tomweber-sas** [comment]
Hey @mailbagrahul , yeah, that's a mess. Let's look at the log and see what it shows. Also, what version are you running here? Can you run this after these errors, so we can see what's in the log?
```
sas
print(sas.saslog())
```
Also, for the to_df_CSV, if you set the obs=5 (just to make it quoick and small) and keep the csv file we can look at it and see what might be the problem with importing it into pandas.
```
RNDPRM.dsopts={'obs' : 5}
df = RNDPRM.to_df_CSV(tempfile='local path for the csv file', tempkeep=True)
df.head()

fd = open('local path for the csv file', 'r')
dat = fd.read()
print(dat)
fd.close()
```
Thanks!
Tom

**Comment by mailbagrahul** [comment]
Ok. Still it is not parsing it. 

![image](https://user-images.githubusercontent.com/15937179/53263861-73a61c00-368f-11e9-8067-791ad1c5851e.png)

![image](https://user-images.githubusercontent.com/15937179/53263970-b36d0380-368f-11e9-8c94-57c670497b78.png)

**Comment by tomweber-sas** [comment]
@mailbagrahul I can't see any of the code from the log to see what was submitted. I see an error that the libref is blank which it says is invalid. But I can't see anything to know what was run in SAS.

I need to see the whole traceback, not only the last 2 that aren't in saspy at all. I need to see the whole part of the log for what was run in SAS for that saspy command.

I also need to see the output from submitting each of the following objects:
```
sas

RNDPRM
```
And, what was the contents of that csv file? Can you run the code I gave you to read it and display it? I need to see that also.

I don't have nay information here to know what is going on.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
And, of course, if you don't want to post all of that here, for any reason, you can send it directly to me in email; not problem with that.

Thanks again!
Tom

**Comment by mailbagrahul** [comment]
Haha. Whats your mail id?

Thanks!
Rahul

**Comment by mailbagrahul** [comment]
And one more thing I noticed is - When open a new session and attempt to move some data to GRIDWORK (thru data step from saspy) and tried to_df_CSV () it worked. Even file_info(), list_tables() worked well. If I execute .sas program which generated more outputs to GRIDWORK and then I tried to pull one data via CSV, it failed. Eventually file_info(), list_tables() failed. Something weird is happening. Any thoughts?

**Comment by tomweber-sas** [comment]
Yes, no problem there. And I delete anything I get through email once I gather what I need out of it. My email should be associated with my I'd, but it's tom.weber@sas.com
Thanks!
Tom

**Comment by tomweber-sas** [comment]
So, after some offline investigating, it seems as though this is due to me accidentally using rsplit() instead of rpartition() when I'm parsing some info from the log in 2 methods(file_info, list_tables), and the SAS script that is run in this job which disables most output to the log. I used split where I normally use partition and it happened to work under normal circumstances, but partition is what I use for that pattern. I fixed those 2 places and it works as expected regardless of setting options which were keeping most output from the log. The trouble here was that there's no output in the log to see what was submitted nor why noting was being written to the log.

Waiting to hear back that this has solved it for this whole use case. I can't verify that on my end.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
So, the only issue left inhere is the to_df_CSV() where you're getting some error in the proc export, which I can't see, so there is not data in the csv file, which results in the pandas.read_csv() getting the error:
pandas.errors.EmptyDataError: No columns to parse from file

The problems with list_tables() and file_info() are fixed at what's at master. Is that correct?

Thanks,
Tom

**Comment by mailbagrahul** [comment]
You are right. Thanks a lot for fixing it.

**Comment by tomweber-sas** [comment]
ok, thanks. So it's just the proc export failing that is left. In the original post above it has the following errors
```
ERROR: Invalid libref ''.
ERROR: Export unsuccessful.   See SAS Log for details.
```
And that's exactly what we need to see, is the log, or what SAS code was submitted. The other thing I had asked to see was what submitting that SASdata object returned
```
RNDPRM
```
As that will show what is set for the libref on that object. I can't think of how an empty libref (in the error) would happen. But I have to see some of this info to be able to at least speculate.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Trying to clean up old issues:

So we worked on this offline and it turned out that this problem only happens after submitting a SAS batch script which I can't see to know what it does. I do know that it turns off all output to the log, so we can't see what code is getting the error, and it changes many other options and runs a bunch of macro, but I have no idea what else it's doing.
The saspy method wouldn't get the error about a missing libref, so it's really unclear what code is driving that error. 
Without being able to see what that program is doing, I can't provide any kind of workaround, so I think this issue is at a dead end. Everything works fine if that program isn't submitted, so it's certainly something it's doing that ends up driving this error, but I don't know what that is.

Can we close this, or is there anything else I can try to do?

Thanks,
Tom

**Comment by mailbagrahul** [comment]
Hello Tom,

Thanks for helping me in figuring out the issue. Yes. It is due to options that we could not work further on this issue. Moreover, we are in the process of transforming our application code so hopefully, we should not see any problems after this. I will connect with you again if I need your help. You can close this ticket.

Thanks,
Rahul

**Comment by tomweber-sas** [comment]
Awesome, thanks Rahul. If there's anything else you need, just let me know!
Thanks!
Tom
