### ISSUE TITLE
On windows could I use saspy to determine sas session encoding.

### ISSUE THREAD

**Issue by garra2** [sassoftware/saspy#212]
It there any possible to use different encoding sas seesions, by use saspy(I can't change the sasv9.cfg file)?
Such as sometimes I need to use UTF8 rather than the default wlatin1.

**Comment by tomweber-sas** [comment]
I'm afraid the answer is no, sorry. The encoding is a start up option only. You can't change it once SAS is up and running. And the IOM client doesn't provide a way to specify overrides of how the server is already configured. So you can't override the encoding over IOM, which is the only access method available on Windows. 
Sorry about that,
Tom

**Comment by tomweber-sas** [comment]
The usual way to address this is to have more than one server confiigured, for each encoding, and you can connect to whichever one you want from saspy. That does work so you can run which one you want when you want.

**Comment by garra2** [comment]
How to get more than one server configured.？Could you show me a simple example?  many thanks!

**Comment by tomweber-sas** [comment]
Well, that depends. Can you tell me what your current set up is? It sounded like you have some remote workspace server you are connecting to, such that you can't access the configuration for it (can't edit the sasv9.cfg file). Is that a production workspace server? Who administers it and the metadata server and such? Or is it something different?

Thanks,
Tom

**Comment by garra2** [comment]
yes, Our sas is deployed on the remote server.Only our leader have the administrator privileges.By base sas, we Set different -config commands in the sas shortcut to control the encoding.

**Comment by tomweber-sas** [comment]
Yes, ok, that would be something your administrator would configure, Here's a link to doc on that:
https://go.documentation.sas.com/?docsetId=biasag&docsetTarget=n10001intelplatform00srvradm.htm&docsetVersion=9.4&locale=en
It's really just a metadata thing so that you can have more than one set of servers (saspy connects to the workspace server) defined so theycan be configured differently. The same object spawner can launch both of them.
In your saspy configuration definition you would want to specify which App Server you want to connect to. That would be using the 'appserver' key. So you would have two config definitions, one for each of the two app servers, and you would connect to which ever one you wanted at the time (utf-8 or wlatin1).

Here's the appserver key info, from the IOM Remote doc https://sassoftware.github.io/saspy/install.html#remote:

```
appserver -
If you have more than one AppServer defined on OMR,
then you must pass the name of the physical workspace server that you want to connect to,
i.e.: ‘SASApp - Workspace Server’.
Without this the Object spawner will only try the first one
in the list of app servers it supports.

For instance:
# connect to utf8 SAS
iomutf8  = {'java'      : '/usr/bin/java',
            'iomhost'   : 'objspawner.iom.host',
            'iomport'   : 8591,
            'encoding'  : 'utf8',
            'classpath' : cp,
            'appserver' : 'SASApp UTF-8 - Workspace Server'
           }
# connect to Wlatin1 SAS
iomutf8  = {'java'      : '/usr/bin/java',
            'iomhost'   : 'objspawner.iom.host',
            'iomport'   : 8591,
            'encoding'  : 'windows-1252',
            'classpath' : cp,
            'appserver' : 'SASApp Wlatin1 - Workspace Server'
           }

```

**Comment by garra2** [comment]
many thanks!
