### ISSUE TITLE
with latest update, getting weird encoding message

### ISSUE THREAD

**Issue by sascis** [sassoftware/saspy#220]
SAS Connection established. Subprocess id is 3149

The encoding value provided doesn't match the SAS session encoding.
SAS encoding is utf-8. Specified encoding is utf-8.
Using encoding utf_8 instead to avoid transcoding problems.
You can override this change, if you think you must, by changing the encoding attribute of the SASsession object, as follows.
If you had 'sas = saspy.SASsession(), then submit: "sas._io.sascfg.encoding='override_encoding'" to change it

**Comment by tomweber-sas** [comment]
Ah, that's a type on my part. that should have an underscore instead of a dash; utf_8 not utf-8. I'll fix that at master. The reason this changed is that saspy needs to know the Python encoding value that matches the SAS sessions encoding. The 'encoding' : key in the configuration definition is how the user has had to tell me what the correct encoding is. However, that isn't always specified correctly and can then cause various problems.
With this new version, I've added a mapping table so I can see what the SAS session encoding is, and automatically set the corresponding python encoding myself. You don't need to specify 'encoding' anymore.
In this case, you already aren't specifying it, and I'm defaulting it to utf-8, but I put the sas name 'utf-8' instead of the python name 'utf_8' in there when I default it and then it's getting caught by my validation code because of that typo.
If you add 'encoding' : 'utf_8' to your config definition, this should go away. I'll push the fix to master today when I get a chance.
Thanks!
Tom

**Comment by tomweber-sas** [comment]
I've fixed this at master, if you want to pull that and verify the fox.

thanks,
Tom

**Comment by tomweber-sas** [comment]
This is now in the 2.4.4 release which is the latest Pypi version also. Can you confirm the fix on your end?

thanks,
Tom
