### ISSUE TITLE
NameError exceptions due to pandas not being installed as an explicit dependency

### ISSUE THREAD

**Issue by ilankham** [sassoftware/saspy#227]
The module pandas is used throughout this project but is not currently installed as a SASPy dependency, leading to unexpected `NameError` exceptions.

To reproduce this, setup a virtual environment with only SASPy installed, and try this example:

```Python
from saspy import SASsession
sas = SASsession()
fish_df = sas.sasdata2dataframe(table='fish', libref='sashelp')
```

This currently results in the following:

```
Traceback (most recent call last):
  File "[file path]", line 4, in <module>
    fish_df = sas.sasdata2dataframe(table='fish', libref='sashelp')
  File "[venv path]\lib\site-packages\saspy\sasbase.py", line 985, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "[venv path]\lib\site-packages\saspy\sasioiom.py", line 1649, in sasdata2dataframe
    tdf = pd.DataFrame.from_records(r, columns=varlist)
NameError: name 'pd' is not defined
```

PR #225 resolves this by updating setup.py to include pandas (and its dependency numpy). An alternative is as follows: 

1. Refactor the entire code base, e.g., by consistently wrap `import pandas as pd` in `try-except` statements.

2. Update project documentation to explain by pandas is not an explicit dependency and to list all features requiring a separate pandas installation.

**Comment by tomweber-sas** [comment]
I've taken a first pass at this and pushed it to a branch named nopandas. Also, I pushed a notebook showing this to the saspy-examples repo under IssuesExamples:
https://github.com/sassoftware/saspy-examples/blob/master/Issue_examples/Issue227.ipynb

See what you think and let me know. results that aren't pandas work fine but panda requests get the ImportError for pandas
```
ImportError: No module named 'pandas'
```

Thanks!
Tom

**Comment by ilankham** [comment]
The code

```Python
from saspy import SASsession
sas = SASsession()
fish_df = sas.sasdata2dataframe(table='fish', libref='sashelp')
```

now produces the following with Python 3.7.3:

```
Traceback (most recent call last):
  File "[file path]", line 3, in <module>
    fish_df = sas.sasdata2dataframe(table='fish', libref='sashelp')
  File "[venv path]\lib\site-packages\saspy\sasbase.py", line 975, in sasdata2dataframe
    import pandas
ModuleNotFoundError: No module named 'pandas'
```

Even when the pandas-detection logic on line 975 of sasbase.py is adjusted to be

```Python
        if self.sascfg.pandas:
           import pandas
```

the example produces the following:

```
Traceback (most recent call last):
  File "[file path]", line 3, in <module>
    fish_df = sas.sasdata2dataframe(table='fish', libref='sashelp')
  File "[venv path]\lib\site-packages\saspy\sasbase.py", line 986, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "[venv path]\venv\lib\site-packages\saspy\sasioiom.py", line 1660, in sasdata2dataframe
    tdf = pd.DataFrame.from_records(r, columns=varlist)
NameError: name 'pd' is not defined
```

If the goal is to keep SASPy independent from pandas, have you considered factoring pandas-dependent portions into a module that could be imported separately?

If this isn't feasible, printing warning messages to stdout or stderr might be preferable to Tracebacks.

**Comment by tomweber-sas** [comment]
So, are you saying that in python 3.7 they changed the exception from ImportError to ModuleNotFound error?
That's why I don't care for explicit exception names in except block, for one line of code, cuz they change the names, but it's still the same error either way.

I'm unclear on the next thing where you changed the boolean conditition of my check. You  don't have pandas, so when you disabled my check, you got the error from it not being there, that you were getting before which you didn't like because it was misleading. That's because you disabled my change which was giving you the correct error about pandas not being there. Or am I missing something there? Could be.

As for messages to the log instead of exceptions, that's an infinite debate there, I'm sure. I already have PRs for changing messages TO exceptions because that's the 'right way' to do it. 

Did you try the example notebook? Do you get the same results? Is it just that 3.7 changed the exception to different wording (that I have no control over). Can you run the notebook with your version and we see what it gets? You can export it as html and attach it (add.txt extension else it won't attach - can then download it and remove .txt and view it).

Thanks,
Tom

**Comment by hhubbell** [comment]
Chiming in as I saw a reference to some exception code I've been working on.

[`ModuleNotFoundError`](https://docs.python.org/3/library/exceptions.html#ModuleNotFoundError) is a subclass of `ImportError`, so catching the wrong error is not the issue.  Try the following:
```python
>>> try:
        raise ModuleNotFoundError
    except ModuleNotFoundError:
        print('Caught the error`)
Caught the error

>>> try:
        raise ModuleNotFoundError
    except ImportError:
        print('Also caught the error')
Also caught the error
```

What you've done in your branch is moved the error source from pandas usage to pandas import.  Previously, `import pandas` errors were silently passed, which meant that the first time a user notices there's an issue is when they get the `NameError: name 'pd' is not defined` traceback.  This happens because you `import pandas as pd`, but have no fallback for when the import fails, so `pd` isn't defined.
```python
try:
   import pandas as pd
except ImportError:
   pass    # `pd` never gets set if pandas isn't installed, resulting in NameError later
```

In your new branch, you explicitly `import pandas` in the `sasdata2dataframe` method without a try-catch block, so users without pandas installed get the `ModuleNotFoundError` traceback.
```python
# No issue here yet...
try:
    import pandas
    self.pandas  = True
except ImportError:
    self.pandas  = False

...

# Then, later...
if not self.sascfg.pandas:
    import pandas    # Source of ModuleNotFoundError
```

What's worse for users? A `NameError` or `ModuleNotFoundError`?  Either way, something has to happen because pandas is required to get a DataFrame.

My two cents on the issue is that you should leave the the try-catch block at the top when you import pandas, and then check that the module loaded in `sasdata2dataframe`, at which point you can emit whatever you want (`stdout`, `stderr`, `exception`).
```python
def sasdata2dataframe(...):
    if 'pandas' not in sys.modules:
        print('Pandas module not found. Pandas is required to load data into a DataFrame')
        # Or,
        raise ModuleNotFoundError('Pandas module not found. Pandas is required to load data into a DataFrame')
        # Or,
        warnings.warn('Pandas module not found. Pandas is required to load data into a DataFrame')
```

It's my opinion that you should import modules at the top unless there is a specific circumstance that calls for an import in the function body.  Checking `sys.modules` for pandas in `sasdata2dataframe` seems like a reasonable compromise that keeps your codebase clean, adds no dependencies, and provides the flexibility to tell the user there's an issue in whatever way you think is reasonable.

**Comment by tomweber-sas** [comment]
Hey Harry, thanks for jumping in. More input is a good thing. Let me get back to the beginning though. Much of what you state above is the point, though it's stated as thought is part of the problem (that's how I read it).

The problem:
user doesn't have pandas installed.
they try something in saspy that uses pandas (you don't **have** to do anything with pandas in saspy)
they get an error about 'pd' not being defined.

That was the issue. who knows what 'pd is. The error wasn't you don't have pandas. The suggestion is to make installing saspy dependent on pandas. My answer, No, fix the error so it's not confusing.

saspy doesn't require pandas, and some people don't want to have to install it just to run saspy..
I said that if you don't have pandas and try to use it in python (no saspy in sight), you get the same error, of course, cuz you don't have it. But, you don't get the same error, saspy had 'pd' not defined, but if you import pandas then you get (some) import error. 

So that's exactly the point of this change. If you don't have pandas, then if you try to do something in saspy that uses pandas, you now get the Import error (or whatever subclass error happens to come up for whatever version of python you have). Exactly what is shown in the example notebook, and what I believe will be shown running the notebook in 3.7 as well. If you don't have pandas now, and try to use it in saspy, you get the **same** error as if you try to use it outside of saspy and don't have it. 

The issue is a confusing error when you try to use modules you don't have installed. So now, you get the error you should get when you try to use modules you don't have installed. 

That make sense? And, I'm just doing the' import pandas' in those checks **to throw** the error instead of explicitly throwing the error myself. Seems like that's a good thing since the error is different in different versions of python, so I don't have to know which subclass error I should throw, I let python itself throw it, as I don't care.

Make sense? Oh, and removing it from the top of a couple of those modules was because it's never even used in those, so it wasn't needed in the first place there.

Thanks,
Tom

**Comment by ilankham** [comment]
To clarify, here's the scenario I'm testing:

1. Create a virtual environment and install SASPy.
2. Create a requirements.txt file listing only `saspy`.
3. Develop a Python application (not a Notebook) using SASsession.sasdata2dataframe (e.g., something like the 3-line example above).

Because I'm not working in a REPL (or REPL-like environment), this application cannot currently be deployed and trusted to run reliably. Installing pandas is not a "value add" for SASPy outside of a REPL; it's a necessity to keep applications from crashing. SASPy is intentionally causing Exceptions to be raised related to packages that its own code base relies on, but which SASPy doesn't automatically install. To fix this, I would need to manually determine the transitive closure of SASPy dependencies. And I would need to manually add them to my requirements.txt file before deployment. This creates maintenance and security issues. It also creates a transparency issue since, by any reasonable definition, pandas is currently an actual (even if not desired) dependency for SASPy to be used the way Python developers expect PyPI packages to operate for application development.

Regarding code style, I agree with @hhubbell. The SASPy code base will only be easier to read and maintain if all imports are listed at the tops of files. If you choose to stick with raising Exceptions, an alternative approach would be something like `raise ImportError('The pandas module needs to be imported before this method can be used.')`, rather than use an import statement mid-file.

**Comment by tomweber-sas** [comment]
@ilankham thanks for clarifying you use case!

Regarding what the error says or how it's presented, it doesn't really matter to me. It's an error and it just need to let the user know what the problem is. So it need to say 'pandas', not 'pd' so you know you don't have pandas. Issuing the Import to raise the exception, or issuing raise manually to raise the exception is 6 in one half dozen in the other. I'll change it to raise, and it'll do the exact same.

Regarding the argument that it's saspy's fault that you don't have pandas in the python deployment you are using to explicitly create, manipulate and interact with pandas data frames, I just don't buy it. Please be sure, I'm not trying to be argumentative here; this is a good discussion, and I welcome it :).  

There are hundreds of things saspy can do right out of the box and only 1 of them requires pandas to be available; sd2df(). You might argue that df2sd() is another. But, you can't even try to call that without the required data frame parameter until after you already got an error from whichever of the other dozens of methods you would have used to create a data frame which would have failed with, guess what, an exception caused by the fact you don't have pandas. I can do every single thing in saspy other than sd2df and df2sd, which is a lot, without having pandas.

I think I'd buy arguing that python should have pandas as a dependency more than saspy. But, the same argument would stand, you can do tons of work in python without using pandas, but once you want to do one thing with pandas, you needed to have installed it so it's there. 

Given your description of your scenario. where you are explicitly writing python code to interact with pandas data frames in your python program and it's a known thing that your python environment doesn't already have pandas installed, I think you need to add pandas to your requirements.txt file. 

What happens when you issue anything at all that has something to do with pandas, before you issue sd2df() in any python program in this environment? It will fail with some exception because you don't have pandas. In that case, is it python's problem for throwing the exception because it should have installed pandas for you? 

saspy isn't dependent on pandas. trying to use data frames in python is dependent on pandas. The dataframe sd2df returns you has nothing to do with saspy at all; it's a stand alone data frame in python, period. There's no association to saspy in it.

I'm afraid I still see no reason to force pandas and all of it's dependencies upon every saspy install.
If people are using pandas, they had to have installed it. If they don't use dataframes they can still use saspy to do everything it does.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I've changes the code to throw the exception via raise instead of implicitly by doing the import when pandas isn't there. I capture the exception from the original exception to use as the type and message for the raise, so at least it'll be as consistent as issuing the import to throw the exception, since it will still be that same exception.

**Comment by hhubbell** [comment]
Hi Tom,

One other thing you can consider that supports the use case @ilankham brings up is to add an `extras_require` argument to `setup.py` ([Documentation](https://setuptools.readthedocs.io/en/latest/setuptools.html#declaring-extras-optional-features-with-their-own-dependencies)).  This allows user libraries that depend on saspy to declare in their setup script that pandas should also be installed if needed.

You can do something like the following:
```python
setup(name='saspy',
    extras_require={
        'sd2df': ['pandas'] # Or whatever you want to call the dependency identifier, maybe `with_pandas`?
    },
    ...
)
```

Then, users like @ilankham can specify the following in their setup.py if they want to support operations that return a DataFrame.
```python
setup(name='my_module',
    install_requires=['saspy[sd2df]'],
    ...
)
```

This also allows users to install saspy with pandas if they choose.
```bash
pip install saspy[sd2df]
```

I realize this seems unnecessary for just one simple dependency, but you can imagine that there may be a number of projects that want to use saspy in the future to take advantage of the `sasdata2dataframe` functionality but do not themselves need to depend on pandas directly.

**Comment by tomweber-sas** [comment]
Hey Harry, thanks. Reading on the extras_require, I now see that you were using that to address my same concern with the pypiwin32 that your com access method would require, while saspy itself will not have that as a requirement. Yes that seems to address this optional feature requirement problem. I have another access method I haven't published yet which seem like it will end up needing another non-standard library module, and I won't make that be a requirement for all of saspy, but it would be a runtime requirement if you wanted to use that access method. So I think this is a good solution to that problem.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Finally have a chance to circle back to this. The changes to consistently handle not having pandas installed by throwing the import error if trying to use sd2df, and changing the default results back to html (the original default) instead of pandas, have all been pushed and are available in the current release.

With Harry's suggestion about adding pandas to the extras_require in the setup, like this:
extras_require={ 'pandas': ['pandas'] }

Then it could do the pandas install at saspy install time by submitting the following:
pip install saspy[pandas]

though you can do that be submitting:
pip install saspy, pandas

but at least this will make it more of a documented install thing, like the pypiwin32 optional requirement for the COM access method that's now production too:
extras_require = {'iomcom': ['pypiwin32']},
 
So do you think I should add pandas as follows:
extras_require = {'iomcom': ['pypiwin32'], 'pandas':['pandas']},


Thoughts?
Tom

**Comment by tomweber-sas** [comment]
Cleaning up old issues. I'm closing this, as all the work was done and pushed some time ago. If there's anything else, just let me know!

Thanks!
Tom
