### ISSUE TITLE
Feature Request: Allow users to store `sascfg_personal.py` in their home directory

### ISSUE THREAD

**Issue by hhubbell** [sassoftware/saspy#237]
**Is your feature request related to a problem? Please describe.**
Many software packages store configuration files in the user's home directory for easy access. This enables users to modify configurations without searching their system for the library's install path. In addition, this workflow allows users of shared systems to make modifications to a config without disrupting other users.

Currently, the `sascfg_personal` configuration can be difficult to use. You must either:
1. Add a file to the `saspy` library on your system. A minor pain for some users, but potentially a showstopper for others.
2. Add a config file location to your `$PYTHONPATH`.
3. Reference a config each time you start a `SASsession()`.
4. Keep a copy of your config in each project directory that uses `saspy`. 

**Describe the solution you'd like**
My proposal is to modify the configuration hierarchy to include `$HOME/.config/saspy`.

This change would allow users to store configuration files related to `saspy` in an easy to access, local, and idiomatic location.  I propose `$HOME/.config` as it seems to the new preferred way to store dotfiles, instead of littering the user's home folder with them.

The new search hierarchy would be the following:
1. If a `cfgfile` param is passed to `SASsession()`, use this file or raise a `SASConfigNotFoundError`.
2. Otherwise, follow the below steps:
    * Search for `sascfg_personal` in the local scope. i.e, a project specific configuration that differs from some more general one. This is the equivalent of python searching `sys.path[0]`, or the default search order behavior.
    * Search for `sascfg_personal` in `$HOME/.config/saspy`.
    * Search for `sascfg_personal` anywhere else in `sys.path`.
    * Search for a `saspy.sascfg_personal` file in the library folder. This would be more of a globally administered config, for instance if a multi-user system required specific configuration parameters (perhaps a server URI or whatever) where users would then need to require a user/pw upon session init.
    * Finally, fall back to `sapsy.sascfg` if no other config is found.

As an aside, storing a config in `$HOME` would allow users to set their SAS passwords in a saf**er** way, similar to how PostgreSQL works with the [`.pgpass`](https://www.postgresql.org/docs/9.1/libpq-pgpass.html) file. It's standard practice to `chmod 600` this file.

**Additional context**
I have a pull request for this feature.

**Comment by tomweber-sas** [comment]
Ah, sorry, I posted my comments to the PR. But, there was another thought I had regarding a comment above. Although you can put id's/password's in the file and set it to 600, there still a difference between that and the existing .authinfo file (also 600 under your home directory). The contents from authinfo aren't accessible in the python process. But, the dictionaries/lists/... in the config file are accessible in the python process:
```
sas.sascfg.SAScfg.*

sas.sascfg.SAScfg.pune
{'classpath': '/u/sastpw/tkpy2j/lib2/sas.svc.connection.jar:/u/sastpw/tkpy2j/lib2/log4j.jar:/u/sastpw/tkpy2j/lib2/sas.security.sspi.jar:/u/sastpw/tkpy2j/lib2/sas.core.jar:/opt/tom/github/saspy/saspy/java/saspyiom.jar',
 'encoding': 'cp1252',
 'iomhost': 'some.machine.this.that',
 'iomport': 8591,
 'java': '/usr/bin/java',
 'omrpw': 'myPWhere',
 'omruser': 'myIDhere',
 'timeout': 0}
```
So, in the case of Jupyter, if you share a notebook with someone, they can interrogate these values easily in python. So, just need to be aware of that. 

The PR looks good though.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey Harry, so I've been playing around with this config stuff a bunch the past couple days. I'm switching back to here instead of the PR for discussion, so it'll be in the issues, My last comment in the PR was that I basically had your code (logic) that I tweaked some and it was behaving. But, I still had the possibility of 3 possible config file per session, if things changed (the right way) on the file system. I'd like it to be more deterministic and not change if something changes on the filesystem w/in a session (python session). I have to track down problem when users hit them and this kind of variance can be troublesome. So, I've come up with something I think will work. I think it's almost just what you want :)

Here's what I have coded up on my system currently:

1) Bad news first. I still have sascfg_personal from the saspy module location first. This is the current behavior, for past 2 years, and, that file never exists there unless you explicitly create it and put it there. Consider it a global default. For how you want this to behave, just don't put that file there and everything works as you want. But, no one who already is running will be affected.

2) aside from the above, the search path is then current dir, home/.config/saspy. rest of sys.path.
This is the search you would like where it's all on the file system somewhere in sys.path, with the home/.config added after cur dir.

3) for both cases above, there will only be the one file imported and used for the life of the python session, even if things change on the filesystem. Whatever file gets imported the first time is it for every time, regardless of changes on the filesystem.

4) cfgfile=   The current behavior is a bit off in that you will only get the first cfgfile= to be used. It can be different than the default ( that would be used in 1 and 2 above), but subsequent cfgfille= won't use the file specified, but rather the file from the very first cfgfile=.  Again, the original idea was there is only 1 file with as many different configurations that you need, not multiple files w/ different configurations. So, what I have now is each cfgfile= actually uses the file specified, and it's (still) independent of 1 and 2 above.

So, You get one default config file for the life of the session, but you can explicitly use different files via cfgfile=. There's no breaking change (except different cfgfile= will work - I consider that a bug). And you have the search order you want by just not creating a config file in the module space (where there doesn't exist one in the first place). Oh, and if no file is still found with all of this, I still look for sascfg.py as a catch all; existing behavior again.

I believe this addresses my concerns and your behavior expectations. I assume you would expect different cfgfile= to actually use the files each one specifies. 

So, what do you think?

I can push these changes out to my 'config' branch. But I'll hold off on that in case you want to compare the existing difference between your branch and that branch (that I mentioned in the PR in my last post). It's only a little bit different. Well, actually, you can just look at the difference between my code and this commit to see those minor changes. Yeah, I'll push it and then you can try it out and see if you think it behaves as you would want. 

Also, this eliminates the need to tell anyone that we picked a different file than how it used to behave. The list_configs() method is still in there and the file that was used is still listed in the SASsession __repr__ output; so you know which one was actually used. Also, once you import saspy, submitting `saspy.SAScfg` will show the file that will be used as the default (no cfgfile=) - that is at the time you imported saspy (if you go change files around before actually starting a SASsession, you could change that, but you can do that now too). 

Thanks!
Tom

**Comment by hhubbell** [comment]
Hi Tom,

I think that approach is great.  Your branch looks good to me!

Thanks

**Comment by tomweber-sas** [comment]
Cool. Do you want to update your branch with the changes and we can see about merging in the PR? I'll also update the doc with more detail about this too, once we merge it and before building a release. 
Tom

**Comment by tomweber-sas** [comment]
Hey Harry, I finally have a chance to get back on this. I assume you've been busy too. How about I merge in your existing PR and then I'll just make the corresponding tweaks from my branch on top of those? That way you don't have to do that work on your side. We'll end up w/ the same thing, and then I can add some more detailed Doc for this and roll it all up into a fresh release. 

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Ok, this is now V3.1.6 which is the current version!

Thanks again for your support and contributions Harry! Sorry this one took so long.
Tom
