### ISSUE TITLE
saspy connect to sas viya using httpsviya

### ISSUE THREAD

**Issue by veerendra-pappoppula** [sassoftware/saspy#247]
I am trying to connect to sasviya. I am able to enter my credentials but the session creation fails at

File "C:\Python\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

is there any documentation on how to connect and how to use saspy when connecting to sas viya?

I am trying to read metadata information from viya server. Like dashboard names, dashboard url, what datasets are being used, when were the datasets last updated. Is there a way to do that?

**Comment by tomweber-sas** [comment]
Hey, sorry, I was out yesterday. Can you show me the configuration definition you're using? And the full traceback too?
When you say Viya, (which is kinda a general term), are you trying to connect to CAS? What host and port is it you're using;? What server are you connecting to. This access method for saspy connects to the Compute Service, which lauches a Compute Server (like a Workspace server in regular SAS). So it still is connecting to MVA SAS (same as SAS 9.4) that is installed in a Viya deployment. 
Let's make sure that's what you're trying to connect to. Or if that's not what you're trying to connect to, maybe it's a different package, like python-swat which connects to CAS. Or if it's some other micro service, then also, maybe something else.

The only doc for this access method is in the configuration section, since after that, it's the same objects and methods as for any other connection method; it's still MVA SAS.

Thanks!
Tom

**Comment by veerendra-pappoppula** [comment]
The purpose of trying to connect to SAS VIYA is to read metadata information from viya CAS server. Like dashboard names, dashboard url, what datasets are being used, when were the datasets last updated. Is there a way to do that? From what I have learned, I believe this information is stored in PostgreSQL to which I don't have access to, and there are no shell scripts that I can run to get the information I need. I might not have all the information, but contacting technical support didn't help.

Here is what I have in the cfg file:

httpsviya = {'ip'      : 'sasvad01.wcupa.edu',
             'context' : 'Data Mining compute context',
             'authkey' : '',
             'options' : ["fullstimer", "memsize=1G"]

SAS_config_names=['winiomlinux', 'httpsviya', 'httpviya']

Here is the traceback:

Traceback (most recent call last):
  File "<pyshell#1>", line 1, in <module>
    saspy.SASsession(cfgname='httpsviya')
  File "C:\Python\lib\site-packages\saspy\sasbase.py", line 346, in __init__
    self._io = SASsessionHTTP(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "C:\Python\lib\site-packages\saspy\sasiohttp.py", line 379, in __init__
    self.sascfg     = SASconfigHTTP(self, **kwargs)
  File "C:\Python\lib\site-packages\saspy\sasiohttp.py", line 211, in __init__
    self._token = self._authenticate(user, pw)
  File "C:\Python\lib\site-packages\saspy\sasiohttp.py", line 288, in _authenticate
    conn = self.HTTPConn; conn.connect()
  File "C:\Python\lib\http\client.py", line 1384, in connect
    super().connect()
  File "C:\Python\lib\http\client.py", line 928, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "C:\Python\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Python\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

Please let me know.

Thank you,
Ravi

**Comment by tomweber-sas** [comment]
Ok, thanks, that does make it more clear. It does sound like this isn't the kind of connection you're looking for. If you could connect saspy via the HTTP access method, you would be connect to a SAS server, not CAS. If there is a PROC that allows you to get at the info you want, then that could make sense. I don't know that you can get at this info from MVA though (I don't know either way). If running a PROC in MVA to connect to CAS and get this isn't what you were trying to do, then this isn't the correct path.

I don't use CAS personally. so I don't have the answer at hand for you. I did google some of what you are looking to do and found a couple links that are for monitoring CAS via SAS Environment Manager:
https://go.documentation.sas.com/api/docsets/evfun/3.4/content/evfun.pdf
https://go.documentation.sas.com/api/docsets/calmonitoring/3.4/content/calmonitoring.pdf

These both talk about a dashboard and monitoring what's going on in the CAS server.
Could these be what you're looking to use?  In the second link there's mention of connecting to CAS over http to monitor it; this sounds a  lot like what you're looking for.
```
To log on to CAS Server Monitor, open a web browser and enter the following URL in the address field:
https://http-proxy-machine-name/cas-tenant-name-deployment-instance-name-http
```
Let me know if any of this is what you're looking for, or at least closer to it.

Thanks,
Tom

**Comment by veerendra-pappoppula** [comment]
I am trying to get the metadata information without having to login using a webpage manually. I can get the information I want, manually, but it is a one by one process and not a batch process. 

I will take more time to go through the links, but I am not sure if they have anything. Thank you for your suggestions.

Ravi

**Comment by tomweber-sas** [comment]
Ok, so that it the right information, but you're looking for a programmatic way to access it instead of clicking on a web page? I'll check with some folks here to see if I can find out if you can do that. Make perfect sense, so I would hope there is!

**Comment by tomweber-sas** [comment]
I've emailed a couple guys that may know. I also searched some more and found these. Are either of these links 'it'?
https://developer.sas.com/guides/rest.html
https://developer.sas.com/apis/cas/rest/current/apidoc.html

Thanks,
Tom

**Comment by veerendra-pappoppula** [comment]
I think there is some good information in there. I did not come across
before. I am going to go through and try a few things and reply here if I
find something.

Thank you very much for your guidance.

**Comment by tomweber-sas** [comment]
Great. I'm here to help. One of the folks I asked also pointed at the second link: https://developer.sas.com/apis/cas/rest/current/apidoc.html

That seems to be the API interface to at least get some monitoring info. I also head back with another thing to use to get table information; part of what you were looking for. There's a tableinfo CAS Action which you can run to get some of the table info. Running actions seems to be something you can do with that API, and the python-swat module is also the python module that connects to CAS and you can use to run actions. So maybe there's more that one way to get at all of the various things you want. But, hopefully all of this is available via programmatic API!

Thanks,
Tom

**Comment by veerendra-pappoppula** [comment]
I dont think the rest API's are for me. But I am taking a look at swat
module. And I tried this, after installing the swat module:

conn = swat.CAS('sasvad01.wcuds.net', 5570, '75vpappoppul', 'pwd')


ERROR: The TCP/IP tcpSockConnect support routine failed with error 10060
(The connection has timed out.).
ERROR: Failed to connect to host 'sasvad01.wcuds.net', port 5570.
Traceback (most recent call last):
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 303, in
__init__
    self._sw_connection = clib.SW_CASConnection(*params)
  File "C:\Python\lib\site-packages\swat\clib.py", line 94, in
SW_CASConnection
    return _pyswat.SW_CASConnection(*args, **kwargs)
SystemError: <class 'py37swat.SW_CASConnection'> returned NULL without
setting an error

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<pyshell#4>", line 1, in <module>
    conn = swat.CAS('sasvad01.wcuds.net', 5570, '75vpappoppul', 'Zxcv1234')
  File "C:\Python\lib\site-packages\swat\cas\connection.py", line 310, in
__init__
    raise SWATError(self._sw_error.getLastErrorMessage())
swat.exceptions.SWATError: Could not connect to 'sasvad01.wcuds.net' on
port 5570.

Am I doing something wrong? The CAS server is a remote linux machine.

Thank you,
Ravi

**Comment by tomweber-sas** [comment]
Well, are you sure those are the correct host/port for connecting to CAS? I'm afraid I don't use CAS, nor swat to CAS either, so I'm not completely sure what the problem might be. But the error shows that it timed out trying to connect, so the host/port are what I would look at first. And, I hate to bounce you around, but I don't know enough about swat, so what I would do after verifying the host/port is open an issue w/ swat, so that the right support person can help you get seat working:https://github.com/sassoftware/python-swat/issues

Even searching issues on that site might provide some info if others had this same problem.
Well, looking at the doc for swat, I see that maybe you are supposed to use this key in the connection:, protocol='http'

From the doc at https://sassoftware.github.io/python-swat/binary-vs-rest.html#rest-protocol
'''
To specify the REST protocol explicitly, you can use the protocol='http' option on the connection constructor.

In [2]: conn = swat.CAS(cashost, casport, protocol='http')
'''

Maybe give that a try. It could be you were going through the binary protocol. and that's the wrong port for that path, assuming it's the right port for the HTTP{ case (wouldn't be the same port)?

Tom

**Comment by veerendra-pappoppula** [comment]
I apologize. I will ask in the respective forum. Thank you for your time.

**Comment by tomweber-sas** [comment]
No problem, I'm happy to help regardless, but I don't want to waste you time when I don't know enough to be helpful. Getting you the right other person is the best in those cases.

Thanks,
Tom
