### ISSUE TITLE
SAS session fails to initialize in Jupyter when notebook dir is set to a remote location

### ISSUE THREAD

**Issue by robbielj** [sassoftware/saspy#250]
**Describe the bug**
I use IOM over java method to connect to local sas installation.
When jupyter notebook default notebook dir (c.notebookapp.notebook_dir in config) is set to a network drive folder, saspy session fails to initialize, reporting sspiauth.dll not found in system path. 

When this is set to a folder on local machine or submitting python code via system command line, there is no issue.

Now I can solve it by linking the network dir to local machine.
Wonder whether it is a bug.

**Comment by tomweber-sas** [comment]
Hmm, that's curious. My first thought is that maybe you are picking up a different sascfg[_personal].py file in each case. We can check that by submitting the following for each situation
```
import saspy
saspy.sasbase.SAScfg
```

Can you do that and see if it's a different config file? That's easy to address if so.

Thanks!
Tom

**Comment by robbielj** [comment]
Yes. They are the same config file on local drive. The following is the verbose error.

> using sas config named: autogen_winlocal
> we failed in getConnection
> the application could not log on to the server. The server process terminated unexpectedly with exit value 2.
> sas process has terminated unexpectedly. RC from wait was: 4294967290
> SAS connection failed. No connection established. Double check your settings in sascfg_personal.py file.

> attempt to run program “......”
> be sure the path to sspiauth.dll is in your system path.

**Comment by robbielj** [comment]
Yes. They are the same config file on local drive. The following is the verbose error.

```
using sas config named: autogen_winlocal
we failed in getConnection
the application could not log on to the server. The server process terminated unexpectedly with exit value 2.
sas process has terminated unexpectedly. RC from wait was: 4294967290
SAS connection failed. No connection established. Double check your settings in sascfg_personal.py file.

attempt to run program “......”
be sure the path to sspiauth.dll is in your system path.

```

**Comment by robbielj** [comment]
Yes. They are the same config file on local drive. The following is the verbose error.


```
using sas config named:autogen_winlocal
we failed in getConnection
the application could not log on to the server. The server process terminated unexpectedly with exit value 2.
sas process has terminated unexpectedly. RC from wait was: 4294967290
SAS connection failed. No connection established. Double check your settings in sascfg_personal.py file.
attempt to run program “......”
be sure the path to sspiauth.dll is in your system path.
```

**Comment by tomweber-sas** [comment]
Ok, can I see the config file? and where was it located? The specific error is
```
the application could not log on to the server. The server process terminated unexpectedly with exit value 2.
```
Basically, SAS isn't starting up. It's being started but failing for some reason. The return code 2 isn't documented as a specific cause. But, given this only happens when you're current directory is that network drive, and it's trying to execute the command in your registry, it's going to be some kind of disconnect between paths or permissions or something like that. 

Can you show what the command in your registry is? See number 5 in this link: https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors

The other thought is based upon what you mentioned about it working when you link the path to your local machine? If where the client (saspy/the Java subprocess) isn't actually localhost (127.0.0.1 of where SAS is) when it tries to start that SAS process, that would cause it to fail also. So, is the python process (the notebook), actually running on a different host in this scenario? That would certainly cause a failure like this. Can you explain more about this network location and 'linking' it to your machine or not?

Thanks,
Tom

**Comment by robbielj** [comment]
# 
The config file is like this:
```
Sas_config_names=[“autogen_winlocal”]

Sas_config_options={
	“lock_down”: False,
	“verbose”: True
}

cpW = “D:\\.....\\sas.svc.connection.jar”
cpW += “D:\\....\\sas.security.sspi.jar”
cpW += “D:\\....\\log4j.jar”
cpW += “D:\\....\\sas.core.jar”
cpW += “C:\\Users\\...\\saspy-3.1.0-py3.6.egg\\sas\\java\\saspyiom.jar”

autogen_winlocal={
	“java” : “c:\\....\\java”,
	“encoding”: “gb2312”,
	“classpath”: cpW
}
import os
os.enviro[‘PATH’]+=“;d:\\....\\sasext
```

All paths in the config file are valid. No file is missing. 
The command in the registry looks correct to me. It is like
```
d:\progra~2\sashome\......
```

Java, SAS and python are all local. I am working inside an isolated network. Local machine attaches a lot of network storage drives. The linking is a hard link like “ln” on Linux. I linked the folder on network drive to local.

**Comment by tomweber-sas** [comment]
Hey, any chance of getting on a Web-Ex, I can set up so we can investigate this on your machine? If not, that's ok and we can still try to track it down. Not sure I can reproduce it here to diagnose it. I still think it is an IOM start up error, not a saspy or java error. Your config looks fine, all fully qualified paths. I still think it's something like the IOM client not thinking you're SAS is localhost when running from the network drive,like it does when you make it local, but I can't really verify that.

Let me know if that will work,
Tom

**Comment by tomweber-sas** [comment]
Were you able to gather any more info on this? It seems that it's IOM failing to start, which I have to believe is because it doesn't see it being the same local host when you have the drive on the network as opposed to connected locally; based upon the error its getting. But I don't have enough info to prove that either way.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Just cleaning up old issues. If you'd like to pursue this further, just reopen it and let me know. I have to believe this is just IOM behavior when it doesn't think it's on localhost.

Thanks!
Tom
