### ISSUE TITLE
Ability to use SAS macro variable in markdown

### ISSUE THREAD

**Issue by jack-hamilton-kpdor** [sassoftware/saspy#257]
In a Jupyter Notebook (not Jupyter Lab), if a notebook with a Python kernel is trusted, and you have  enabled the Python Markdown extension, you can use the value of a Python variable in a markdown cell:

Python cell:
````Python
a = 2.4
````

Markdown cell:
````
a is {{a}}
````

Markdown cell display after run:
````
a is 2.4
````

I would like a similar capability with SAS macro variables in notebooks running the SAS kernel.  If I set a macro variable in my program, I could use it in my documentation.  For example, something like 

SAS cell:
````
proc sql;
    select * from sashelp.class;
quit;
````

Markdown cell:
````
As you can see from the previous output, there are {{SQLOBS}} observations 
in the data set SASHELP.CLASS.
````

Output:
````
As you can see from the previous output, there are 12 observations 
in the data set SASHELP.CLASS.
````

This would not be a simple task, as it would require a lab extension in addition to a SAS kernel change.  I noticed that such a feature has already been requested for Jupyter Lab, but hasn't been implemented as far as I can tell.

I see in the documentation that the sas.symget and sas.symput functions can be used to pass SAS macro values to and from Python,  but I don't see a the opposite, a way to set Python variables from SAS.  Is that correct?  We have SAS 9.4 M5.  It might be possible to write a function to do it in PROC FCMP with the new Python object in 9.4M6, but we don't have that yet, and it's not clear what the scoping rules are for variables set that way.

**Comment by tomweber-sas** [comment]
Hey Jack,

I believe I understand what you're looking for. I haven't tried that myself, but it seems straignt forward - for the python notebook case. With saspy, which is a python notebook, you can use the symput and symget to move values between python variables and SAS Macro variables, so I expect that you can use symget to assign a python variable the value from a SAS macro variable, and then be able to use that python variable in your markdown extension of your markdown cell.

Can you try that out and verify that? BTW, how do you 'enabled the Python Markdown extension'?
Sorry for it being a picture, but here's how you can set the python variable to use in your markdown from a SAS variable:

![Issue257](https://user-images.githubusercontent.com/17710182/64960891-4951c100-d862-11e9-8d96-68aece6552ca.png)


For the SAS_kernel, however, the notebook is not a python notebook. So there are no python variables. I don't know if the 'markdown extension' can even be enabled  in kernel notebooks other than python; do you know either way?. It would take some investigation to see if it could work in that environment, and then to see what would need to be done to support it, is it can.

Tom

**Comment by tomweber-sas** [comment]
Were you able to use symget() to get a SAS macro variable into your python variable and have that render in your markdown cell? And do you know if this can even be done from any kernel other than python?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey, I'm cleaning up old issues, but I dug in to this a bit, looking at the markdown extension. I found this doc: https://jupyter-contrib-nbextensions.readthedocs.io/en/latest/nbextensions/python-markdown/readme.html#internals
It states that what this extension does is execute whatever it is you coded in the {{ }}. So, for the SAS_kernel, it would just take whatever you put in there and submit it to SAS. The output it gets back is then what it renders. But, the output you would get back from submitting something in the SAS_kernel, is either the LST, an HTML document if there was output, or the LOG, which is text, but I believe the kernel turns it into HTML also, in order to color it. So, if this extension were to run in the SAS_kernel, it doesn't sound like you would really be able to get what you expect.

```
The extension overrides the textcell.MarkdownCell.prototype.render function
and searches for the expression enclosed in double curly braced {{ <expr> }}.
It then executes the expression and replaces it with the result returned from
the running kernel, embedded in a <span> tag.
```

So, if you were to code {{%put &mymacro;}} then you would (if it worked at all) get something back like this, I expect. 
```
38   ods listing close;ods html5 (id=saspy_internal) file=stdout options(bitmap_mode='inline') device=svg style=HTMLBlue; ods
38 ! graphics on / outputfmt=png;
NOTE: Writing HTML5(SASPY_INTERNAL) Body file: STDOUT
39   
40   %put &mymacro;
'Tom'
41   
42   ods html5 (id=saspy_internal) close;ods listing;

43   
```

I don't see that the SAS_kernel could even know this was being done, as it's not in the loop. Just the markdown extension driving an execute call of code, same as any other.

Closing this, but if you want to explore it further, just let me know. We could try some things where you're running to see what actually happens.

Thanks,
Tom
