### ISSUE TITLE
Load module error

### ISSUE THREAD

**Issue by isonimiguelBB** [sassoftware/saspy#260]
When I connect using SSH, I can't submit a libname statement for db2 returning the following error in the log:

>ERROR: Could not load /opt/sas94/SASFoundation/9.4/sasexe/sasdbu (67 images loaded)
>ERROR:  0509-022 Cannot load module /opt/sas94/SASFoundation/9.4/sasexe/sasdbu.
>        0509-150   Dependent module libdb2.a(shr_64.o)
>       could not be loaded.
>        0509-022 Cannot load module libdb2.a(shr_64.o).
>        0509-026 System error: A file or directory in the
>       path name does not exist.
>        0509-022 Cannot load module /opt/sas94/SASFoundation/9.4/sasexe/sasdbu.
>        0509-150   Dependent
>       module /opt/sas94/SASFoundation/9.4/sasexe/sasdbu could not be loaded.
>ERROR: The SAS/ACCESS Interface to DB2 cannot be loaded. The SASDBU   code appendage >could not be loaded.
>ERROR: Error in the LIBNAME statement.

Why is that happening? When I connect using SAS EG in a Windows PC it works perfectly.
 - CentOS 7.6
 - SAS Version: 9.4M3
 - SASPy Version: 3.1.6

**Comment by tomweber-sas** [comment]
Hey, I can't be 100% sure, but probably 99% 😎, that it's because when you connect from EG, you're connecting to a workspace server that is already configured with the DB2 client configuration and likely other preconfigured things too. 
When you connect using STDIO over SSH, you are directly starting your own SAS session that is not that workspace server, thus the DB2 client, nor any other configuration, are not already set up for you.

You should use the IOM access method to connect to that same workspace server that you connect to with EG, and you should then be able to access everything from saspy that you can in EG.

The config doc is here, and if you need any help with it just let me know, I'm happy to help.
https://sassoftware.github.io/saspy/install.html#iom-using-java
It would be the remote case as opposed to local, based on you using SSH.

Thanks,
Tom

**Comment by isonimiguelBB** [comment]
I'm connecting to the same server using both EG and SSH. Is that the problem?

The thing is I've already tried using IOM but, because I'm using a lot of data at the same time, the java processes consume all the memory on the server until it becomes unusuable. Increasing memory is not an option because I already have 32GB, the max I'm allowed to.

Thanks!

**Comment by tomweber-sas** [comment]
Hey, actually, no you aren't connecting to the same server. You would be starting a SAS session from the same installation on the same machine, but it isn't a workspace server, and it's not configured as that workspace server would be either. Well, when you say SSH I am assuming you're talking about using the STDIO over SSH access method as opposed to the IOM access method. Is that what you are doing? I don't see anything really showing it either way. IF that's the case, then no, it's not the same. If I'm misunderstanding that, then it's still to be seen.

So, what is it you're doing such that the java process is consuming all your memory? I haven't seen that before. That seems like something to address. Are you trying to pull lots of data over to your python process? Even that shouldn't use memory for java, but it would for python.

Do you have anything I can look at, or would you want to try a web-ex where I could see what's going on and try to figure out how to get you working as you would expect? I expect this is something I can solve if I have more to go on.

Thanks!
Tom

**Comment by isonimiguelBB** [comment]
That's correct. I'm using STDIO over SSH to the same machine I connect when using EG. 

Basically, I'm loading multiple tables using the multiprocessing python library, then converting each one to a pandas dataframe and then loading to MySQL using SQLAlchemy.

As lots of java processes are opened, they use all the memory. If I try to kill some of them after the execution, they become zombies. The python processes are ok.

Here's the code (every function from the priority file starts a list of tables and lib is the list of libname statements to be executed):

>import multiprocessing
>import os
>import priority
>
> def multi(f, lib):
>     if f == 0:
>         while True:
>             priority.priority0(lib)
>     elif f == 1:
>         while True:
>             priority.priority0(lib)
>     elif f == 2:
>         while True:
>             priority.priority2(lib)
>
>  if __name__ == "__main__":
>     processes = []
>     for f in range(0, 8):
>         p = multiprocessing.Process(target=multi, args=(f, lib))
>         processes.append(p)
>         p.start()
>     for process in processes:
>         process.join()

**Comment by tomweber-sas** [comment]
Oh, it's not my IOM java process, it's others on your client machine. Though, does not having that one java process (using STDIO instead of IOM) really make the difference? Or, with the error you're getting, you can't run the whole thing, so it might have the same problem as well, but you aren't getting there to see?

I do still expect that the error is because when you start you're own SAS session, it's not configured with the necessary DB2 client libraries, which are configured for you in the workspace server. I don't have anything showing that, but I fully expect that to be the case. If you know what paths you need, you could probably set that up for your SASsession, but I don't know what else you might be missing as you're not running that workspace server. 

What else can I do? Is web-ex an option, to see if there's anything else that can be done on my side? What are you doing with saspy, if all of that works? I could at least diagnose and prove out my theory about your DB2 access engine error and see what we can do about that. 

Tom

**Comment by isonimiguelBB** [comment]
There are a lot of java processes and they consume a lot of memory in an unstable way, but I can't see if STDIO SSH is the answer because I can't get to that part.

What would I need to set that session up in STDIO SSH?

Web-ex is blocked here. I'm using SASPy to make some DB2 data available in a MySQL server basically. The company didn't purchase the MySQL module, only DB2.

The plan C is to use IOM JAVA executing as cronjobs and see if that works out.

Thank you!

**Comment by tomweber-sas** [comment]
So, what java processes are you referring to? Ones that have to do with the code you showed above?
So far I haven't seen any saspy code, so I can't tell what's really going on.

As for what you need from the workspace server configuration, I don't know. Can you connect to the workspace server using IOM; forget all the code you're trying to run, just make a connection and see what is set up on there (which would be the same from EG). Do you have access to SMC? You can use that to see what all is defined in metadata for that workspace server, I would look at the environment variables for that servers session, to see if db2 libraries are added to the path, or if it has other db2 client variable defined so that it works. You could then try to set up the same things for your session. 

I still don't understand why IOM isn't feasible, but I don't have a clear understanding of what you're doing w/ saspy. Nor if it's the IOM java client processes you're talking about or some other java processes associated with all that other code you're running. I don't know of a reason the IOM Java processes would '[use] memory in an unstable way' or what is really going on, but if it's got something to do with them , I'd like to understand what the situation is. If it's other processes based upon the other code you're running, then maybe it's just more work that your machine can handle at a time? I don't have enough info to know.

Can you tell me what java processes you think are causing the problem?

Thanks,
Tom

**Comment by isonimiguelBB** [comment]
The java processes initiated on the client side to make the connections, I don't start java from my code in any other way.

What are the system variables I have to obtain to make the DB2 connection?

**Comment by tomweber-sas** [comment]
So, you're saying the saspy IOM client java process? Can you make an IOM connection to that same workspace server you connect to from EG? What saspy code are you running when you say the java process uses up all the memory? I'd like to understand what is going on with that.

I don't know how your db2 client is configured for your SAS/Access to DB2 on your woirkspace server. That's what you need to find out if you are going to try to run your own SAS session instead of using the workspace server. I'm afraid I don't know how that's set up at your site.

I'm curious to understand if there's really a problem with the IOM java process or not. Can we look into that?

First I would like to see that you can actually connect to that workspace server. Then see what code you're trying to run. Then try running it directly form python w/out all that extra multiprocessing and other code. Then with all of that, but only 1 thread (process), instead of 8. At each of these steps, see if everything works and behaves as expected and if not, then figure out why without all of the rest being in the way. I don't know what is causing what kind of problem on your system, as of yet. But identifying the actual problem and getting this to work the right way is what I'd be inclined to do.

Can we work through that? Can you show me the saspy code you're running, and show the connection to the workspace server working by itself? You should be able to have your libname to db2 work, assuming it's the same as what you do in EG.

This would be easier to do together via web-ex, what I was looking to do, but I understand if that's not  an option, we can working through it like this is. If you have any issue with posting results or info I need on here, we can just use direct email. And if your company requires it, we can even work directly through a SAS Tech Support ticket. Whatever is the best way for you.

Thanks,
Tom

**Comment by isonimiguelBB** [comment]
I thing I got it. The DB2 library is not in the same path as the SAS program. Example: SAS installed in /opt/sasinside/SASHome/SASFoundation/9.4/bin/sas_u8 and DB2 library in /opt/IBM/db2/sqllib

How do I pass all the paths to SASsession constructor?

I'm connecting using 1 process now, the same problem. Tried a code as simple as:
>import saspy
>
>sas = saspy.SASsession(cfgname='ssh')
>data = sas.submit(
>    """libname DB2TEST DB2 authdomain=domain schema=DB2TEST database=database;
>        proc sql;
>            select * from DB2TEST.TEST;
>        quit;""")
>print(data['LOG'])

No problema continuing here, just have to censor some things =)

**Comment by tomweber-sas** [comment]
Well, looking at page 47 in the SAS/ACCESS install doc:
http://support.sas.com/documentation/installcenter/en/ikfdtnunxcg/66380/PDF/default/config.pdf

It seems like you need to add the db2 client libraries to the LD_LIBRARY_PATH.
Since you're using ssh, you must have an account on that machine, so you could set this in your .profile or .[shell]rc file so when you connect, it's already set, so the SAS process you're creating would have it available.

But, again, I would suggest using the workspace server itself.

**Comment by tomweber-sas** [comment]
Can you run that code using the IOM access method connecting to the workspace server?

**Comment by isonimiguelBB** [comment]
With IOM it works perfectly, but as I keep loading tables, lots of java processes are created and aren't killed.

**Comment by tomweber-sas** [comment]
How many SAS sessions are you creating? Are you ending them ever? Why would the java processes be killed? They terminate when you end the SAS session. Do you just keep creating more? I've yet to see a line of saspy code that you are running, so it's hard to provide any insight. I just have to guess at what you might be doing, and if there's something you should be doing differently, which would work just fine. 
I have been looking at the java iom process while transferring large amounts of data across each direction (python to SAS and back), and I see no unusual memory consumption or leaking by the java process. But again, I'm just guessing that moving data is what you are probably doing? 
Can you provide any information about what you are doing that might help me figure out how to get this to work for you? I have to believe there's something you could be doing differently that could make this work, but again, I have no idea what you are doing.

It sounds like you just keep creating more and more SAS sessions until you run out of memory on your machine. But ???

Tom

**Comment by isonimiguelBB** [comment]
You gave me an insight! Thank you. I wasn't ending the sessions (endsas()), now java gets killed. and doesn't consume all my memory - yet.

Thanks again! And sorry for the "newbiness"!

**Comment by tomweber-sas** [comment]
ok. You know that these sessions are interactive sessions and you can run more than one thing in them, right? It kinda sounds like you're creating an entire session for each saspy code (whatever code that is) you're trying to run. You can run as much code through one session until you are done. You don't need to keep creating and terminating sessions just to run  one piece of SAS code.

Again, I don't know what you're running, but I'm glad it's starting to come together. I think if you used a session for more than one thing, you would probably have even more progress.

But, I'm glad you're getting closer!

Thanks,
Tom

**Comment by tomweber-sas** [comment]
One last thought. If you are moving data from SAS to python (sasdata2dataframe sd2df), and your SAS data sets are of any significant size, you may find the _CSV version to be much more efficient. sd2df_CSV()  instead of sd2df().
just in case :)
Tom

**Comment by isonimiguelBB** [comment]
Thank you very much!
