### ISSUE TITLE
%%SAS <class.session_object> returns 'Invalid SAS Session object supplied'

### ISSUE THREAD

**Issue by kjnh10** [sassoftware/saspy#262]
**Describe the bug**
``` python
#mycalss.py
import saspy
class MyClass(object):
    def __init__(self):
        self.sas_session = saspy.SASsession(cfgname='....', omruser='', omrpw='')
```

``` python
#on jupyter lab
##cell1
from myclass import MyClass
myclass = MyClass()

##cell2
%%SAS myclass.sas_session
proc options option=encoding;run;  /* any code */
-> 'Invalid SAS Session object supplied'
```

If I change like below, it works.
```python
##cell2
session = myclass.sas_session
##cell3
%%SAS session
proc options option=encoding;run;  /* any code */
```

**To Reproduce**
See above

**Expected behavior**
it works

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [jupyter on windows, sas server on linux]
 - SAS Version: 9.4M3
 - SASPy Version: 3.1.6

**Comment by tomweber-sas** [comment]
Interesting one :)
Yes, I was able to reproduce this, thanks for the clear instructions.
It turns out that the SASsession object you supply on the magic:
```
%%SAS myclass.sas_session
```
is not passed in to the SAS magic code as an object, but rather as a string. The magic code has to find this string in the list of objects in the users namespace to then access that object. So, a multi-part object reference 'obj1.obj2' as a string, doesn't match an object name in the name space, as there will be two objects each with a single part name; 'obj1' and 'obj2' and nothing named 'obj1.obj2'.  The second case with a single part name is found, as you saw. 

In the namespace there are objects named:
'myclass', 'sas_session', and 'session' but no single object named 'myclass.sas_session'.

I'm not familiar enough with this code currently to know if there is a straight forward way to address this. The only thing that jumps out at me is to parse what you pass in, looking for '.' dots, and find the first part of the name as an object, and if that's found, see if the next part of the name is an attribute of that object (another object), and continue down the line till the last part of the multi-part name is an object that's found and is a SASsession object. Or you can assign it to a single name and it all works fine :)

I've attached an html version of my notebook; can't attach .html, so I added .txt to it. If you download it and remove the .txt it will render as an html when you open it. It shows me stepping through the SAS magic code in the debugger to identify what I explained above. I didn't know this ahead of time, just stepped through it and observed. 

[Issue262.html.txt](https://github.com/sassoftware/saspy/files/3707575/Issue262.html.txt)

So, are you ok with just using a single object name, or would you like me to try to pursue a workaround to allow the multipart names?

Thanks,
Tom

**Comment by kjnh10** [comment]
Hi @tomweber-sas,

Thanks for your detailed explanation.
I think it's better to use this format, though it's not must...

I created a pull-request #263 , could you check it?

Thanks,

**Comment by tomweber-sas** [comment]
That was a good fix and it's merged in. Thanks for coding that up for me and submitting it!
It's at master now. I'll let you close this, after you verify it's working too.

Thanks,
Tom

**Comment by kjnh10** [comment]
@tomweber-sas ,

I checked out master and verified it's working fine!
So I'm going close.

Many thanks for your quick action.
