### ISSUE TITLE
head() fails for a sasdata which has extended name

### ISSUE THREAD

**Issue by kjnh10** [sassoftware/saspy#264]
**Describe the bug**

# my code
```python
import saspy
sess = saspy.SASsession(
    cfgname=".....",
    omruser='......',
    omrpw='....',
    )

sess.submit('LIBNAME LIB BASE "somewhere";')
dat = sess.sasdata(table='201906_data', libref='LIB')  # this data exist and valid i can confirm from SAS EG
# dat = sess.sasdata(table='data_201906', libref='LIB')  # for this case, issue does not happen. 
dat.head()  # -> failed
```

# from my config for sas session
```
winiomlinux = {
            'java'      : 'java.exe',
            'iomhost'   : '......',
            'iomport'   : ........,
            'classpath' : cpW,
            'autoexec' : 'options validmemname=extend;',  # this should make me to be able to use extended name for a dataset
            }
```

**To Reproduce**
See above

**Expected behavior**
this works

**Screenshots**
Error message
![image](https://user-images.githubusercontent.com/6933428/66631195-a9a90800-ec40-11e9-87e6-dfc099463605.png)

**Desktop (please complete the following information):**
 - OS: [jupyter on windows, sas server on linux]
 - SAS Version: 9.4M3
 - SASPy Version: 3.1.6

**Additional context**
in the variable 'code', the dataset name should be LIB.'201906_data'n instead of LIB.201906  
if I changed like below, 
```
dat = sess.sasdata(table="'201906_data'n", libref='LIB') 
```
other error occured in SASsessionIOM.exist() in sasioiom.py.

**Comment by tomweber-sas** [comment]
@kjnh10 thanks for entering this. I do see the problem, and have a fix for it that I'm still in the process of testing out. It does appear this is limited to the exist() method, although most SASdata methods drive an exist call before generating and submitting their code, so that ends up making it rather pervasive.

Most methods generate libref.tablename, so when you have these extended names, and use the 'xxx'n (N-literal) syntax, then they work just fine. You would have to set the validmemname=extend, as you did, and code the table name as an n-literal, which you did. The one place where I don't simply code libref.table, is in exist where I was using the exist function in the datastep. That function requires a quoted string (of the libref.tablename), and my extra quotes around your libref and n-literal were getting a syntax error.

I've adjusted the way I'm invoking the exist function and it's working for both n-literals and non-n-literal. So, I want to try to make sure everything is working with this before pushing it. But,it's looking good so far.

Will you be able to grab the fix from master to verify on your side when I push this? 

Thanks,
Tom

**Comment by kjnh10** [comment]
@tomweber-sas 
 Sure, when you are ready, please let me know. I will test.

**Comment by tomweber-sas** [comment]
wow, I was sure I actually submitted that yesterday, but it didn't seem so. Sorry about that. hopefully I can spend some time on this today and see how much closer I get to the final answer.

Tom

**Comment by tomweber-sas** [comment]
Hey!, gonna hit submit on this when I get done typing :)

So, I just pushed to the nliteral branch the changes necessary to support this w/out the user needing to do anything. I now submit the validmemname=extend option, and generate the N-literal syntax, including stripping any leading or trailing blanks (SAS allow you to submit them, but strips them off), so now you can just use table= '   3 bad  SAS table name  '  for any table= parm.
I have made all the changes in the common code and in the 3 access methods I wrote. The COM access method is next. It's completely different, so I did my 3 first as they were all similar changes.

So, if you grab nliteral, it should now work for you with your original case, no need for any options or funny syntax. Of course, if you find anything not working right, let me know. I've tested a lot, but I can't say it's 100% yet; more to validate, but it looks very good currently.

Thanks,
Tom

**Comment by kjnh10** [comment]
Hi @tomweber-sas,

That user don't need to use nliteral is what I really wanted! Thanks.

I will check out the branch and test it.
When finished, I will let you know the result.

**Comment by kjnh10** [comment]
I checked that this branch is working for a code I have written first.
And  I have also used this branch for the whole day and it seems working fine,

**Comment by tomweber-sas** [comment]
Cool! I'm not sure when I'll be building another version, but as you have this running from master, I'm guessing you're good for the time being?

**Comment by kjnh10** [comment]
I think this feature has not been merged to master yet.
I tested in the nliteral branch. Am I missing something?

Anyway, there is no time limit though I hope it will be released soon,

Thanks,

**Comment by tomweber-sas** [comment]
Yes @kjnh10, it is still in the branch and I have not merged that to matter yet. I was inundated last week and issues, but I'll see about merging it in to master tomorrow.
Appreciate you testing it out and verifying the changes!
Thanks,
Tom

**Comment by tomweber-sas** [comment]
ok, I finished up the changes in the COM access method to get this working in it too. I just merged all of it into master, so you should be good to go from there. Let me know if all is good from your side with it and we can close this one.

Thanks!
Tom

**Comment by kjnh10** [comment]
Hi @tomweber-sas,

Many thanks, I have confirmed that it's working fine.

**Comment by tomweber-sas** [comment]
Awesome, thanks for verifying!
Tom
