### ISSUE TITLE
Transcoding error encountered

### ISSUE THREAD

**Issue by wonderfreda** [sassoftware/saspy#268]
**Describe the bug**
I am trying to convert a dataframe to a sas dataset. And I encountered the following error message:

![image](https://user-images.githubusercontent.com/30054031/67016570-63cbc400-f0c6-11e9-9a0b-670f2fde4c90.png)

**Desktop (please complete the following information):**
 
![image](https://user-images.githubusercontent.com/30054031/67016639-8231bf80-f0c6-11e9-850b-db5292ebb532.png)

I presume it's caused by encoding difference between latin1 versus cp1252, but don't know how to resolve it. Thank you very much!

**Comment by tomweber-sas** [comment]
Well that was quick :)

Ok, so this is an issue with the SAS session you are using is running in the windows latin1 (1252) code page. It only supports single byte ASCII characters. But, the data in your dataframe, has characters that don't exist in that 1252 single byte code page. To have this really work correctly, SAS would need to be running with encoding=utf8, then this would have no problem importing the characters in your dataframe.

As you're running a local windows install of SAS, I expect that you may have SAS installed with uicode support? Since you have SAs installed in the usual location, I think you can determine if you have the ability to run SAS in utf8 this way.

Look in C:\Program Files\SASHome\SASFoundation\9.4 \nls and see if you have a folder named 'u8'.
If so, then take a look at C:\Program Files\SASHome\SASFoundation\9.4\sasv9.cfg  it would probably just contain this line:
-config "C:\Program Files\SASHome\SASFoundation\9.4\nls\en\sasv9.cfg"

If you have that u8 directory, you can have your SAS session come up running in utf8 by simply changing that line to 
-config "C:\Program Files\SASHome\SASFoundation\9.4\nls\u8\sasv9.cfg"

You can change it back to use wlatin1 at will. But if you can try running it in utf8, then you should be able to load the data from that data frame that has unicode characters (or at least, non-cp1252 characters).  Do you know what data is in the data frame that isn't supported in Windows code page?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Any progress with this? Are you able to run SAS in utf8 and have this work for you? 

If, for some reason, you can't, like don't have utf8 support installed or something, then the next thing would be to clean up the data in python before moving into your Wlatin1 SAS session. I don't know what the data you have in the dataframe is like, but for strings you can use encode().decode() to convert them. In python they are utf8, but you need them to be able to go to cp1252, but there are characters that can't. Your choices are to change those chars to something that exists in cp1252, or convert them to the usual substitution character. So, if you want it in 1252 SAS and don't care that the chars that can't exist are converted to the replacement charater, you could do this to the strings in question; to the columns of the dataframe or whatever, but if you had a sting named bob then:

bob = bob.encode('cp1252', errors=replace).decode()

Now bob doesn't have any characters that can't exist in cp1252. Of course, you don't have to original, valid data anymore, but that's because it can't exist in that code page.

So, it's either run SAS in a code page that supports the data you're loading, or convert that data so it can be loaded, by getting rid of the unsupported characters if that's ok.

```
str.encode(encoding="utf-8", errors="strict")
 Return an encoded version of the string as a bytes object. Default encoding is 'utf-8'. errors may be
 given to set a different error handling scheme. The default for errors is 'strict', meaning that
 encoding errors raise a UnicodeError. Other possible values are 'ignore', 'replace', 'xmlcharrefreplace', 
 'backslashreplace' and any other name registered via codecs.register_error(), see section Error 
 Handlers. For a list of possible encodings, see section Standard Encodings.

```

**Comment by wonderfreda** [comment]
Hi Tom,

Thank you very much for checking in! I was able to resolve the issue with
the saspy on our server edition and got work done there. As for the
original post I wrote last week, the strange truncation of sas.df2sd was
caused by a \n character in my text string in the column of the dataframe.
Once I removed the \n from the text, then it exported the entire dataframe
as anticipated. Thanks again for your help!

**Comment by tomweber-sas** [comment]
Hey, no problem, and I'm glad you got around it. Hmm, strange about getting a transcoding error for \n, as that's a single ASCII byte which exists in all of the codepages. However, there is (was) a problem in df2sd when data has embedded newline characters in the strings. So, maybe there was a compounded problem while you were trying to get around this which then had downstream effects???

Hey, but that issue caused me to add an option to the df2sd method to actually support transferring embedded newlines in character columns into the SAS datasets so you can actually get those in and not have to 'clean' them from your data before it can work. Just add embedded_newlines=True to your df2sd method invocation:

sd = sas.df2sd(..., embedded_newlines=True)

and this should get the data over with newlines intact in the columns. :)
The reason that's not the default is that it adds a little extra overhead, and it's not a terribly usual case. So, didn't want to add to overhead for all the times you don't need it, and it's easy enough to set the flag on the call to make it work.

```
embedded_newlines – if any char columns have embedded CR or LF, set this to True to get them iported into the SAS data set 
```
If you want to try that and see if it addresses the original problem, cool. If you're past it and have moved on that's fine too. If so, is there anything else I can do for this issue? Or should it be closed?

Thanks!
Tom

**Comment by wonderfreda** [comment]
Cool! I will give it a try! Do I need to upgrade the saspy in order to see
the new functionality? If so, I don't want to bother our tech team with new
refreshing, but will keep in mind for this added feature going forward. You
can go ahead and close the ticket. Thanks again for your help!

**Comment by tomweber-sas** [comment]
Actually, you showed you have 3.1.6, so I believe you already have it! Give it a try!

**Comment by tomweber-sas** [comment]
I'll go ahead and close this one. If you get a chance to try the embedded newlines, I hope that solves the original issue. If you need anything else, as always, just let me know!

Thanks,
Tom
