### ISSUE TITLE
Parsing error due to misinterpreted dtypes

### ISSUE THREAD

**Issue by fdegier** [sassoftware/saspy#271]
**Describe the bug**
When calling the method `.to_df_CSV()` it will eventually run the following code: 

```python
df = pd.read_csv(tmpcsv, index_col=False, engine='c', dtype=dts, **kwargs)
```

This however results into a parsing error:
```python
ValueError: could not convert string to float: 'Random_string_with integer (50)'
```

This is caused by incorrect assumption of the data type by the logic on lines 1792 - 1802 in `sasioiom.py`

**Expected behavior**
Either proper assumption of datatype so Pandas can convert those, or no dtype specification so Pandas will infer the schema.

**Comment by tomweber-sas** [comment]
Hey, thanks for entering this, and I saw the other one too. Can you show me the output from the contents() method for the SASdata object you were running to_df_CSV() from? What column did it assume the wrong data type? I get the data types from the SAS data set itself, and try to then set them appropriately for the data frame. So, if that's failing for some case, then I certainly want to address that. 

Thanks,
Tom

**Comment by fdegier** [comment]
As far as I can tell, there is an option to specify the dtypes when calling `to_df()`, however down the road it will apply this logic:
```python
      dts = kwargs.pop('dtype', '')
      if dts == '':
         dts = {}
         for i in range(nvars):
            if vartype[i] == 'N':
               if varcat[i] not in self._sb.sas_date_fmts + self._sb.sas_time_fmts + self._sb.sas_datetime_fmts:
                  dts[varlist[i]] = 'float'
               else:
                  dts[varlist[i]] = 'str'
            else:
               dts[varlist[i]] = 'str'
```
As I am not giving it any dtypes I interpret this logic as making `vartype[i] == 'N'` a float unless its a date/time, and `vartype[i] != 'N'` a string. This means that the data type of my column is interpreted to become a float while it actually should be a string.

When I tested the same data without `dtypes` specified, Pandas complained about mixed type columns, I then added `low_memory=False` to have Pandas infer the dtypes. This resulted in correct parsing and allowed me to use the Pandas method `to_parquet()` successfully. 

### Conclusion
It seems that the parsing of the dtypes does not cover all cases, its a bit hard to debug as Pandas does not provide the column name of the one that failed to parse (I will spend a bit more time on it to find the offending column). 

It would be a nice addition to just have Pandas infer the dtypes, as that would provide a way to continue, e.g.:

```python
 try:
    df = pd.read_csv(tmpcsv, index_col=False, engine='c', dtype=dts, **kwargs)
 except ValueError:
   print("WARNING: Letting Pandas infer dtypes, ignoring specified dtypes")
    df = pd.read_csv(tmpcsv, index_col=False, engine='c', low_memory=False, **kwargs)
```

**Comment by tomweber-sas** [comment]
Hey, can you show me the output from the contents() method of your data, so I can see what columns and types and formats they have?

The logic regarding the vartype[i] == 'N' being a float or string is actually correct. SAS only has 2 data types, Numeric and Character. Numeric is a floating point number. Character is an array of bytes. So, vartype[i]  is either N or C. That's it; so it is either a number (float) or a string. BUT, here's the catch, SAS has date/time/datetime formats, which apply to Numeric floats, which makes SAS **interpret** the numbers as the number of seconds or days since a point in time (date time datatime). They are still floats.

So, the check for N, as opposed to C, then looks at the format of the variable to see if that N (float) is supposed to **represent** some kind of datetime. If so, then that SAS float was written out as a datetime string, not as a number, in the csv file (I made it do that). So any string should be able to be loaded into pandas without it being a problem. But, whatever you ran with whatever data, didn't seem to get there. The next step is then the rest of this story. You should see that after creating the data frame (which usually works :) ),  I run the following code to follow up on that datatime logic from above:

```
      for i in range(nvars):
         if varcat[i] in self._sb.sas_date_fmts + self._sb.sas_time_fmts + self._sb.sas_datetime_fmts:
            df[varlist[i]] = pd.to_datetime(df[varlist[i]], errors='coerce')
```
This takes the Charater column, that should have been successfully loaded in to pandas, with strings that pandas can correctly interpret as datetimes (what were floats in SAS with some datetime format), and tells pandas to convert that column to it's actual datetime type, instead of it being a string (Object), type. 

In your case, that step isn't happening. But, I don't know what data you are starting with nor which column is causing that error (if it even is a datetime column that's the problem), nor what data values are in that column in the csv file that was created. So, I can't really tell what the real problem is or what should actually be done to resolve it.

I do allow for you to override dts (the data types I tell pandas to use), and you can specify kwargs to the sd2df_CSV which will then be passed on to pr.read_csv, so that if there is really some odd case that doesn't work (like this, maybe), you have the ability to manipulate pandas with it's various parameters (like the low memory one, or anything else). I didn't find pandas guesses of datatypes to be be consistent or deterministic or, frankly, reliable, such that I specifically go through all the work to determine the types from SAS to then specify them explicitly to pandas. And, again, that usually works :)

So, I'd like to see what this specific problem is that you're hitting, as all the cases I've tried, this all works correctly. But, as there's no end of different data; I've certainly not driven every possible case. If there's a case here that I can handle, which I'm not currently, then I want to tighten that up so that this just works like it's supposed to, which would be ideal.

If it turns out to be some anomalous case that I can't fix in my code (I doubt), then we can figure out what parameters to specify in sd2df_CSV(), to get the correct behavior for you for this case. Sounds like possibly (..., dts={}, low_memory=False). But again, gotta know what the actual problem is.

Thanks!
Tom

**Comment by fdegier** [comment]
Hi Tom,

Thanks for your continuous support and explanation (I'm new to SAS). So after a bit of debugging I found that the column is a N vartype and the varcat is `BEST` which according to the logic leads to a conversion to float. However it has at least 1 value that looks like this: `Random number (5000)` which causes the conversion to fail. If I for testing purposes add `BEST` to `sas_date_fmts` then it works as it gets converted correctly. 

You are right about Pandas conversion not being ideal, but as I'm more interested in actually getting the data than receiving the right data types in Pandas. 

Please note that `.content()` still suffers from the `obs()` issue:
```log
['ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file ', '
```

**Comment by fdegier** [comment]
Please also note that `.contents()` does not take into account the `obs` issue, see the following:

```python
varcat = l2[2].split("\n", nvars)
print(varcat)
```
Out:
```log
[2019-10-24 12:24:49,750] {{logging_mixin.py:95}} INFO - ['ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file
```

**Comment by tomweber-sas** [comment]
Wait, what is this error? I haven't seen that before. What code are you running? The spde engine doesn't support obs=???

I just tried that and it didn't produce any error. what is your libname statement for this data that gets this error?:
```
 1? libname x spde '.';

NOTE: Libref X was successfully assigned as follows:
      Engine:        SPDE
      Physical Name: /opt/tom/github/saspy/

 5? proc datasets dd=x;

                                  Directory

                Libref               X
                Engine               SPDE
                Physical Name        /opt/tom/github/saspy/
                Free Space (Kbytes)  213516505
                Metapath             '/opt/tom/github/saspy/'
                Indexpath            '/opt/tom/github/saspy/'
                Datapath             '/opt/tom/github/saspy/'


                      Member    File
             #  Name  Type      Size  Last Modified

             1  SPD1  DATA     42884  10/24/2019 08:56:26

  6? proc print data=x.spd1(obs=10);run;

NOTE: PROCEDURE DATASETS used (Total process time):
      real time           15.63 seconds
      cpu time            0.01 seconds


                                The SAS System                               1
                                              08:55 Thursday, October 24, 2019

                                   Obs    x

                                    1     1
NOTE: There were 1 observations read from the data set X.SPD1.
NOTE: PROCEDURE PRINT used (Total process time):
      real time           0.13 seconds
      cpu time            0.04 seconds


  7? libname x list;

NOTE: Libref=   X
      Scope=    Line Mode Process
      Engine=   SPDE
      Physical Name= /opt/tom/github/saspy/
      Free Space (Kbytes)= 213516505
      Metapath= '/opt/tom/github/saspy/'
      Indexpath= '/opt/tom/github/saspy/'
      Datapath= '/opt/tom/github/saspy/'

  8?
```

I really need to see what you are running and the SAS log to see what's going on. And what's the definition of whatever SASdata object you are using? Just submit the object and it displays it's info.
Submit the SASsession object too, so I can see that information as well. And, you're saying contents() fails with this error? Can you just take obs= off of that object and run the contents? 

You're saying that whatever variable you think pandas is failing on is a Numeric in SAS, but you see a value somewhere that is this:  Random number (5000) 
What it that actually? A string that has those words and the number in parens? I don't understand what that is or where you see it. A SAS numeric variable is a floating point double. So I still don't know what's going on here.

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom,

I'm not sure what the datatype `BEST`  means but it gets converted to a float which Pandas does not allow as it is a string.

**Comment by tomweber-sas** [comment]
there's no data type called best, that's a SAS format. But I can't see anything about what you're running.

**Comment by tomweber-sas** [comment]
As you're online now, would it be possible to do a web-ex (I can set that up), so I can see what it is your doing and get the information I need to be able to help? 
Thanks,
Tom

**Comment by tomweber-sas** [comment]
ok, so, per the call, I was able to do the 3 parts independently as follows, so try this out with whatever other delimiter you want and see if it behaves right, and you get the correct data in your dataframe. You can ignore the dtpyes for this case, as that's irrelevant for this test. I chose '~', but try whatever isn't in your data.

```
delim= '~'
data.to_csv(sas.workpath+'delim.csv', opts={'delimiter' : delim})
print(sas.download('/tmp', sas.workpath+'delim.csv')['LOG'])

import pandas as pd
pd.read_csv('/tmp/delim.csv', index_col=False, engine='c', delimiter=delim)
```

the sd2df_CSV() does not support the opts= at the moment, so I'll need to add that in so that, assuming the above test case works, you can use that instead of doing the 3 parts manually as in this test case. I'll work on enhancing that next. When that's fixed, you would them be able to just do
```
df = data.to_df_CSV(opts={'delimiter' : '~'})
```

Thanks!
Tom

**Comment by tomweber-sas** [comment]
**I thought I posted this last night, but it doesn't seem to have actually gotten out there**

ok, I was able to add in the same support for the proc export part of sd2df_CSV() and push it to master too.
So, make sure you grab the latest master and are running that code. Then you can try this with the sd2df_CSV method too. The following case I used '&', but again, whatever isn't in your data to trip up pandas.

So you need to pass opts= for me to use for the proc export, but then you also have to provide the kwarg for me to pass to pandas to tell it what the delim is when it's not a comma. In the following case, I don't do that at first, and that shows that it gets parsed wrong, but you can then see the delimiters were in that file, as the first column, gets the whole row because there aren't commas; so you can see the '&' between the real column data.
Then tell pandas what the delim is and it get's it right.
```
import saspy
sas = saspy.SASsession(cfgname='iomj')
data = sas.sasdata('cars','sashelp')
df = data.to_df_CSV(opts={'delimiter' : '&'})
df.head()
df = data.to_df_CSV(opts={'delimiter' : '&'}, delimiter='&')
df.head()
```
```
>>> sas = saspy.SASsession(cfgname='iomj')
SAS Connection established. Subprocess id is 8498

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.
>>> data = sas.sasdata('cars','sashelp')
>>> df = data.to_df_CSV(opts={'delimiter' : '&'})
>>> df.head()
  Make&Model&Type&Origin&DriveTrain&MSRP&Invoice&EngineSize&Cylinders&Horsepower&MPG_City&MPG_Highway&Weight&Wheelbase&Length
0  Acura&MDX&SUV&Asia&All&36945&33337&3.5&6&265&1...
1  Acura&RSX Type S 2dr&Sedan&Asia&Front&23820&21...
2  Acura&TSX 4dr&Sedan&Asia&Front&26990&24647&2.4...
3  Acura&TL 4dr&Sedan&Asia&Front&33195&30299&3.2&...
4  Acura&3.5 RL 4dr&Sedan&Asia&Front&43755&39014&...
>>> df = data.to_df_CSV(opts={'delimiter' : '&'}, delimiter='&')
>>> df.head()
SAS Connection terminated. Subprocess id was 8417
    Make           Model   Type Origin DriveTrain     MSRP  Invoice  EngineSize  Cylinders  Horsepower  MPG_City  MPG_Highway  Weight  Wheelbase  Length
0  Acura             MDX    SUV   Asia        All  36945.0  33337.0         3.5        6.0       265.0      17.0         23.0  4451.0      106.0   189.0
1  Acura  RSX Type S 2dr  Sedan   Asia      Front  23820.0  21761.0         2.0        4.0       200.0      24.0         31.0  2778.0      101.0   172.0
2  Acura         TSX 4dr  Sedan   Asia      Front  26990.0  24647.0         2.4        4.0       200.0      22.0         29.0  3230.0      105.0   183.0
3  Acura          TL 4dr  Sedan   Asia      Front  33195.0  30299.0         3.2        6.0       270.0      20.0         28.0  3575.0      108.0   186.0
4  Acura      3.5 RL 4dr  Sedan   Asia      Front  43755.0  39014.0         3.5        6.0       225.0      18.0         24.0  3880.0      115.0   197.0
>>>
```

Thanks!
Tom

**Comment by fdegier** [comment]
Thanks Tom, this does help. After further investigating the issue also occurs due to break lines being in a text field. This causes pandas to read the csv with split lines and causes the conversion to fail. If the fields in the CSV were quoted this would have been prevented.

Is it possible to add quoting to the fields? Or to remove break lines from the CSV?

**Comment by tomweber-sas** [comment]
Well, when I was looking at the doc for proc export, to see what options it had, delimiter= being the one we're using here, I was expecting to see something about quoting or otherwise escaping character columns, for just his kind of a reason, but it didn't have such options. 

https://go.documentation.sas.com/?docsetId=proc&docsetTarget=n045uxf7ll2p5on1ly4at3vpd47e.htm&docsetVersion=9.4&locale=en

When I added this (_CSV versions of sd2df), it was to work around the performance issues of trying to stream the data over and generate the dataframe dynamically in memory. All the object churn causes that to be unwieldy when the data is too large. Pandas can read in a file much quicker, so persisting to disk and having pandas read that was much more performant. And as CSV seems to be the defacto standard for things these days, that seemed to be the way; and we had proc export to read/write them. saspy was already using that for read/write_csv methods.

But, it seems full support, like what you are running into now, isn't there to make that work for all cases. I was thinking this through some last week and I saw that pandas has a couple other read_*() methods, beside CSV, to read in files, and I started thinking that if I used my original sd2df method, with an option to persist that format to disk and have pandas read it in (I still have to investigate this) then maybe I would have better control over all of these other issues; delimiters, embedded newlines, ...

I don't see a way to have proc export add quotes when it writes out the csv, so I'm going to investigate trying to create my own temporary disk format for pandas to read, via my original sd2fd method. I may regret that :) but I think it's something I need to look into. 

Let me see where I get with that and hopefully that can solve all of this.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
@fdegier I've been able to implement the idea I proposed above. I don't have it all the way hooked up, but I've pushed the prototype to master for you to try out. I have it implemented in the access methods for STDIO and IOM, so you need to call it specifically, as you can't get at it yet via sas.df2df() nor  data.to_df() or data.to_df_CSV()... . Once I make it production, assuming it works well, I'll hook it up to get at like you would normally.

Can you pull master and give the new method a try with those tables that are problematic, and the large ones as well, to see how it compares performance wise?

You can call it as follows, by accessing it off the access method object, off the SASsession object:
```
# if you had   df = sas.sd2df_CSV('table', 'libref') then you would use
df = sas._io.sasdata2dataframeTOM('table', 'libref')
```

And, yes, I'll rename it when I get it fully hooked up :)  It takes a combination of the options for sd2df and sd2df_CSV, but I don't think you'll need any of them, as I expect it to work for you with the defaults. But, here's the list in case I need you to try anything extra.

```
   def sasdata2dataframeTOM(self, table: str, libref: str ='', dsopts: dict = None,
                            rowsep: str = '\x01', colsep: str = '\x02', tempfile: str=None, 
                            tempkeep: bool=False, **kwargs) -> '<Pandas Data Frame object>':
      """
      This method exports the SAS Data Set to a Pandas Data Frame, returning the Data Frame object.
      table    - the name of the SAS Data Set you want to export to a Pandas Data Frame
      libref   - the libref for the SAS Data Set.
      dsopts   - data set options for the input SAS Data Set
      rowsep  - the row seperator character to use; defaults to '\x01'
      colsep  - the column seperator character to use; defaults to '\x02'
      tempfile - file to use to store CSV, else temporary file will be used.
      tempkeep - if you specify your own file to use with tempfile=, this controls whether it's cleaned up after using it
      """
```

Thanks!
Tom

**Comment by fdegier** [comment]
Hi Tom,

Thanks, I just tested your fix and the tables that had the conversion issue now parse correctly!

**Comment by tomweber-sas** [comment]
Well, that doesn't look right. I need information. Can you show me what data set you're trying to access; run contents() on it so I can see the variables and types and formats? And you can use the tempfile= and tempkeep=True to save the data that is being loaded into pandas, so I can see if there's something strange. And, are you sure you have master and no code changes of your own in the mix; just to be sure? Last time we saw something strange like that, we weren't running what we thought we were running. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey Fred, I just pushed a change to add a couple more parameters on the dataframe creation to be more explicit about the contents of the file. Assuming you are running the code I had at master, cleanly, there's probably something you're hitting w/ pandas that I'm not, probably related to the number of rows. That particular error is similar to when the embedded comas were making pandas parse the csv wrong, which should happen here. But it could be some other data related issue.
So, what's at master now might address it, but as I don't know what the issue really is, there's no telling.
If you want to jump on a webex tomorrow, I bet we can get to the bottom of it pretty quick. 

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom, 

Thanks and I have great news, just performed the tests again with the latest code from mater (did that yesterday as well) and it now works for all the troublesome tables.

**Comment by tomweber-sas** [comment]
Hey, that is great! I added 2 things, one was to specify the dtypes, which I have in the other versions, so that's consistent. Also, added the parm to specify for format for missing values in this new format of data. That's a little different than in the csv case, so I needed that. I thought those might be the answer to that message you got, but couldn't be sure. It shouldn't have been a parsing error; getting confused about the columns, but rather having pandas guess the types based upon the data in the columns. As your' data was larger than what I've been using to prototype this, there's the possibility for more variation across a lager distribution of rows, such that it might 'confuse' the algorithm that tried to guess the types. And, if there were missings in there, in this different format, that would have made that worse too.

I'll work on adding this in as an official method, so you can get at it directly from the SASsession and SASdata objects, same as sd2df() and sd2df_CSV() and to_df() and to_df_CSV(). Also, I still need to do some more testing on it to make sure I've got any other bases covered. But, your verification helps a lot too! Especially since your cases were not working with the existing _CSV() methods and work with this. I assume they worked with the non-_CSV method, but that was too slow and probably ran out of memory, so as to not be able to tell for sure.

Once I get this added and tested, I'll be able to push it out and build a new release with all of these fixes and enhancements from over the past couple weeks. Then you can get it all via the latest production version; 3.1.7, and I have to doc all these too. Fun, fun :)

Thanks for helping get to the bottom of this and trying out the different enhancements to get this working successfully! And for verifying this!

Tom

**Comment by fdegier** [comment]
Sounds great Tom, thanks for all your help, looking forward to the official release!

**Comment by tomweber-sas** [comment]
I've pushed the changes to access this from the  SASsession and SASdata objects/methods. So, just the like the CSV methods, you can now use this (_DISK) method as follows:

```
# given these
sas = saspy.SASsesion()
sd = sas.sasdata('table','libref')

# from sas (SASsession) you can use sasdata2dataframe with method= or the _DISK alias
df = sas.sd2df('table','libref', method='disk')
df = sas.sd2df_DISK('table','libref')

# from sd (SASdata) you can use to_df with method= or the _DISK alias
df = sd.to_df(method='disk')
df = sd.to_df_DISK()
```

Would you mind terribly pulling this from master and validating your cases with these new methods: sd2df_DISK() or to_df_DISK(), whichever you had the CSV version coded as. Just a sanity check to verify that these changes haven't messed up anything with your cases. It all looks good on my end, but before creating the new version, I'd like to see it work without a hitch w/ your stuff too.

Thanks!
Tom

**Comment by fdegier** [comment]
Hi Tom,

Originally I was using the following method:
```python
data = sas.sasdata(table=table, libref=libref, dsopts=dsopts).to_df_CSV(opts={'delimiter': ';'}, delimiter=';')
```
I've changed this to:
```python
data = sas.sasdata(table=table, libref=libref, dsopts=dsopts).to_df(method='disk', opts={'delimiter': ';'}, delimiter=';')
```
This works as expected.

**Comment by tomweber-sas** [comment]
Hey Fred, I'm a little confused by that. That shouldn't actually work.  opts= isn't supported on this method, nor needed (though it's ignored), and passing in delimiter=';' would break this as that's not the delimiter and would cause pandas to not parse the file correctly. Neither of those parameters should be used. Any chance of a webex today so I can see what is happening? I just tried adding those parameters to one of my cases and it fails as I would expect. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
My guess is that you weren't running what's at master and that just went down the original path, which wouldn't use any of those options, and, as I was thinking, already worked for your data; just not as fast with large data sets. That's the only way I could see that working correctly.

**Comment by tomweber-sas** [comment]
You can test out that theory by trying to run this and see what happens:
```
data = sas.sasdata(table=table, libref=libref, dsopts=dsopts).to_df_DISK()
```
Thanks!
Tom

**Comment by fdegier** [comment]
Hi Tom,

I've found another weird situation. Im running the latest version from PyPi 3.1.7 and now get the following error:

```
[2019-11-06 18:00:06,011] {{taskinstance.py:1051}} ERROR - could not convert string to float: '               .'
Traceback (most recent call last):
  File "pandas/_libs/parsers.pyx", line 1173, in pandas._libs.parsers.TextReader._convert_tokens
TypeError: Cannot cast array from dtype('O') to dtype('float64') according to the rule 'safe'
```
Which is caused by by the missing values replacement.

**Comment by tomweber-sas** [comment]
Hey Fred, I need to see the code you are running, and maybe the definition of the table you are accessing. Can you show me the code, and output, including submitting both the SASsession object and the SASdata object you are using and the output from SASdata.contents() for the description of the table?

Thanks,
Tom

**Comment by fdegier** [comment]
Hi Tom,

Maybe we can have a Webex tomorrow? I also found out that sometimes the disk method gives an empty dataframe while csv method does give correct results.

**Comment by tomweber-sas** [comment]
Sure. what time works for you? I'm available now too, if it's not too late there.

**Comment by fdegier** [comment]
Sorry I don't have the time now but whenever you're online tomorrow we can call, you can send me an invite via mail?

**Comment by tomweber-sas** [comment]
That works! I'll catch you in the morning (here), tomorrow!

**Comment by tomweber-sas** [comment]
Just a followup on this thread for looking back at it in the future. We did the web-ex and figured out that the saspyiom.jar being used with the current V3.1.7 code, was an old jar (don't even know what version), and that was the problem. Once we pointed to the V3.1.7 jar, things worked as expected.
Tom

**Comment by tomweber-sas** [comment]
Hey Fred, I've just pushed, to master, a performance improvement for the _DISK() method. Given the size of data you are processing, this could make a decent performance improvement for those cases. CSV is still a little faster, but for the cases where you have to use DISK, because CSV can't process the data, it should help out your overall processing time.
Tom

**Comment by tomweber-sas** [comment]
FYI, it's now at 3,1,8 production :) don't worry about master.
