### ISSUE TITLE
Supress terminal outputs from saslib

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#284]
Hi when I create a run the saslib command the below output is printed to my terminal. I 
``` 
24
25   libname mylib    '/path/to/lib'  ;
NOTE: Libref MYLIB was successfully assigned as follows:
      Engine:        V9
      Physical Name: /path/to/lib
26
27
```

Is there a way to surpress this?  I tried adding `nosource` to the `options` argument of the `SASsession`, but that caused the session to not be created successfully.   I also have the SAS_config_options `verbose` setting set to `False`.  Is there an 'extra' quiet mode?

Thanks,
Jeremy

**Comment by tomweber-sas** [comment]
Well, no. But, there is actually a way. So, let me explain. There are a few methods which don't return anything, like an object or something specific; like saslib, and unlike sasdata. So returning the log, so you can see if it worked or not, was really all there was, and displaying it seemed the obvious thing, as opposed to returning it and then you having to then display it yourself. Similarly with with methods that display graphs or charts; they just display as opposed to returning them for you to then have to display yourself.

So, that's the back story as to why the answer is no. 

But, there is a way to run saspy such that no methods outright display anything; rather you get an object returned that you can then programmatically do something with (displaying it being one of those things you can then do). This is batch mode, where 'displaying' anything is not the thing to do.
So, this is a very long way to say yes, :) 

You can toggle batch mode on/off around methods that you don't want displaying what they otherwise would. And then choose to not display what they returned :)

```
>>> sas = saspy.SASsession(cfgname='iomj')
SAS Connection established. Subprocess id is 16737

No encoding value provided. Will try to determine the correct encoding.
Setting encoding to utf_8 based upon the SAS session encoding value of utf-8.

>>> sas
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_work31B300000D53_tom64-5/SAS_workB86600000D53_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.2.0
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 3411


>>> x = sas.saslib('x', path='.')
4                                                          The SAS System                            13:37 Tuesday, February 4, 2020

28
29         libname x    '.'  ;
NOTE: Libref X was successfully assigned as follows:
      Engine:        V9
      Physical Name: /opt/tom/gitshit/notebooks
30
31
>>> type(x)
<class 'NoneType'>
>>>
>>> sas.set_batch(True)
>>> sas
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_work31B300000D53_tom64-5/SAS_workB86600000D53_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.2.0
Teach me SAS          = False
Batch                 = True
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 3411

>>> # now the log will be returned in x, which you don't have to print.
>>> x = sas.saslib('x', path='.')
>>> type(x)
<class 'str'>
>>> print(x)
5                                                          The SAS System                            13:37 Tuesday, February 4, 2020

34
35         libname x    '.'  ;
NOTE: Libref X was successfully assigned as follows:
      Engine:        V9
      Physical Name: /opt/tom/gitshit/notebooks
36
37
>>> # now, set it back to normal after not printing x - the log
>>> sas.set_batch(False)
>>>
```

So, the code would simply be:
```
>>> sas.set_batch(True)
>>> x = sas.saslib('x', path='.')
>>> sas.set_batch(False)
```

Tom

**Comment by biojerm** [comment]
If I don't every want to display anything, can I turn batch mode on for the whole session? Either via the sasconfig.py or as a SASsession argument?  Or is writing to the `batch` attribute once I create the SASsession object the best way?

**Comment by tomweber-sas** [comment]
Setting batch to True via sas.set_batch(True), is the way to do it. And, you can run you're whole script with it set. It was designed so you can run saspy in actual python batch scripts. Just be sure you assign the results from those methods to a variable, else, pythons default is to display the object.

**Comment by biojerm** [comment]
great thanks for the help!
