### ISSUE TITLE
Transcoding error on converting dataframe to sas dataset

### ISSUE THREAD

**Issue by snehak0991** [sassoftware/saspy#302]
Hi,

I am trying to load a dataframe from csv file and save it as a sas dataset but I get the following error on doing so:
DataFrame contains characters that can't be transcoded into the SAS session encoding.
'charmap' codec can't encode character '\u0391' in position 9: character maps to <undefined>

I tried debugging by looking at previous similar issues and realized that in my sas session object, the values for sas session encoding and python encoding values were different.
sas session object:
Access Method         = IOM
SAS Config name       = iomwin
SAS Config file       = /home/myusername/.virtualenvs/vbase3/lib/python3.8/site-packages/saspy/sascfg_personal.py
WORK Path             = M:\WORKSPACES94\myusername\SAS Temporary Files\_TD27416_PAPP84SAS01_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = windows-1252
SAS process Pid value = 27416

I tried to change the IOM encoding to wlatin1 but on creating the new session object got the below message:
The encoding provided (wlatin1) doesn't exist in this Python session. Setting it to ''.
The correct encoding will attempt to be determined based upon the SAS session encoding.

The new sas session thus created looks like:
Access Method         = IOM
SAS Config name       = iomwin
SAS Config file       = /home/myusername/.virtualenvs/vbase3/lib/python3.8/site-packages/saspy/sascfg_personal.py
WORK Path             = M:\WORKSPACES94\myusername\SAS Temporary Files\_TD21496_PAPP84SAS01_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 3.3.7
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 21496

With, this I again tried saving the dataframe as sas dataset and still got the same error as before:
Transcoding error encountered.
DataFrame contains characters that can't be transcoded into the SAS session encoding.
'charmap' codec can't encode character '\u0391' in position 9: character maps to <undefined>

code:
import pandas as pd
import saspy
df = pd.read_csv('linuxpath/csv_filename.csv',dtype={'col_m':str,'col_n':str,'col_o':str,'col_p':str,'col_q':str,'col_r':str})
 sas = saspy.SASsession(cfgname='iomwin', omruser='my username',omrpw='my password')
sd_df = sas.df2sd(df,table='sd_df')

What could be the reason for the error:
DataFrame contains characters that can't be transcoded into the SAS session encoding.
'charmap' codec can't encode character '\u0391' in position 9: character maps to <undefined>

Thanks in advance!

**Comment by tomweber-sas** [comment]
Hey @snehak0991 so python runs in utf-8. The data you loaded into the pandas dataframe has characters that are not supported in  the windows codepage that SAS is running in - wlatin1, cp1252, windows-1252 ... those are all aliases for the same codepage. If your SAS session was running in utf-8, then there would be no problem. And, if the only utf-8 characters in your dataframe mapped to characters that exist in wlatin1, then there would be no problem either. So, that is why you are getting that error. 
Are you able to run SAS in utf-8? Then you can correctly transfer and process that data in SAS.

**Comment by snehak0991** [comment]
Hi @tomweber-sas ,

Thanks for the information. I will check if I am able to run SAS in utf-8 and post once I have that information.

**Comment by tomweber-sas** [comment]
cool :)  There's no telling, as that error happened on the first occurrence, how many characters (how much data) are not supported by the windows codepage. So, using a UTF-8 SAS session will support everything in there and allow you to process the data correctly.

**Comment by snehak0991** [comment]
Hi @tomweber-sas,

How would we select the SAS session to run as a UTF-8 session? Do we need to specify when creating the SASsession object?

**Comment by tomweber-sas** [comment]
Well, from your output from submitting your SAS session, it appears you're connecting to a remote SAS session over IOM. Therefor that SAS server would be a Workspace server. Someone has configured and deployed that for users to connect to. saspy can connect to it. EG can connect to it. ...  So, who defined these? Often a site will deploy multiple AppServers so that you can have multiple Workspace server, configured differently. A SAS invocation option named Encoding is how a server is told what encoding to run. 
Do you use EG at all? Have you connected to this Workspace server before with it? How did you know this server existed to be able to connect to it?

**Comment by snehak0991** [comment]
Yes, it is a remote SAS server and I have connected to it using EG. I am guessing there is one administrator who has defined the configuration parameters, I do not have access to it.

**Comment by tomweber-sas** [comment]
Ok, From EG you can query (you can do this from saspy too) your metadata server to find out what AppServers are defined. For each Appserver, you can see the workspace server configuration. You need the host name and port for the metadata server. You can see this easiily from SMC (SAS Management Console) if you have that app installed too. See the instrucctions here: https://sassoftware.github.io/saspy/advanced-topics.html#using-proc-iomoperate-to-find-object-spawner-hosts-and-workspace-server-ports

SMC is the easiest way to look at this. Running these proc iomoperate queries are the next best if you can't just see the metadata with SMC. If you have multiple workspace servers, you can connect to eash one to see what encoding they are tunning.

You must have some SAS Administrator though, since you have workspace servers, so they would be who to contact to see what servers there are, and weather you have access to them and what encoding they are running. 

If you need, I can help walk you through going this, but the instructions above should get you there.
Tom

**Comment by snehak0991** [comment]
Got it thanks!

**Comment by tomweber-sas** [comment]
You found one running utf8, and it worked?

**Comment by snehak0991** [comment]
@tomweber-sas ,

There is currently only 1 SaSAppServer which has wlatin1 encoding so I couldn't find any utf8 encoding AppServers to connect to. We are working to see if new AppServer can be created with utf8 encoding that can be used with SaSpy. Thanks for the information on the encoding.

**Comment by tomweber-sas** [comment]
ok, So setting up another appserver with its workspace server running utf8 is a perfectly normal thing to do (for you admin to do, that is). In your saspy_personal.py, you will need to either change, or add another config definition, to point to that workspace server. You may need to use the appserver key in these to specify the different names for each workspace server. See the doc here for that: https://sassoftware.github.io/saspy/install.html#remote

I don't think I've seen your configuration definition, or I could provide examples showing this. But, if you already understand that, then you should be good. Let me know if yo need help with that.

**Comment by snehak0991** [comment]
Thanks, 
Yup, got what you are conveying about the changes to the saspy_personal.py. Hopefully I can get the new utf8 appserver soon and test this out. Thank you very much for all the information and quick response.  We can close the issue for now!

**Comment by tomweber-sas** [comment]
cool! just let me know if youneedanything else!
Tom
