### ISSUE TITLE
SASPY looks to close connection if SAS submit taking longer than 1hr

### ISSUE THREAD

**Issue by vmoulds01** [sassoftware/saspy#308]
**Issue**

We have a Python application that needs to connect to SAS and run some SAS code and we are using saspy library for this.  

When we execute SAS code that takes less than 1hr to run then everything works fine and the code completes sucessfully. 

When we execute SAS code that can takes more than 1hr to run then the python process hangs and doesn't seem to complete.  

When we looked at the SAS logs on the SAS server we see that the SAS code did actually complete but then it looks like the saspy session has been closed so it can't send the results back to SASPY session. 

Is there a setting in saspy that closes the session after you submit code?

We saw there is a timeout parameter that you can configure when creating SAS session and we tried changing that but it didn't seem to have any affect.  

We thought that issue https://github.com/sassoftware/saspy/issues/99 could have been related and we saw at the end of that issue log that it does mention not being able to increase the timeout past the 60 minutes setting - is that still the case?

**To Reproduce**
1. Open a SAS session using example code and set timeout to 120 minutes (2 hrs):
            sas_session = saspy.SASsession(cfgname=cfgname, appserver=appserver, timeout=120)
2. Submit a long running piece of SAS code e.g.
           sas.submit(""" Long running SAS macro """)
3. SAS code doesn't complete and just seems to hang 

**Expected behavior**
We thought the timeout setting would allow the SAS connection to live 2hrs and that we wouldn't see the connection being closed after 1hr in the logs.

Please let me know if you need any further information.

Thanks

Vicky

**Comment by tomweber-sas** [comment]
Hey Vicky, I can help with that. Which Access Method are you using? If you submit your SAS session object, it'll display that and more info that would be helpful. I'm guessing it's either remote IOM or HTTP. Your configurations definition from your sascfg_personal.py would be useful too.
Thanks,
Tom

**Comment by vmoulds01** [comment]
Hi Tom, 

Thanks for responding so quickly.

Access Method is remote IOM

Is there something specific you are looking to see in the config?  I'd rather not share the configuration file on Github so just wondering if you are looking for it to check something in particular?

Thanks

Vicky

**Comment by vmoulds01** [comment]
Hi Tom,

Sorry i have another question - did I understand the timeout parameter correctly and that it should increase the timeout of saspy session in minutes?  

Thanks

Vicky

**Comment by tomweber-sas** [comment]
Oh, I see it must be remote IOM, you have the appserver= on your session. For that access method, the timeout= is just for on the initial connection to the workspace server, so no, that wouldn't affect this case. For IOM, neither the saspy python code, nor the java code have any kind of 'timeout', not that I have implemented. Since it's hitting the issue at one hour, which is, I believe, the default value set in metadata for the workspace server, my 'guess' at the moment is that the actual IOM client code is what is disconnecting at that time limit, or something in that realm.
Do you know if this is set to 60 min for your server?

Sorry, typed this in but was on another call. more to come...

**Comment by tomweber-sas** [comment]
No problem about not posting extra stuff here. If needed, you can email directly to me, but I don't have to have anything at the moment.

**Comment by tomweber-sas** [comment]
https://go.documentation.sas.com/api/docsets/biasag/9.4/content/biasag.pdf  at the bottom of page 115 is where it shows the IOM timeout setting in metadata that I was referencing.

I think that's what is happening here, though again, I can't swear to that yet, but it's most likely,

The timeout= in saspy is in min, but only for the initial connection (if that were to take long for some reason). The timeout for IOM in the doc above, in metadata, is also in min and that's one I think is set to 60 and causing this.

Can you look and see what the metadata is set to? And I'll try to confirm that would cause this?

Thanks,
Tom

**Comment by vmoulds01** [comment]
Ok that is great to know about the direct emails if needed.

Yea i will take a look at that metadata and see if i can find the timeout and hopefully will be a step closer in getting to root cause of this issue.

I'll keep you posted on what i find here.

Thanks 

Vicky

**Comment by vmoulds01** [comment]
Hi Tom,

So following steps in Force Servers to Disconnect Idle Clients on page 115 of that document i am able to see that the idle timeout setting is 0.

I don't know if that is helpful as if i am understanding your comment above then this setting should be 60 if it's the culprit of the timeout.  

Let me know if you need me to find out anything else.

Thanks

Vicky

**Comment by tomweber-sas** [comment]
No, I'm just guessing at that being the problem, so even if you saw 60, I wouldn't yet be able to say that was the problem. So it's set to 0 and you're sure it's the workspace server of the app server you're connecting to? Just double checking. I'll have to get up with the IOM guys and run this by them to see why this could happen. I just looked through my java code, and I didn't see anything that could account for this (as expected). And, I have no timeouts in my python code either for this. So I'll try to dig here some next.

Tom

**Comment by tomweber-sas** [comment]
Hey Vicky, would you have time for a Web-ex to take a peek at what you are running and see if there's anything on your side that might be helpful? I can set that up, I do that a lot.
Thanks,
Tom

**Comment by vmoulds01** [comment]
Hi Tom,

We have been looking on our side and are currently checking the firewall settings.  

We did check earlier if the issue was being caused by the 60minute reconnect timeout setting for the SAS workspace. We weren’t sure if that was related but thought we would tried changing that just to check. However, it didn’t fix the issue. 

I’ll keep you posted how the firewall checks go tomorrow and if we find anything to see if we need the webex meeting. 

Thanks 

Vicky

**Comment by tomweber-sas** [comment]
That's cool, just let me know. One thing that is worth asking, instead of me assuming the only difference is duration, is what code is being submitted. If you're submitting the same code, but perhaps processing a subset of the data which takes less than an hour, and all the data takes more than an hour, then what we're looking for is what we're thinking. The other case I want to see about is if it's different code and it's something in the code that is cause the hang/timeout. 
For instance, redirecting the log output (proc printto) can cause saspy to 'not come back', as saspy expects to get information from the log for different reasons, one of which is to tell that whatever code was submitted has actually completed and that all  output has bee acquired. So, I'd be curious what code is being run when the problem occurs. WFIW, I do have an option to address proc printto, so that it can be submitted and won't cause a hang. But, that's just one example of a coding reason it could hang as opposed to an IOM protocol reason or something else that could cause what you are seeing.
Thanks,
Tom

**Comment by vmoulds01** [comment]
Hi Tom,

We have been testing a lot in the last 24 hours to try and root cause this. 

We decided to write some test SAS code so that we could test the timeout more and we uncovered something interesting but it doesn't help us solve the problem.  

Earlier, in the week we were seeing the python script I was running be successful if the sas code took less than 1hr and then it seemed to fail if it took more than 1hr.  So, we thought there was a timeout issue and had concentrated our efforts on that.

When looking at the SAS code logs we see that all our SAS code completes successfully on the SAS server.  However, when the python process hangs we see the following message in the SAS server logs:

MLOGIC Ending execution.

;*';*";*/;
ods html5 (id=saspy_internal) close;ods listing;

A connection reset indicates the peer has closed their connection to this session.  This session will remove the peer from its set of active peers.
The Bridge Protocol Engine Socket Access Method was unable to read peer data.

Yesterday we wrote some test sas code that i've put at the bottom of this message where we forced the SAS process to sleep for X minutes and then run a simple SAS query to the SASHELP.cars table.  The purpose of the sleep was to test the timeout theory and see if we could narrow down what was causing that.

However, what we found was that if we put a sleep time of 90 minutes and ran the saspy sas.submit() for that code it completed successfully.  Then we ran the same code with the same sleep time of 90 minutes for a second time and it hung at the sas.submit() method and we didn't see the logging statements printed out after.  When we checked the SAS server logs we saw the error message shown above.  So, the problem is intermittent and doesn't seem to be related to execution time of the sas code.

Just to recap when we see the connection reset message in the SAS server logs we are not seeing anything happen in the python script.  We don't see the python script fail, we don't get any error messages printed out, the process just looks to hang as it never moves onto the print statements after the sas.submit() method call.

We are connecting from same destination server to same SAS server on each run of the SAS code so it doesn't point to a configuration issue with saspy_config else we would expect it to fail all the time.

Network is still being investigated at this point in time to see if it can tell us anything but again given the intermittent issue it's hard to narrow it down.

Any thoughts you have or insights on where else to check would be greatly appreciated.

Thanks

Vicky 



Test Python Code:

sas = saspy.SASsession(cfgname=cfgname,
                                   appserver=appserver,
                                   omruser=str(username),
                                   omrpw=str(password))

start = time.time()
sas_results = sas.submit("""
data _null_;
/* argument to sleep must be expressed in millisecond e.g. 2700000 is 45 mins*/
slept= sleep({3900000});
run;

proc sort data=sashelp.cars out=WORK.cars;
where upcase(type) ne 'HYBRID';
by origin type;
run;
''"")
end = time.time()
print("Running sas code took  = {0:.2f} seconds".format(end - start))
print(sas_results['LOG'])
sas.endsas()

**Comment by tomweber-sas** [comment]
Great job of sleuthing there! Yes, that answers a lot of questions I have. So, the code above has nothing to cause an issue (like proc printto could) like this with the saspy (java iom client) hanging or loosing the connection. So that eliminates a lot of those loose ends. 

That made me wonder if the saspyiom.jar file could possibly be out of synch with the rest of the saspy version you are using. That has happend to others in the past where they copied that jar out of the repository and had it (from that other location) in the class path, then updated saspy (with a newer version of the jar), and so weren't using the right jar. That's worth checking, but I don't thing that is the problem here.

I saw the 'MLOGIC Ending execution.' in the log message and, as I don't submit that option, wondered if that could cause something strange regarding the log output that could trip up my code that needs to get info out of the log. Here's the fdoc to that: https://go.documentation.sas.com/?docsetId=mcrolref&docsetTarget=n0xmqcv92coq2tn1k0z0q6fl2dew.htm&docsetVersion=9.4&locale=en But, again, I don't think that's the problem here either.

Sorry for the goose chase here, want to write down my train of thought so it's here if I need to go back :)

So, I think the error message you have in the log is the smoking gun in this case, but there's no fingerprints on it.
```
A connection reset indicates the peer has closed their connection to this session. This session will remove the peer from its set of active peers.
The Bridge Protocol Engine Socket Access Method was unable to read peer data.
```
What I mean by that is that's what disconnected saspy/java iom client from the workspace server, and seems to be causing saspy to 'hang' but I don't yet know what, specifically, caused that. A socket timeout is what jumps to mind, and there are sockets between both java and workspace, as well a saspy and java. So, I have to figure out what's cause, and what's effect. That error and it disconnecting is the effect, but I don't have the cause pinpointed. 

I'm gonna look at the code and see what I can come up with, and hopefully figure out a way test test out/verify what I come up with. Also, I'll try your same code here to see if I can reproduce it; if I can that will be great. 

Can you tell me what versions of both SAS and saspy you have? 

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Hey, can I see your config def too, cfgname=cfgname and show me the output of submitting your SASsession object: you can email that to me if you don't want to post it, no problem. That'll have the versions and other info I need.

**Comment by tomweber-sas** [comment]
I'm giving your test case a go, but gotta wait for a while to see what happens. Looking at the code, the first thing I see that could cause a socket timeout is in the java client trying to get ODS output. So, I have simple test case to see if that's the cause. Can you give your test case another go with the following change. Instead of having the results be HTML, have them be TEXT, and that should eliminate this, or hopefully show that this is the problem - if it runs this way w/out problem.

So, just set results to text, can be on the submit, or on the SASsesison. Let's set it on the session so it's global, just to see. I show in on both below. that's fine too; redundant.
```
sas = saspy.SASsession(cfgname=cfgname, results='text',
appserver=appserver,
omruser=str(username),
omrpw=str(password))

start = time.time()
sas_results = sas.submit("""
data null;
/* argument to sleep must be expressed in millisecond e.g. 2700000 is 45 mins*/
slept= sleep({3900000});
run;

proc sort data=sashelp.cars out=WORK.cars;
where upcase(type) ne 'HYBRID';
by origin type;
run;
''"", results='text')
end = time.time()
print("Running sas code took = {0:.2f} seconds".format(end - start))
print(sas_results['LOG'])
sas.endsas()
```
Can you try this and see if it works w/out the hang or not, or shows some other issue? I'll try too, but as it takes so long, I've yet to see if I even can reproduce it, as of yet.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey Vicky,
I wasn't able to reproduce this here, so I couldn't verify if the problem went away w/ results='text'; if it was or wasn't that socket timing out that was causing this. Were you able to try that, and/or have you gotten any other info or diagnostics?
Thanks!
Tom

**Comment by vmoulds01** [comment]
Hi Tom,

Sorry for not responding before now.

I am actually off on holiday this week visiting family and don’t have my laptop with me.  

I’ll be back at work next week and can give those things a test then. 

Thanks for all your help and digging into this! 

Vicky

**Comment by tomweber-sas** [comment]
No problem, enjoy your vacation!

**Comment by vmoulds01** [comment]
Hi Tom,

We tried with the results = 'text' and we are still seeing the intermittent issue happen.

We have been able to run successfully with a sleep of 90 minutes and then next time we run with a sleep of 65 minutes it fails.  We still have our network team checking what is happening on the network side of things for successful versus unsuccessful run to see if that gives us a clue as to what is going on.  

I'll keep you posted on what we find.

I don't think this is a SASPY issue given that you aren't able to recreate the problem and with the new knowledge of the intermittent nature of the problem.  Initially, we had thought it was related to a timeout setting but given we managed a successful run of the code with a sleep of 90mins this rules out the 60minute timeout we initially thought was the problem.

Thanks

Vicky

**Comment by tomweber-sas** [comment]
Thanks Vicky, at least that rules out the one 'socket' I'm waiting on to get any ODS output. It seems the other sockets that IOM itself is using to communicate between client and server are what the error is indicating. Also, as that message is in the SAS log from the workspace server (that right ?), it would imply that the (or one of the; I don't know how many IOM uses) socket on the client side (java process) closed, as the message is from the server side.

I've been searching on this error and find many similar, but not the same hits on out tech support site. Then I found an issue on our communities site which has the same error messages in one of the log files:
```
2019-08-15T04:36:18,274 INFO [00590574] 1161165:sas - A connection reset indicates the peer has closed their connection to this session. This session will remove the peer from its set of active peers.
2019-08-15T04:36:18,274 INFO [00590574] 1161165:sas - The Bridge Protocol Engine Socket Access Method was unable to read peer data.
```
https://communities.sas.com/t5/Administration-and-Deployment/SAS-MC-An-existing-connection-was-forcibly-closed-by-remote-host/td-p/581563
This issue was with the metadata server, but it's still all IOM between all the servers. I think it would be good to get up with Tech Support for this problem, as they may very well know the right diagnostics to use to determine the cause of this. I would reffer then to this issue when opening a ticket, so they can also get up with me if they need info about anything on my side.

Is opening a Tech Support ticket for this something you can do. I think that will get us farther, quicker. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Hey Vicky,

Just touching base; been busy on other saspy issues and other things here. I reached out to TS to see what they knew about this; cuz I figured they've seen it before and sure enough, the first thought was a firewall inactivity timeout, being the culprit. Clearly, can't be sure, but they have a solution for that problem, so we can try that out to see if it solves this. There's a 'keepalive=seconds'  setting you can configure on your workspace servers. I've attached a link to that doc and a pic where this is set in OMR (via SMC). You could set it to 30 min (30*60) so it's just a ping every 30 min to reset the timeout, if it's a 60 min or so network timeout that's getting you. Is this something you can try - first even see if you have this configured at all too.

https://go.documentation.sas.com/?docsetId=biasag&docsetTarget=n16001intelplatform00srvradm.htm&docsetVersion=9.4&locale=en#n16030intelplatform00srvradm

![image](https://user-images.githubusercontent.com/17710182/90556271-a044d200-e166-11ea-8850-3eb40affe4ed.png)

Hopefully, this is what's biting you and this will solve it! If not, at least we can see and go from there. 

Thanks,
Tom

**Comment by vmoulds01** [comment]
Hi Tom,

Thanks for checking back in.

I’d spent a week trying to debug that issue and then had to park the problem as had other things to get done. 

I was just back to looking into it again this week so this comment is perfect timing.  I’ll give that setting a check to see if that could help with this problem. 

We still haven’t been able to point what the root cause of the issue is due to its intermittent nature.  

Thanks for your continued advice and support on this problem.

Vicky

**Comment by tomweber-sas** [comment]
Cool, hope this proves to be the problem, and answer. Yes, the other thing I was told was that basically any actual error or whatever, would end up as 'A connection reset' in terms of the message in the log; so it's hard to tell the root cause from that. But, FWIW, this seems pretty plausible. So, fingers crossed for now :)
Tom

**Comment by tomweber-sas** [comment]
Hey Vicky, any updates? Anything I can do?

**Comment by vmoulds01** [comment]
Hi Tom,

Sorry I’ve not replied in a while. I’ve actually just left the project now that was using this. We ended up pivoting to using a different database source and pyspark as we didn’t resolve the SAS issues unfortunately. 

We didn’t have much time and ended up being easier to use a different data source for the data we needed.

Thanks for all your help on this though it was really appreciated! 

I can close this ticket now. 

Thanks

Vicky

**Comment by tomweber-sas** [comment]
Hey Vicky, thanks for letting me know. Sorry to hear that, but I understand. Was hoping it was what tech support had said, as they said that was a common problem. Wish it had been something in saspy as I could have just fixed it for you 😎
