### ISSUE TITLE
SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

### ISSUE THREAD

**Issue by ClientSpec-CEO** [sassoftware/saspy#309]
I am having the error below. I have tried some of the suggestions from previous users,.But I am not so good at using it to resolve mine. I only know how to programme in SAS :(
I was following the tutorial step by step ..SAS Tutorial | Using SAS in Python Applications With SASPy and Open Source Toolshttps://www.youtube.com/watch?v=YL8xV0AOcMc&t=185s

Using SAS Config named: default
---------------------------------------------------------------------------
SASIONotSupportedError                    Traceback (most recent call last)
<ipython-input-12-1b26ae88434c> in <module>
      2 saspy
      3 saspy.SAScfg
----> 4 sas = saspy.SASsession()

~\anaconda3\lib\site-packages\saspy\sasbase.py in __init__(self, **kwargs)
    442                 self._io = SASsessionSTDIO(sascfgname=self.sascfg.name, sb=self, **kwargs)
    443             else:
--> 444                 raise SASIONotSupportedError(self.sascfg.mode, alts=['IOM'])
    445         elif self.sascfg.mode == 'IOM':
    446             self._io = SASsessionIOM(sascfgname=self.sascfg.name, sb=self, **kwargs)

SASIONotSupportedError: Cannot use STDIO I/O module on Windows. Try the following: IOM

**Comment by tomweber-sas** [comment]
Hey, I can help you with that. I hadn't seen that video, just starting to watch it now; cool :)
But, have you looked at the actual instruction? https://sassoftware.github.io/saspy/install.html#configuration
It appears from the error above, that you are running on a windows machine. I don't see the output from the
saspy.SAScfg statement, but I suspect it's something along the lines of  ~\anaconda3\lib\site-packages\saspy\sascfg.py,
is that true?
SAS can be installed/deployed in a number of different ways, and so saspy has a number of different ways to be able to interface to those various deployments. Because of that, you have to provide a little configuration information so I know what kind of SAS and how to get at it.
So, first, where is the SAS that you are trying to connect to? On the same windows box that you are running python on? Or maybe it's a Workspace server running in some deployment, like what you would connect SAS/EG to?
Since your client is windows, and I suspect you're on SAS 9, not Viya, you need to use the IOM access method. This works for both a local SAS install and a remote Workspace server. You need to have Java available on your machine, and then you just need to configure a config file with a little information.

Can you tell me where SAS is that you're trying to connect to? Then I can provide you with what you need for your configuration.
Thanks,
Tom

**Comment by ClientSpec-CEO** [comment]
wow.. thanks for your reply. while I was looking away..
The SAS is located in my oracle VM. It's a learning edition downloaded following this instruction here https://www.sas.com/en_us/software/university-edition/download-software.html

**Comment by tomweber-sas** [comment]
haha. Ok, so UE. So, UE is a self contained environment, which actually has Jupyter, python and saspy already installed and configured in it. You can't get to that SAS from external python on your own windows box.
So, since you have that VM running, just bring up a browser and go to 
http://localhost:10080   I think that's it, I'll post if that's wrong; it's displayed in the VM window that comes up when you start it.
from there, choose jupyter instead of studio.

**Comment by tomweber-sas** [comment]
Hey, I had the url right :)

**Comment by ClientSpec-CEO** [comment]
Yes you got it . OK ,I will give this a go then ......I understand what you are saying  now and I will get back to you

**Comment by ClientSpec-CEO** [comment]
Yes!!!!!!!!!. I got it ...Thank you so so much 
![Capture2](https://user-images.githubusercontent.com/62108124/88297616-04a37b80-ccf8-11ea-9e1e-827540caef9d.PNG)

**Comment by tomweber-sas** [comment]
Cool, I see you're just trying to do what you're seeing in the video; got it now. So, one thing I'll tell you is that the version of saspy that is in whatever version of UR you have, is bound to be old. You can actually upgrade saspy to the latest version inside your UR, and I would suggest doing that. The instructions to do this are in #307 
Basically, if you submit this in the notebook before you get started, it'll update saspy to the latest:
```
! pip install saspy==3.3.7 --user
```

**Comment by tomweber-sas** [comment]
Yes, there you go!
And, since saspy is preconfigured, all you need to do to start is submit
```
import saspy
sas = saspy.SASsession()
sas
```
and then you're good to go (but get the latest saspy first :)

**Comment by ClientSpec-CEO** [comment]
Yes, you are right > i am trying to replicate the steps in the video before I suggest SASPy at work . Great information !! I will do the updates as well

**Comment by ClientSpec-CEO** [comment]
Just a quick silly  question?
if the UE is a closed system. It has saspy in it already, and  I can use  it from the jupyter notebook that is in it. And you mentioned that there is  not a way to use an external python to interface directly to the SAS that is inside UE.

where will i update SASPy the ! pip install saspy==3.3.7

**Comment by tomweber-sas** [comment]
Cool! I'm most of the way through the video. The guys are doing a good job with this intro! 
One thing you might find nice is something that probably wasn't in saspy when they created this, is an enhanced set of submit methods, which make seeing the LOG or LST from what you submit much easier to use.  submitLOG() and submitLST(). See the doc on these here: just scroll down to these - they just display the output for you so you don't have to do that yourself after.
https://sassoftware.github.io/saspy/api.html
Sorry the individual methods aren't indexed, this part is autogenerated. But here's the two from that doc:
```
submitLOG(code, results: str = '', prompt: dict = None, printto=False)
This method is a convenience wrapper around the submit() method. It executes the submit then prints the LOG that was returned.

submitLST(code, results: str = '', prompt: dict = None, method: str = None, printto=False)
This method is a convenience wrapper around the submit() method. It executes the submit then renders the LST that was returned, as either HTML or TEXT, depending upon results. The method= parameter allows you to adjust what gets returned to suit your needs.

listonly - this is the default, and returns the LST (will be empty if no output was produced by what you submitted)
listorlog - this returns the LST, unless it’s empty, then it returns the LOG instead (one or the other). Useful in case there’s an ERROR.
listandlog - as you might guess, this returns both. The LST followed by the LOG
logandlist - as you might guess, this returns both. The LOG followed by the LST
``` 

Let me know if you need anything else or have any other questions!
Tom

**Comment by tomweber-sas** [comment]
@ClientSpec-CEO I'm going through old, idle issues, and looking to close them if there's nothing left. I see I didn't answer that last question; sorry I missed that, hope you figured it out. that was to update the version of saspy in UE, so you ran that in a notebook cell in UE. 
Is there anything else you need with this? Can we close this?
Thanks!
Tom

**Comment by tomweber-sas** [comment]
Closing this one. I thing you were good to go. If you need anything else, just open another ticket! Happy to help,
Thanks,
Tom
