### ISSUE TITLE
looking info about python to install in the SAS server 

### ISSUE THREAD

**Issue by bikashten** [sassoftware/saspy#312]
@tomweber-sas I am currently using SASPY to communicate between the SAS and python. My python and python IDE are installed in my local machine and 'p10sas01.rbcint.com' is only the host server for our team.
 SAS_config_names = ['xxxx']
xxxx     = {'java'      : 'java',   # or the full path to java.exe if you don't have the path to it in your PATH environment variable
            'iomhost'   : 'p10sas01.rbcint.com',
            'iomport'   : 8591,
            'sspi'      : True,
            } 

We are trying to install python and IDE in the SAS host server so that everyone can use them. Is it possible to install the python and python IDE in the p10sas01.rbcint.com server? If possible, please, let me know the illustration. If it is not possible, is it possible to use SASPY to access the big data file from the SAS server? 

Thank you,
Bikash

**Comment by tomweber-sas** [comment]
Hey @bikashten , well each of the things you ask can be done. You can install python on any machine. looking back at your previous issue, it seems the IDE you mention is spyder? So, that's anaaconda, and sure, can run on your SAS server machine (that's a windows box I think?). You can move data between SAS and python using saspy, either direction, so again that answer is yes. But all of this begs the question of why, and what are you actually trying to do?

If you install python and the UI to use on the SAS server machine, then everyone trying to use it has to log on to that machine, right? Remote desptop, since it's windows. Is that really what you want, and why? Python is a 'client' software, so why wouldn't whoever wants to use it just have it on their own machine? saspy will connect to the workspace server the same from either location. 

You ask about big data. What are you imagining you will be doing? saspy interacts w/ SAS, and the big data SAS can access, is accessed by SAS and is processed by SAS. You can see results in saspy from the SAS processing of the data. That's would be the 'normal' way you would use saspy to access SAS and have it process 'big data'. But are you asking about moving the data from SAS in to Python? Again, yes you can do that. Is that what you're trying to do? And why? Can your python process really handle that data? 

Any of this is do'able. But it depends on what you're trying to accomplish.

**Comment by bikashten** [comment]
@tomweber-sas Thank you for a quick reply. Our team was thinking to install the python on the SAS server machine like SAS EG installed in our server so that it is centralized to use them via user id and password. Since Python is a client based software, I think SASPY is better option for us to communicate between SAS server and python installed in the local machine. Thank you for your time and consideration. 

Regards,
Bikash

**Comment by tomweber-sas** [comment]
Sure thing. But EG is a client side thing too. Though, I guess you may need to pay for each client? I don't know the licensing, so who knows, but it's just a client too that remotely connects to a workspace server. saspy, obviously if free, so that' snot a concern, if it is w/ other clients. So, yes you can do it any way you like, but it does make sense to me that anyone just have it on their own machine.

**Comment by tomweber-sas** [comment]
sounds like you've got things under control. Is there anything else you need with this, or can we close this issue?
Thanks!
Tom

**Comment by bikashten** [comment]
@tomweber-sas Yes, I got it. Thank you Tom for your help.

Regards,
Bikash
