### ISSUE TITLE
sas.submit to pandas DataFrame

### ISSUE THREAD

**Issue by rdemarqui** [sassoftware/saspy#327]
Hello!

I've been trying to transform SAS data into a pandas DataFrame.

Firstly I used the command sas.sd2df(), but it was pretty slow, even for small data. It took almost 15 minutes for a simple dataset with 85 rows × 5 columns.
Example:
sas2df = sas.sd2df(table='new_table', libref='work')

My second try was a workaround, where I did the steps below: 
  - Got the results with:
	result_html = sas.submit('''
			PROC PRINT DATA=WORK.new_table;
			RUN;
			''', results='HTML');
  - Transformed it in pd.DataFrame using pd.read_html(result_html['LST']).

Using results='HTML' works perfectly (2 sec for the same dataset) with pd.read_html(result_html['LST']), but I'm looking for the same result using results='PANDAS or TEXT' on sas.submit because it brings a smaller and cleaner raw data.

Is there a way to transform the result of command sas.submit(... , results='PANDAS or TEXT') in to a Pandas DataFrame?

I'm using saspy 3.5.3 version.

Thanks!

**Comment by tomweber-sas** [comment]
Hey, I can help you with that. Yes, sd2df is the right way to do this. Something seems wrong if that took 15 minutes. Can you run the following so I can see what is going on? And, what's your configurations definition? 
```
sas
sd = sas.sasdata(table='new_table', libref='work', results = 'text')
sd.contents()
```
Thanks!
Tom

**Comment by rdemarqui** [comment]
Hi.
Above the command response: 
![image](https://user-images.githubusercontent.com/21056133/95899299-bc2fb300-0d66-11eb-96f9-3ff10bdb51d3.png)

I just omitted Filename path and Owner Name.

About configurations definition, what exactly do you need? I'm using iomcom connection.

Thank you!

**Comment by tomweber-sas** [comment]
Hey, ok, so that's really a small table. So, I wanted to see your saspy configurations. If you has submitted your SASsession object, sas, I could tell a number of things about what was going on. But you are saying you're using the COM access method? I could see that for sure if I had output. Is this a local or remote SAS that you are connecting to? Where are you connecting from? Though, I guess I can deduce that if you are using COM, as it means you're on windows, and given the file paths in the contents output, SAS is on linux, so you're remote from windows. Again, this would be clear if I had the output of the code.
I can't imagine it taking 15 minutes to transfer that data. But, the COM access method is a user written access method I can't fully support, as opposed to the three I wrote and do fully support. Can you try the IOM access method? sd2df should take less than a second for that to create a df from that little table. I haven't seen COM be that slow before though, that's really slow.

**Comment by rdemarqui** [comment]
Hello.
I'm connecting to a remote SAS, using windows10 and SAS EG 7.1.
Which command I execute to see saspy configurations?
It's possible to connect IOM access method using windows on remotes SAS?

Thanks!

**Comment by tomweber-sas** [comment]
Yes, @rdemarqui  you can connect to the same workspace server definition that EG connects to using IOM. You just need java on your client machine, which you probably already have. So, the configuration is what you put in the sascfg_personal.py, based upon the instructions: https://sassoftware.github.io/saspy/install.html#sascfg-personal-py, but instead of using the configuration definition for COM (https://sassoftware.github.io/saspy/install.html#iom-using-com), use the IOM Remote version instead: (https://sassoftware.github.io/saspy/install.html#iom-using-java, https://sassoftware.github.io/saspy/install.html#remote).

So your config may look something like this:

```
com      = {'provider'  : 'sas.iomprovider',
            'iomhost'   : 'xyz.abc.iom.com',
            'iomport'   : 8591,
            'authkey'   : 'mycreds'
            }
```
And you would follow the instructions and would have something more like this:

```
iom   =    {'java'      : 'java',
            'iomhost'   : 'xyz.abc.iom.com',
            'iomport'   : 8591,
            'authkey'   : 'mycreds',
            #'appserver' : 'SASApp - Workspace Server'   # if needed if multiple servers
            }
```
This should get you connected and should allow the sd2df methods to work as you would expect.
Thanks,
Tom

**Comment by rdemarqui** [comment]
Hello Tom.
Thanks for helping me. I gonna try your suggestion. If I have another problem, I will open another task.

Thank you!
