### ISSUE TITLE
head method does not work for sasdata when table is from SPDE Engine 

### ISSUE THREAD

**Issue by michaelbestlinkit** [sassoftware/saspy#329]
Describe the bug

I am using saspy to pull data from SAS and converting the resulting pandas data frame to parquet.
SASPy has a method to show the first rows, `sas_data.head()`.
If I want to limit the number of rows in the table, I can use a depots dictionary to limit the number of lines in the table, an example of such a dictionary for the SPDE Engine would be: 
```
dsopts = {'startobs': 1, 'endobs': 100000}
```

When the table belongs to the BASE engine, I can run the `head()` method  after applying the dspots when pulling the table.
However, when doing the same for the SPDE Engine, I get the following error:

```
sas_results.head()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/dist-packages/saspy/sasdata.py", line 218, in head
    df   = self._returnPD(code, '_head')
  File "/usr/local/lib/python3.8/dist-packages/saspy/sasdata.py", line 164, in _returnPD
    raise ValueError("Internal code execution failed: " + errorMsg)
ValueError: Internal code execution failed: ERROR: The option OBS= cannot be used with the SPD Engine-only options STARTOBS= or ENDOBS= for file 
```

This error does not occur if I do not use the dspots for the SPDE Engine, which does not seem like the behaviour you would expect.

To Reproduce
This is what I'm doing in python3.8.0.
sas is my SAS session. I have kept out names and the dspopts dictionary, but this just filters some of the columns in these tables.

```
sas.saslib(libref=spde_df_libref,
           engine="SPDE",
           options="ACCESS=READONLY",
           path=spde_df_sas_path)
sas.sasdata(table=spde_df_table,
            libref=spde_df_libref)
dsopts = {'startobs': 1, 'endobs': 100000}
sas_result = sas.sasdata(table=spde_df_table,
                         libref=spde_df_libref,
                         dsopts=dsopts)
sas_result
sas_result.head() # this results in error
```

Without the dsopts it is fine.
```
sas.saslib(libref=spde_df_libref,
           engine="SPDE",
           options="ACCESS=READONLY",
           path=spde_df_sas_path)
sas.sasdata(table=spde_df_table,
            libref=spde_df_libref)
sas_result = sas.sasdata(table=spde_df_table,
                         libref=spde_df_libref)
sas_result
sas_result.head() # this does not result in the error
```

Expected behavior

I would expect that limiting the number of rows that I pull from the SAS table would not result in an error. Furthermore, I'm providing the startobs and endobs, which are specific to SPDE, so the error message does not seem like it communicates correctly what is happening.

Desktop (please complete the following information):

OS: Ubuntu 18.04
Access Method = IOM
SAS Config name = iomwin
SAS Config file = .config/saspy/sascfg_personal.py
SAS Version = 9.04.01M1P12042013
SASPy Version = 3.5.3
Teach me SAS = False
Batch = False
Results = Pandas
SAS Session Encoding = wlatin1
Python Encoding value = windows-1252

Let me know what else I can provide to help fixing this problem.

**Comment by tomweber-sas** [comment]
Yes, this is just another case of the SPDE engine not honoring the common options all SAS engines support: firstobs= and obs= ( which is really 'lastobs' not 'number of obs').  It made up it's own option names for this; startobs= and endobs=. So I'll have to go make SPDE specific changes throughout saspy to account for this incompatibility bug in that engine, as, even if I got them to fix this in the engine, you'd not get that till who knows when, if ever. 

I won't be able to give you the same day fix for this case though, like the other issue. I'll have to go through all of the methods and the dsopts code and special case who know how much code to account for this. I'll have to research all the cases for this too, to be sure I'm accounting for everything. If head() is broke, then so is tail(), not to mention the dsopts code to generate dataset options, which can be invoked on every method there is; so it's pretty pervasive.

Regardless, I'll get this accounted for ASAP and let you know when it's there to try out. Sorry about that. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
So, good news, bad news on this, well sorta (for me, not you) :)   This is not as pervasive as I was thinking. The dsopts code uses what you have set in there, and that is fine for the general case with all the various methods (if you don't use options the engine doesn't support). So it's only the cases where I'm trying to override, or otherwise augment these options having to do with obs, where the spde engine doesn't work right. So, that's good.

But, I have to actually know it's the spde engine, so I've added a query to determine that, at SASdata creation time. head() and tail() are the two cases left where I'm manipulating the obs options, so I need to handle this in those methods. I've also observed that spde doesn't actually honor it's options with some proc sql query (used in tail()), which I then still need to deal with differently to get these methods to actually behave correctly with this engine. Another inconsistency is that if neither startobs nor endobs are used, then obs= works, but throws an error if the others are set, and fistobs= fails regardless, even when obs= works. 

So, I'm working on all of that now. I have it all working, except for the last bit where getting the correct number of obs when startobs or endobs are set, as the engine doesn't honor those in this case. 

So, just an FYI. I'm hoping to have this pushed for you to try out by the end of the day, assuming I don't run into any other issues with this.

Tom

**Comment by michaelbestlinkit** [comment]
@tomweber-sas Tom, thanks for the update, and thank you for your support. I really appreciate how fast you have gotten on these issues :)

**Comment by tomweber-sas** [comment]
Sure thing! I just pushed the fix for this. It took a while because I also had to fix up some cases where I wasn't completely honoring all of the dsopts (firstob, obs, startobs, endobs) in head and tail. When you have any of these set in your dsopts, then head and tail should be relative to the result set those options would produce. All of that is now working right, and the other incompatibilities w/ spde not always honoring it's own options (sql query) has been addressed too, which was related to that same subsetting logic.

This is at 'main'. Go ahead and try it out and see what you find. It all appears correct to me.

Thanks!
Tom

**Comment by michaelbestlinkit** [comment]
@tomweber-sas 
Hi tom, sorry for not answering sooner, I had some other work and ended up having some other problems that were impeding me from testing your solution. 
I just tested it and it works great! Awesome work, thanks again so much for your fast reply.

Do you know when you will be making a new release with this fix? 

Unless you have any other questions, comments or concerns, feel free to close this issue.

**Comment by tomweber-sas** [comment]
No problem, and, that's great! As for building a new release, I can do that. There are a couple other minor fixes at main currently. I have another enhancement in the works right now which, when finalized, would justify a new release. And, since it's a big change, maybe getting this and the other things out of it's way, so to speak, will be a good thing. I'll see about getting this into a new version today!

**Comment by tomweber-sas** [comment]
V3.5.4 is now available as the current production version. It's in the 'releases' in this repo, and on PyPi, and Conda will build this later today, I expect, as it's an automated process when new versions are created. 
```
pip uninstall -y saspy
pip install saspy
```
will cleanly install this new version from PyPi

I'll go ahead and close this out. Let me know if you need anything else!
Tom
