### ISSUE TITLE
Slow creation of sas7bdate files

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#332]
Hi Tom,

I have a program that uses pandas to loop over some csv files, do some manipulations, checks of the data, and outputs the data to sas7bdat files using saspy.  I loop over a number of .csv files with varying number of records and the process is taking a fair amount of time.  I threw in some time stamps to get time deltas (t1-t0) and found the conversion of the dataframe to a sas dataset (using `df2sd`) to be the bottleneck (see example from one file below).
![image](https://user-images.githubusercontent.com/866921/96647244-281f9780-12e2-11eb-97af-c3d327a159cd.png)

The above df/ds has 92 columns and 46258 observations/rows.  I am also applying formats and labels when creating the dataset.  

Any ideas how I could speed this up?  I was thinking I could thread the write process, but I am wondering if you have an 'easier' solution.   Not sure if there is a way to 'open the pipe' to let data flow better to the sas kernel.  In general the files are not too large < 100mb.  I know there is a method='DISK' for the sd2df, but I do not see a similar option for df2sd.

I for all the datasets I looked at time vs number of observations and did not see anything too wild as when datasets have more observations.
![image](https://user-images.githubusercontent.com/866921/96647568-c4499e80-12e2-11eb-82f5-1f13354555b6.png)

Note the data types and number of columns varies between each dataset, so it is not a 'clean' comparison between time and obs.

Thanks in advance,
Jeremy

**Comment by tomweber-sas** [comment]
Hey Jeremy! Yes, I've actually been looking at this for another issue. I did some preliminary work, and was just getting back to that today to see if I can finalize it; lots of change, so lots of validation and testing to be done. 
I have a branch called (go figure) 'df2sd' with a number of changes and options (new parameters) to provide some optimizations. It would be great for you to try these out to see how much it can help.

There a a few things that I have to do in df2sd, besides streaming the data to SAS, and these can take more time as the data gets larger. The first thing is that I have to calculate the lengths of all of the char columns. SAS only has CHAR and FLOAT datatypes and the char variables lengths have to be declared up front, as the number of bytes, in the SAS encoding. SAS doesn't support char length, but only byte length. Since dataframes have no metadata (it doesn't have char lengths for any columns), I have to actually calculate the the byte length for each column by scanning all of the data and transcoding it into the SAS encoding to get the maximum length to declare for  the SAS data set, so the data fits. The second thing I have to do is transcode the data from Python's UTF-8 to whatever the SAS session encoding is. There is a third thing that can add a little overhead, which is to handle any embedded newline or carriage return chars in the character columns. Since I'm streaming the data to SAS via STDIN, being directly parsed and written to the data set by the data step, any new line char will be interpreted and the end of that line of data, and would then cause parsing problems. So, I replace any LF/CR on the python side w/ hex 2/3 and swap them back in the datastep, so they can be in the char variables in the data set.

The length calculations and transcoding was being done first in df2sd, and was taking a lot of time, as the data gets larger. I've tried a number of ways to get the max encoded byte lengths and have what performs the best. But, I've also made some optimizations for certain cases to eliminate what overhead I can. Here are the enhancements and new parameters. The default behavior is, of course, what it currently does, so no breaking changes.

1) char_lengths - I've added a BPC (bytes per character) value to my lookup table for all of the SAS encodings. In the cases where BPC is 1 (single byte encodings), I can optimize out the transcoding to bytes of the SAS encoding from the length calculations, and only calculate char length, as chars equal bytes in single byte case. That saves some time. For cases where BPC is greater than 1, you can specify to still only calculate char length, and then just multiply that by BPC (you can also specify your own BPC to use) to get the SAS byte length for the columns. 

2) encode_errors - since I've separated out the transcoding (some times) from the length calculations, now I can support the transcoding a little differently, and this has slightly different requirements depending upon the access method too. The previous code would fail if there were transcoding errors, before even trying to send the data over, as it caught this in the length calculations code. Now, if not caught there (still can be), it can be done when streaming the data. This then allows for the option of failing (at that point, so there may now be a partial dataset), or of replacing invalid chars with the replacement char of the encoding, so all of the the data can be stored in the SAS data set of the SAS encoding (with invalid chars replaced, of course). 

3) embedded_newlines - this options has been here for a while, but if you know you have no LF/CR in your data, you can set it to False, and that will eliminate any overhead of trying to swap any occurrences of these, back and forth. 

This is getting long, so I'll stop here. Can you submit your SASsession object and post that output here? Then I can see which access method you're using, and what encoding you SAS session is in and provide you appropriate option values to try with this new code, to compare timings.

Doc string in the new code (still only at the branch):
```
        :param encode_errors: 'fail', 'replace' or 'ignore' - default is to 'fail', other choice is to 'replace' \
                              invalid chars with the replacement char. 'ignore' doesn't try to transcode in python, so you \
                              get whatever happens in SAS based upon the data you send over (this can vary per access method). 

        :param char_lengths: How to determine (and declare) lengths for CHAR variables in the output SAS data set \
                             SAS declares lengths in bytes, not characters, so multibyte encodings require more bytes per character (BPC)
            .. code-block:: python

                'exact'  - the default if SAS is in a multibyte encoding. calculate the max number of bytes, in SAS encoding, \
                           required for the longest actual value. This is slowest but most accurate. For big data, this can \
                           take excessive time. If SAS is running in a single byte encoding then '1' (see below) is used, not this.

                'safe'   - use char len of the longest values in the column, multiplied by max BPC of the SAS multibyte \
                           encoding. This is much faster, but could declare SAS Char variables longer than absolutely required \
                           for multibyte SAS encodings. If SAS is running in a single byte encoding then '1' (see below) is used. \
                           Norte that SAS has no fixed length multibyte encodings, so BPC is always between 1-2 or 1-4 for these. \
                           ASCII characters hex 00-7F use one btye in all of these, which other characters use more BPC; it's variable
 
                [1|2|3|4]- this is 'safe' except the number (1 or 2 or 3 or 4) is the multiplier to use (BPC) instead of the \
                           default BPC of the SAS session encoding. For SAS single byte encodings, the valuse of 1 is the default \
                           used, since characters can only be 1 byte long so char len == byte len \
                           For UTF-8 SAS session, 4 is the BPC, so if you know you don't have many actual unicode characters \
                           you could specify 2 so the SAS column lengths are only twice the length as the longest value, instead \
                           of 4 times the, which would be much longer than actually needed. Or if you know you have no unicode \
                           chars (all the char data is actual only 1 byte), you could specify 1 since it only requires 1 BPC. 
```

Thanks!
Tom

**Comment by tomweber-sas** [comment]
Hey Jeremy,

I thought that last post was a lot of info to assimilate. I've been working on this for #326 and that's mostly been offline. I've added some info below from an email thread on that. 
So, the jist is that having to calculate the SAS variable lengths from the dataframe data is a big part of the problem. removing the transcoding to SAS encoding to get byte length and just getting char length helps a fair amount, but for big data that is still a lot of overhead. So, along with what I posted previously, which was the first pass at trying to make this better, I also added the ability to just provide a dict with the char columns and the lengths you want me to declare. With that, the entire calculation overhead is gone. I added a new (internal at the moment; starts w/ an underscore) method which can be used to calculate the lengths, with the new options too. So that can be run independently, returning the dict with whichever methods (option settings) you choose. Or you can just create the dict yourself with the lengths you want, and not have to do the calculations. This will eliminate all the overhead. And for jobs where you run df2sd on the same data over and over (production scheduled jobs, ...), you can just hard code this dict and pass it in, never having to do the calculation again.



---------------------------

I’ve made another enhancement to all of this. For data your size, even calculating the string length (then multiplying by BPC to get byte length) as opposed to calculating the exact correct byte length, takes way too long. Especially, in the case where you are running this code over and over.

So, I’ve pulled the code to get the lengths out to it’s own function, and df2sd calls that. That function returns a dict with the char columns and lengths. It works the same as this new code has. But, this now means 2 new things. 

1)	df2sd can now take that dictionary as a value for char_lengths= and it will then skip this whole step and just use the lengths from the dict.
2)	you can skip calling the function and create the dict yourself with lengths you specify (eliminating that code and time altogether) you must provide all of the char columns, with lengths, matching the names to the df.columns output
 
Here’s some examples:
``` 
tom64-5> python3.5
Python 3.5.6 (default, Nov 16 2018, 15:50:39)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-23)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy, time, pandas as pd
>>> sas  = saspy.SASsession(cfgname='iomj'); sas
SAS Connection established. Subprocess id is 13160
 
No encoding value provided. Will try to determine the correct encoding.
Setting encoding to cp1252 based upon the SAS session encoding value of wlatin1.
 
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_work6F0F00007FE3_tom64-5/SAS_workED3800007FE3_tom64-5/
SAS Version           = 9.04.01M4P11092016
SASPy Version         = 3.5.3
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 32739
 
 
>>> # create some data with all char columns for the data frame 
>>> 
>>> cars = sas.sasdata('cars','sashelp')
>>> df = cars.to_df_DISK(dtype=str)
>>> df['Make'][1]="Alice"+'\u20ac\u20ac\u20ac\u20ac\u20ac\u20ac\u20ac\u20ac'
>>> 
>>> df.dtypes
Make           object
Model          object
Type           object
Origin         object
DriveTrain     object
MSRP           object
Invoice        object
EngineSize     object
Cylinders      object
Horsepower     object
MPG_City       object
MPG_Highway    object
Weight         object
Wheelbase      object
Length         object
dtype: object
>>> 
>>> df.head()
            Make           Model   Type Origin DriveTrain   MSRP Invoice EngineSize Cylinders Horsepower MPG_City MPG_Highway Weight Wheelbase Length
0          Acura             MDX    SUV   Asia        All  36945   33337        3.5         6        265       17          23   4451       106    189
1  Alice€€€€€€€€  RSX Type S 2dr  Sedan   Asia      Front  23820   21761          2         4        200       24          31   2778       101    172
2          Acura         TSX 4dr  Sedan   Asia      Front  26990   24647        2.4         4        200       22          29   3230       105    183
3          Acura          TL 4dr  Sedan   Asia      Front  33195   30299        3.2         6        270       20          28   3575       108    186
4          Acura      3.5 RL 4dr  Sedan   Asia      Front  43755   39014        3.5         6        225       18          24   3880       115    197
>>>... for i in range(4):
...    df = df.append(df, ignore_index=True)
...
>>> 
>>> df.shape; df.size
(6848, 15)
102720
>>> 
>>> # call the function to get the lengths back in a dict to pass in
>>> 
>>> d1 = sas._df_col_lengths(df) ; d1
time (in seconds) to calculate column lengths=  0.11144638061523438
{'MPG_Highway': 2, 'Invoice': 6, 'Wheelbase': 3, 'Weight': 4, 'Type': 6, 'DriveTrain': 5, 'Horsepower': 3, 'Origin': 6, 'MPG_City': 2, 'EngineSize': 3, 'Model': 39, 'Make': 13, 'Length': 3, 'MSRP': 6, 'Cylinders': 3}
>>> 
>>> sd = sas.df2sd(df, char_lengths=d1)
>>> sd.columnInfo()
      Member  Num     Variable  Type  Len  Pos
0   WORK._DF    9    Cylinders  Char    3   84
1   WORK._DF    5   DriveTrain  Char    5   64
2   WORK._DF    8   EngineSize  Char    3   81
3   WORK._DF   10   Horsepower  Char    3   87
4   WORK._DF    7      Invoice  Char    6   75
5   WORK._DF   15       Length  Char    3  101
6   WORK._DF   11     MPG_City  Char    2   90
7   WORK._DF   12  MPG_Highway  Char    2   92
8   WORK._DF    6         MSRP  Char    6   69
9   WORK._DF    1         Make  Char   13    0
10  WORK._DF    2        Model  Char   39   13
11  WORK._DF    4       Origin  Char    6   58
12  WORK._DF    3         Type  Char    6   52
13  WORK._DF   13       Weight  Char    4   94
14  WORK._DF   14    Wheelbase  Char    3   98
>>> 
>>> # just define your own lengths and skip all of this time to calculate, all together!
>>> 
>>> d1 = {}
>>> for col in df.columns:
...    d1[col] = 30
...
>>> 
>>> d1
{'MPG_Highway': 30, 'Invoice': 30, 'Wheelbase': 30, 'Weight': 30, 'Type': 30, 'DriveTrain': 30, 'Horsepower': 30, 'Origin': 30, 'MPG_City': 30, 'EngineSize': 30, 'Model': 30, 'Make': 30, 'Length': 30, 'MSRP': 30, 'Cylinders': 30}
>>> 
>>> sd = sas.df2sd(df, char_lengths=d1)
>>> sd.columnInfo()
      Member  Num     Variable  Type  Len  Pos
0   WORK._DF    9    Cylinders  Char   30  240
1   WORK._DF    5   DriveTrain  Char   30  120
2   WORK._DF    8   EngineSize  Char   30  210
3   WORK._DF   10   Horsepower  Char   30  270
4   WORK._DF    7      Invoice  Char   30  180
5   WORK._DF   15       Length  Char   30  420
6   WORK._DF   11     MPG_City  Char   30  300
7   WORK._DF   12  MPG_Highway  Char   30  330
8   WORK._DF    6         MSRP  Char   30  150
9   WORK._DF    1         Make  Char   30    0
10  WORK._DF    2        Model  Char   30   30
11  WORK._DF    4       Origin  Char   30   90
12  WORK._DF    3         Type  Char   30   60
13  WORK._DF   13       Weight  Char   30  360
14  WORK._DF   14    Wheelbase  Char   30  390
>>> 
``` 
So, with this, you can call the function once and save the info, then just create a dict with that output from then on, and use it to call df2sd and never have to waste time recalculating that same info.
Or, if you know how long you need for the columns, just code it yourself and I’ll just use the lengths you provide!
 
That may just be the way for you to deal with data this size.

**Comment by tomweber-sas** [comment]
Ah, STDIO and utf-8. Thanks.

First would be to just run df2sd() with this code, and see how long it takes. Just to compare with what you have today; should be comparable with the default values.

Then try out calling 
d1 = sas._df_col_lengths(df) ; d1
with your df. default parms and see how long that is taking; the code in the branch will print out how many seconds it took. I'll remove that before merging it in.
Then you can call df2sd(df, char_lengths=d1)
and see how long it takes to transfer the data, as it will use the lengths from the dict you passed in and skip doing that itself).
Hopefully, the time the two independent part takes about equals the time from the first, regular, call.

The next thing to time, would be calling  (use 'safe' or 1,2 ,3 ,or 4  - all calculate chars not bytes)
d2= sas._df_col_lengths(df, char_lengths='safe') ; d2
and compare this with the calling it the first time; this will calculate char lengths, not transcoded byte lengths. So, we can see what that saves, time-wise. Though, since the encoding is utf-8, that part is really just converting to bytes, without actually transcoding to bytes of a different encoding, so it will still be quicker, just not as much quicker as not transcoding to bytes of something other than utf-8. Still, it is what it is. 

One other thing to note, if playing around with this is that BPC for utf-8 is 4, which is rarely needed. So, to not have the SAS variables declared longer that necessary, you can specify char_lengths=1 or 2, depending on your data, instead of 'safe' which will use 4 as the multiplier. if all your data is 7bit ascii, then 1 is fine as those are all 1 byte even in utf-8. 2 should be good for most other 'reguilar' (I know that's a stupid term to use), data, if you don't have a lot of 3 or 4 byte chars.  This is just for is you use the char clac instead of the transcoded byte length (char_lengths='exact'). 

Looking forward to what you observer with these changes and your data!
Tom

**Comment by biojerm** [comment]
still looking at the results, but a quick coding suggestion for `_df_col_lengths`

```
for name in df.columns:
    if df[name].kind in ('o','s','u','v'):
       if corb:  # calc max chars not bytes
          col_l = df[name].astype(str).map(len).max() * bpc
       else:
          if encode_errors == 'fail':
             try:
                col_l df[name]].astype(str).apply(lambda x: len(x.encode(self._io.sascfg.encoding))).max()
             except exception as e:
                print("transcoding error encountered.")
                print("dataframe contains characters that can't be transcoded into the sas session encoding.\n"+str(e))
                return none
          else:
             col_l = df[name].astype(str).apply(lambda x: len(x.encode(self._io.sascfg.encoding, errors='replace'))).max()
       if col_l == 0:
          col_l = 8
       ret[name] = col_l
print("time (in seconds) to calculate column lengths= ",  time.time() - starttime)

return ret
```

I basically removed the all the range(len(df.columns)) stuff and looped over the names directly.  I may be missing something (compatibility for example), but it seems a little cleaner.

**Comment by biojerm** [comment]
Hey Tom,

here is some of the data from supplying the `char_lengths='safe'`

/tmp/tmpd_94w0xd/hptn083-2020-08-21T1650/page/page_ae.csv
time (in seconds) to calculate column lengths=  0.5003330707550049
Total time to write sas dataset = 48.195741

/tmp/tmpd_94w0xd/hptn083-2020-08-21T1650/page/page_aeyn.csv
time (in seconds) to calculate column lengths=  0.012648582458496094
Total time to write sas dataset = 1.021371

/tmp/tmpd_94w0xd/hptn083-2020-08-21T1650/page/page_bm.csv
time (in seconds) to calculate column lengths=  0.026406049728393555
Total time to write sas dataset = 2.883634

/tmp/tmpd_94w0xd/hptn083-2020-08-21T1650/page/page_bs.csv
time (in seconds) to calculate column lengths=  0.7809956073760986
Total time to write sas dataset = 50.171936```

**Comment by biojerm** [comment]
here are the data

**Comment by tomweber-sas** [comment]
Thanks Jeremy. It doesn't seem that any of this data is large enough to have the column length calculation even be significant. I'd need to see the different in the following, for page_bs.csv, as it seems to be the longest, That will tell what the difference is in that overhead. But, sine 'safe' (char len) was less than a second, I expect 'exact' (byte len) can't be more than 2 seconds, at most, which isn't the big issue of a 50 second run. 
```
sas._df_col_lengths(df, char_lengths='exact')
sas._df_col_lengths(df, char_lengths='safe')
```
The other issue which started me on this was 150 million rows, 100 column, 140GB data. The time to calculate column lengths was significant for that case. That was also IOM, not STDIO, and I saw yesterday, which running some comparisons that STDIO is taking significantly longer to transfer the data. The code is the same, both on the python side, and the data step (SAS side). So, I'm trying to account for that currently. If I can figure out why that is and address it, then STDIO would have a big boost in the transfer time, which is really the only significant time in these case of yours.

Oh, and yes, that range(len(df.colimns)) deal looks like evolutional decay to me :)   Something that's changed over time, where needing the index number is no longer needed, buy that was never refactored to be 'clean' again. I've made that change, and yes, it works just fine. Thanks.

I have an idea I'm going to try for the data transfer, but I really don't know for a fact why it's slower in STDIO than IOM, so I'm not sure it'll address it. Either way, I'll let you know what I find after seeing what I see. If you want to run the above and see the difference, I'm expecting it to only be a second difference or so. 

Thanks!
Tom

**Comment by biojerm** [comment]
sure let me add in the timing code and post the results a little later.  If you want we can also jump on a call and play around.  I a meetings until 12:15 Pacific Time, but am free after that.

**Comment by biojerm** [comment]
Stupid Question, is choosing STDIO vs IOM is that something I 'chose' or is that part of the SAS configuration?

**Comment by biojerm** [comment]
I added some annotations to the first few 
```
/tmp/tmp4eb4xeri/hptn083-2020-08-21T1650/page/page_ae.csv
Dataset is page_ae with shape (46258, 92) and size in bytes 189200232
time (in seconds) to calculate column lengths=  1.1822693347930908 (exact)
time (in seconds) to calculate column lengths=  1.1819648742675781 (safe)
time (in seconds) to calculate column lengths=  1.1706624031066895 (default of sas2df)
52.755165 (total time to write dataset)
23-Oct-20 11:55:20 INFO The number of records in page_ae match
/tmp/tmp4eb4xeri/hptn083-2020-08-21T1650/page/page_aeyn.csv
Dataset is page_aeyn with shape (4310, 17) and size in bytes 3244282
time (in seconds) to calculate column lengths=  0.02377033233642578 (exact)
time (in seconds) to calculate column lengths=  0.02308797836303711 (safe)
time (in seconds) to calculate column lengths=  0.023308753967285156 (default)
1.116174 (total time)
23-Oct-20 11:55:21 INFO The number of records in page_aeyn match
/tmp/tmp4eb4xeri/hptn083-2020-08-21T1650/page/page_bm.csv
Dataset is page_bm with shape (8830, 22) and size in bytes 7616023
time (in seconds) to calculate column lengths=  0.052137136459350586
time (in seconds) to calculate column lengths=  0.05085325241088867
time (in seconds) to calculate column lengths=  0.05195331573486328
3.047892
/tmp/tmp4eb4xeri/hptn083-2020-08-21T1650/page/page_bs.csv
Dataset is page_bs with shape (105492, 59) and size in bytes 220450220
time (in seconds) to calculate column lengths=  1.6788153648376465
time (in seconds) to calculate column lengths=  1.7120051383972168
time (in seconds) to calculate column lengths=  1.7248468399047852
56.240257
23-Oct-20 11:56:21 INFO The number of records in page_bs match
/tmp/tmp4eb4xeri/hptn083-2020-08-21T1650/page/page_cm.csv
Dataset is page_cm with shape (48557, 66) and size in bytes 154755902
time (in seconds) to calculate column lengths=  1.0574016571044922
time (in seconds) to calculate column lengths=  1.0552213191986084
time (in seconds) to calculate column lengths=  1.0648560523986816
```

**Comment by tomweber-sas** [comment]
Yeah, that's even closer than I expected; effectively no difference; So it's just char len vs. byte len with no actual transcoding being done, as both sides are utf-8; as close to the same as it gets. And there's not enough data to take more than a second or so, so this isn't the problem. 
BUT! I did just finish coding up and testing the rewrite I was mentioning, and it did the trick. I think I know why, but I'd need to dig into it to prove it's what I'm thinking. But, regardless, it seems to have worked around this problem. I haven't fully tested this code yet, but I can push it to the branch so you can try it and see if it makes a difference.

Are you local or remote? STDIO or STDIO over SSH? python and SAS on same machine or not. 

STDIO and IOM (and HTTP) are three different access methods, for use depending upon the SAS deployment. Which accee method is determined by your configuration. https://sassoftware.github.io/saspy/install.html#choosing-an-access-method

I have the code working for a local connection, and trying it out over ssh; I see an issue I need to dig into.

**Comment by biojerm** [comment]
Yeah we have a linux server I SSH into that has SAS installed on it.   The python and SAS are run from the same server though.

**Comment by biojerm** [comment]
Are the changes in the current branch?  I am not seeing anything when I fetch.

**Comment by tomweber-sas** [comment]
I'm still fiddling with it trying to get failure cases working. Hoping to push it so you can just see if it helps in a few ...

**Comment by tomweber-sas** [comment]
ok, just pushed. Give it a whirl!

**Comment by biojerm** [comment]
sweet I will check it out.  Have a good weekend.

**Comment by biojerm** [comment]
I don't know what you did, but 👏 .  SOOOO much faster.  What was a 20 minute process is now ~2.  10X programmer= @tomweber-sas 

```
/tmp/tmp5g_h20fw/hptn083-2020-08-21T1650/page/page_ae.csv
Dataset is page_ae with shape (46258, 92) and size in bytes 189200232
time (in seconds) to calculate column lengths=  1.1496949195861816
time (in seconds) to calculate column lengths=  1.1395726203918457
time (in seconds) to calculate column lengths=  1.1230108737945557
7.32664
/tmp/tmp5g_h20fw/hptn083-2020-08-21T1650/page/page_aeyn.csv
Dataset is page_aeyn with shape (4310, 17) and size in bytes 3244282
time (in seconds) to calculate column lengths=  0.022806644439697266
time (in seconds) to calculate column lengths=  0.022457599639892578
time (in seconds) to calculate column lengths=  0.02248525619506836
0.154146
/tmp/tmp5g_h20fw/hptn083-2020-08-21T1650/page/page_bm.csv
Dataset is page_bm with shape (8830, 22) and size in bytes 7616023
time (in seconds) to calculate column lengths=  0.051480770111083984
time (in seconds) to calculate column lengths=  0.051798105239868164
time (in seconds) to calculate column lengths=  0.05149388313293457
0.350697

/tmp/tmp5g_h20fw/hptn083-2020-08-21T1650/page/page_bs.csv
Dataset is page_bs with shape (105492, 59) and size in bytes 220450220
time (in seconds) to calculate column lengths=  1.7433340549468994
time (in seconds) to calculate column lengths=  1.7108275890350342
time (in seconds) to calculate column lengths=  1.7119989395141602
10.320801
```

**Comment by biojerm** [comment]
Please let me know when these updates are deployed and we can update our package.  Once again Bravo!

**Comment by tomweber-sas** [comment]
Hey, that's great! I expect to get this out this week. It's a LOT of changes and some slight behavior changes, so I need to really validate all of the various code paths and failure cases to make sure I don't miss anything. But, I'm hoping to do all of that this week! I'll keep this open and post to it once I get the new release built!
Thanks again for testing it out for me!
Tom

**Comment by tomweber-sas** [comment]
@biojerm I've built V3.6.0 and it's out on pypi now. I'll close this, and you can
```
pip uninstall -y saspy
pip install saspy
```
to get the new fresh version with all of this in it. BTW, I renamed the _df_col_lengths() method to be df_char_lengths(), so it was public (no leading underscore), and matched the char_lengths= parm of df2sd, which it creates the dictionary for. 
Let me know if you need anything else!

Thanks,
Tom

**Comment by biojerm** [comment]
@tomweber-sas Thanks again, my internal customers are quite excited about the update.  These updates and a few threads are dropping processing time down from ~ 60 min to about ~5-7.

**Comment by tomweber-sas** [comment]
Awesome! I just wish I'd have happened upon this sooner :)

**Comment by biojerm** [comment]
@tomweber-sas 

I am trying to build a conda package with the new version of saspy and getting this error:

[jlabarge@statsrv]$ conda-build saspy
Error: about/license_family 'APACHE' not allowed. Allowed families are AGPL,
Apache, BSD, GPL2, GPL3, LGPL, MIT, Other, PSF, Proprietary, and
Public-Domain.

did you change anything where APACHE might be up-cased, or is this on my end?

**Comment by tomweber-sas** [comment]
Conda hasn't built this release yet; it's on a CI/CD autobot process that runs when it notices I pushed a new version. You can check here (https://github.com/conda-forge/saspy-feedstock) to see when it's been run and finished. I don't use conda to do installs, so, I can only guess that when this says it's done, you would be able to get it with your process? probably. 
You should see a PR before too much longer, then it'll process things, then, might not be till tomorrow, the PR will be merged, and then I guess it's ready to be installed?  You can see pr 44 was 3.5.4, so pr 45 will be this release

**Comment by tomweber-sas** [comment]
oh, sorry. I didn't change anything about any license. Just code changes

**Comment by biojerm** [comment]
yeah I am downloading from pypi and building my own conda package, so that I don't have to wait for anaconda to build the package.  My process is just giving me grief.  If you did not change anything with the license it is probably something on my end.  I will keep digging.  Thanks

**Comment by tomweber-sas** [comment]
yeah, sorry about that, but I don't think it's anything I changed. Nothing about apache jumps out at me.

**Comment by biojerm** [comment]
yeah I am getting the same 'Error' when I try 3.5.3,  so it is clearly on my end.
