### ISSUE TITLE
SASpy 3.6.1 Running forever

### ISSUE THREAD

**Issue by mailbagrahul** [sassoftware/saspy#338]
I tried new version of SASPy 3.6.1 today after tweaking some of the configurations settings but it keeps on running without erroring out but SASPy 3.0.0 works fine. Please assist

SASPy version: 3.6.1
Python 3.7.8 (tags/v3.7.8:4b47a5b6ba, Jun 28 2020, 08:53:46) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession(cfgname='Prod_Sec')

**Comment by tomweber-sas** [comment]
Can you show me your configurations file?

**Comment by mailbagrahul** [comment]
I cannot share it here. I can share it to your official mailbox.

**Comment by tomweber-sas** [comment]
yes, of course, you can email anything to me you can't put on here.
tom.weber@sas.com

**Comment by tomweber-sas** [comment]
To follow up back on here. This is using the IOM access method, and as I was hoping to see, the config file had a classpath coded with an old saspyiom.jar, copied off to the side. So, I expect the problem is the old saspy jar with the new saspy code. The answer is to remove the classpath completely from the config, as it's no longer needed. The jars are included in the saspy repo and saspy builds the classpath based upon those, so that this kind of thing can't happen anymore; old saspy jar with new saspy code.
So, we'll see if this addresses the problem once this change is applied to the config file.

**Comment by mailbagrahul** [comment]
Thanks Tom. I removed the classpath and added encryption supporting files to SASPy repo. It connected without any issues. Thanks for your time.
