### ISSUE TITLE
No way to use settings from server, for example validvarname

### ISSUE THREAD

**Issue by binnisb** [sassoftware/saspy#339]
**Describe the bug**
From saspy I can not specify to follow server settings for e.g. valid variable name. This has caused a conflict between datasets created from Python vs datasets created in SAS. See screenshot

**To Reproduce**
Create a session with IOM profile, hitting this line:
https://github.com/sassoftware/saspy/blob/2758cbaaf9e3cb008b250053849818305734e6a5/saspy/sasioiom.py#L512

which forces `validvarname=any` and `validmemname=extend`

Is there any specific reason for that instead of accepting the server setting? 

**Expected behavior**
Default to accept server settings, or allow one to set these in the `sascfg_personal.py`

**Screenshots**
![image](https://user-images.githubusercontent.com/1642748/98869660-6ee05780-2472-11eb-94ff-3972375d1b82.png)

**Desktop (please complete the following information):**
 - OS: Linux, Windows
 - SAS Version: 9.4
 - SASPy Version: latest

**Comment by binnisb** [comment]
I am sorry, I mixed up `autoexec`, didn't realize it executed SAS code after the session is established. So now I override these options with the server values.

**Comment by tomweber-sas** [comment]
Hey @binnisb, great job using the autoexec key for setting these options as you want, automatically when you establish a session. That's just the kind of thing it's for. 

I did want to answer, or address, the original questions though, about me setting these options as I am. You seem familiar enough with SAS, though many who use saspy really aren't SAS programmers. SAS has so many options, between system options to options on programming statements, that there are thousands of combinations of different behaviors, abilities, constraints, ... to have to work with. One of the goals of saspy, being a purely python interface to SAS, is to try and make all of the usual things someone would do, seamless and not require intricate knowledge of all of these SASisms to be able to work right. I want to get the 90+% cases working without lots of extra parameters and options. I do expose many options through optional parameters on methods, when required, but try to make python things work in SAS as a python programmer would expect. This is rarely clean and easy to accomplish.

For these var and table name options, SAS's rules about valid names is, frankly, archaic. We have a very limited scope of valid names, and when I first created saspy, I immediately started getting issues about this because python allows virtually anything to be a name of a column or table (data frame), So, to get 'normal' python behavior, I had to set these options to the most forgiving, and use the n-literal syntax everywhere, just to get normal python behavior to work as expected.

Hope that all makes sense, and I am glad you were able to get things working as you want them to, even if that isn't the default. Getting the behavior you want, even when having to twist a couple of SAS knobs manually, but still having things work, is still a win when trying to interface to something this this many permutations of behavior!

Let me know if there's anything else!
Thanks,
tom
