### ISSUE TITLE
df_char_length gives length of three when nan is a column value

### ISSUE THREAD

**Issue by biojerm** [sassoftware/saspy#348]
Hey Tom,

I just ran into a minor bug with df_char_lengths

if np.nan is in the data column the minimum length of the column will be three because of the way astype(str) works.  Below is an example of the same code being used in in df_char_lengths.

```In [8]: df = pd.DataFrame({'col1':['', ' ', np.nan]})

In [9]: df['col1'].astype(str).map(len)
Out[9]:
0    0
1    1
2    3
Name: col1, dtype: int64

In [10]: df['col1'].astype(str)[2]
Out[10]: 'nan'
 ````
It seems `astype` turns np.nan values into the string 'nan'

I encountered this the other day when a column had Y/N/nan in the column.  I would have expected to be 1, but the length was actually 3. 

Super minor bug, that will only show up if the max length is less than 3 and col contains nan.  

This SO post suggests filling na with empty sting first.
https://stackoverflow.com/questions/58197097/how-to-count-length-of-missing-values-for-string-variables-as-zero

not sure how badly this would hurt performance.

**Comment by biojerm** [comment]
Another option could be to use the `df[name].str.len().max()` this seems to be robust against np.nan

```
In [12]: df['col1'].str.len()
Out[12]:
0    0.0
1    1.0
2    NaN
Name: col1, dtype: float64

In [13]: df['col1'].str.len().max()
Out[13]: 1.0
```

I found this SO post that also talks about a few different approaches.  https://stackoverflow.com/questions/21295334/find-length-of-longest-string-in-pandas-dataframe-column

One of the suggestions is np.vectorize which might also speed up this step.  I don't have much experience with np.vectorize, so I will hack around for a bit and see if I can't post a 'demo'

**Comment by tomweber-sas** [comment]
Hey Jeremy, can you show me the output from the df_char_lengths() call with this dataframe. I'm a little unclear, as that only tries to get lengths for the char columns, not the numerics. So, I'm not able to replicate this myself so far.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
little trial I was trying:
```
>>> df = pd.DataFrame([1.0,2,None])
>>> df
     0
0  1.0
1  2.0
2  NaN
>>> df.dtypes
0    float64
dtype: object
>>>
>>> sas.df_char_lengths(df)
{}
>>>
>>> df = pd.DataFrame(['1','2',None])
>>> df
      0
0     1
1     2
2  None
>>> df.dtypes
0    object
dtype: object
>>>
>>> sas.df_char_lengths(df)
{'0': 4}
```

**Comment by biojerm** [comment]
Interesting `None` seems to be fine but `np.nan` is being troublesome.

Here is my code
``` 
import saspy
import pandas as pd
import numpy as np

sas = saspy.SASsession(cfgname="sas_u8")

print(sas)

df = pd.DataFrame({"col1": ["Y", "N", ""], "col_with_nan": ["Y", "N", np.nan]})
print(df)
lengths = sas.df_char_lengths(df)
print(lengths)

```

and the output

```
Access Method         = STDIO
SAS Config name       = sas_u8
SAS Config file       = /scratch/jlabarge/saspy_sandbox/sascfg_personal.py
WORK Path             = /tmp/SAS_work264300009EC1_statsrv/
SAS Version           = 9.04.01M2P07232014
SASPy Version         = 3.6.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 40641


  col1 col_with_nan
0    Y            Y
1    N            N
2               NaN
{'col1': 1, 'col_with_nan': 3}
```

For a bit of context on how I found this... I was reading in .csv files using the pandas method `pandas.read_csv`.  The method has default feature where values that look like `NA` in various shapes (eg na, n/a, NA, N/A ect) are substituted for np.nan.  Ended up the customer did not want that substitution because it was altering raw data.  So I turned off that feature and while comparing the outputs we noticed that the column lengths in the sas datasets were different in a filed that had possible options of Y/N/NA.  So when I had the pandas 'NA substitution' behavior active I was producing datasets with a length of 3, because the column had values of Y/N/np.nan after read in.  But when I turned off the NA substitution feature the column had lengths of 2 (because values were Y/N/NA).  

To me the more 'correct' answer for column length of a column with the values of Y/N/np.nan would be 1.


Purely for reference if you would like here is the read_csv docs:
https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.read_csv.html

The attribute of `na_values` spells out the defaults

Here is the list for quick reference
 ```
‘’, ‘#N/A’, ‘#N/A N/A’, ‘#NA’, ‘-1.#IND’, ‘-1.#QNAN’, ‘-NaN’, ‘-nan’, ‘1.#IND’, ‘1.#QNAN’, ‘<NA>’, ‘N/A’, ‘NA’, ‘NULL’, ‘NaN’, ‘n/a’, ‘nan’, ‘null’.
```

**Comment by biojerm** [comment]
My best guess is using the `df[name]astype(str)` turns `np.nan` displayed as (NaN in df) into the string `'nan'` where as `None` seems to remain `None`.

**Comment by tomweber-sas** [comment]
That helps, I couldn't get a NaN in to char column. Now I see how you did it. And, the dtype is object, but that column then has mixed types:
```
>>> df = pd.DataFrame({"col1": ["Y", "N", ""], "col_with_nan": ["Y", "N", np.nan]})
>>> df
  col1 col_with_nan
0    Y            Y
1    N            N
2               NaN
>>> df.dtypes
col1            object
col_with_nan    object
dtype: object
>>> type(df['col_with_nan'][2])
<class 'float'>
>>> type(df['col_with_nan'][1])
<class 'str'>
>>> type(df['col_with_nan'][0])
<class 'str'>
>>>
```
So, sure, now this column will be treated as a char column, and trying to find the length will get 3 since a missing float, cast as a string is the string 'nan' (whatever case).  
```
>>> sas.df_char_lengths(df)
{'col_with_nan': 3, 'col1': 1}
>>>
```
I'm not really sure that this is something I should have to try to work around, really. You show in the other column, which is actually all chars, that missing (Null, empty string) "" is a more correct way to code a missing character value than sticking a float in the middle of a char field. And, then you get the length you were expecting, which is right. No offense, but this seems like 'user error' to do this but expect it to behave like if it was done the more correct way. Hope that makes sense.

Trying to make df2sd somehow support mixed type columns which are declared (as best then can be by pandas) as strings (char) but having floats or anything else in them (cuz 'object' can actually be anything; there is no 'string' or 'char' type in pandas) and not expecting them to be converted to strings, as that's the only possibility for moving the data into SAS (as a char variable), isn't realistic, in my mind. 
What I expect for things like this, where you have something valid in a dataframe that can't be valid (as is) in a SAS data set, is that you manipulate, or normalize the data frame into something that can be valid in SAS before trying to import it. Python is trivially easy for this kind of thing. This one is kinda like Dr., Dr., it hurts when I do this  :  I don't like getting 3 for the length because I forced a Null float into a char column, and it's 3 chars long when converted to a char; then don't do that and put a Null char in the char column, which is 0 chars long. Or, convert Null floats to Null chars in that column, before trying to import it to SAS. Sorry, I'm really not trying to be unsupportive here, but this is what I think for this scenario. You know I help as best I can all the time, but this one seems a user issue. Really not being argumentative. 

Now, here's where you convince me otherwise, and show me how and why that somehow does make sense :)

What do you think?
Tom

If you put a 1 in there, which becomes a float, but displays as '1' (1 char long), you still get 3 because it's really '1.0' (see 'col1' this time):
```
>>> df = pd.DataFrame({"col1": ["Y", "N", "", 1.0], "col_with_nan": ["Y", "N", np.nan, 1]})
>>> df
  col1 col_with_nan
0    Y            Y
1    N            N
2               NaN
3    1            1
>>>
>>> type(df['col_with_nan'][3])
<class 'int'>
>>>
>>> type(df['col1'][3])
<class 'float'>
>>> df['col1'][3]
1.0
>>>
>>>
>>> sas.df_char_lengths(df)
{'col_with_nan': 3, 'col1': 3}
>>>
>>> type(df['col1'][2])
<class 'str'>
>>>
>>> df['col1'][2]
''
>>> df.dtypes
col1            object
col_with_nan    object
dtype: object
>>>
```

**Comment by tomweber-sas** [comment]
No to beat this to death (but I guess I am), I see this one case as the one square out of all the possible rectangles. It's just a null, missing, N/A, whatever, so it should just be empty. But to take a column of type Object and import it into SAS can only work if the values are strings. So, this is not really different than any other 'not a string' that is put into an Object column of a dataframe (all the rectangles. if you will). All I can reasonably do is take str() of each value and move it to SAS.

Here's a slightly different case, but the same to me, where I have a one item dictionary in the column, which pandas is perfectly happy to accommodate, but is not valid in a SAS dataset. Now, you may say, Hey, I only wanted the Value from the dict to be in my data set, so what I actually get isn't what I want. 

This is what you get:
```
>>> df = pd.DataFrame({"col1": ["Y", "N", "", 1.0], "col_with_nan": ["Y", "N", np.nan, {'hey':'what?'}]})
>>> df
  col1      col_with_nan
0    Y                 Y
1    N                 N
2                    NaN
3    1  {'hey': 'what?'}
>>> type(df['col_with_nan'][3])
<class 'dict'>
>>> sas.df_char_lengths(df)
{'col_with_nan': 16, 'col1': 3}
>>> str(df['col_with_nan'][3])
"{'hey': 'what?'}"
>>> sd = sas.df2sd(df)
>>> sd.head()
  col1      col_with_nan
0    Y                 Y
1    N                 N
2  NaN               NaN
3  1.0  {'hey': 'what?'}
>>> sd.columnInfo()
     Member  Num      Variable  Type  Len  Pos
0  WORK._DF    1          col1  Char    3    0
1  WORK._DF    2  col_with_nan  Char   16    3
>>> df.dtypes
col1            object
col_with_nan    object
dtype: object
>>> 
```
So, to get what you want, I say that's up to you on the python side, and you can get this with one line of code (make the dataframe compatible for sending to SAS; not me trying to jigger it around somehow) to get what you want:
```
# change the value to a char myself; now I have char 5 not 16, with the value not the str(dict)
>>> df['col_with_nan'][3][list(df['col_with_nan'][3].keys())[0]]
'what?'
>>>

>>> df['col_with_nan'][3] = df['col_with_nan'][3][list(df['col_with_nan'][3].keys())[0]]
>>> df
  col1 col_with_nan
0    Y            Y
1    N            N
2               NaN
3    1        what?
>>>
>>>
>>> sd = sas.df2sd(df)
>>> sd.head()
  col1 col_with_nan
0    Y            Y
1    N            N
2  NaN          NaN
3  1.0        what?
>>> sd.columnInfo()
     Member  Num      Variable  Type  Len  Pos
0  WORK._DF    1          col1  Char    3    0
1  WORK._DF    2  col_with_nan  Char    5    3
>>>
``` 
There's no end of what you can put in a Object column that's not a string, but I have to consider all the values of that column str() or I have endless permutations of cases to somehow support. 

Ok, I'm done for now :)

**Comment by tomweber-sas** [comment]
Sorry, can't help it, this one's a polygon! :) I can't even guess what the 'right' thing could be for this (other than str() of it).

Jeremy, I hope you see my point and find this amusing, not irritating.
Tom

```
>>> df = pd.DataFrame({"col1": ["Y", "N", "", 1.0], "col_with_nan": ["Y", "N", np.nan, sas]})
>>> df
  col1                                       col_with_nan
0    Y                                                  Y
1    N                                                  N
2                                                     NaN
3    1  Access Method         = IOM\nSAS Config name  ...
>>> df['col_with_nan'][3]
Access Method         = IOM
SAS Config name       = iomj
SAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py
WORK Path             = /sastmp/SAS_workAF7E00006687_tom64-5/SAS_work7F0400006687_tom64-5/
SAS Version           = 9.04.01M4D11092016
SASPy Version         = 3.6.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = utf-8
Python Encoding value = utf_8
SAS process Pid value = 26247


>>> type(df['col_with_nan'][3])
<class 'saspy.sasbase.SASsession'>
>>> str(df['col_with_nan'][3])
'Access Method         = IOM\nSAS Config name       = iomj\nSAS Config file       = /opt/tom/github/saspy/saspy/sascfg_personal.py\nWORK Path             = /sastmp/SAS_workAF7E00006687_tom64-5/SAS_work7F0400006687_tom64-5/\nSAS Version           = 9.04.01M4D11092016\nSASPy Version         = 3.6.1\nTeach me SAS          = False\nBatch                 = False\nResults               = Pandas\nSAS Session Encoding  = utf-8\nPython Encoding value = utf_8\nSAS process Pid value = 26247\n\n'
>>> sd = sas.df2sd(df)
>>> sd.head()
  col1                                       col_with_nan
0    Y                                                  Y
1    N                                                  N
2  NaN                                                NaN
3  1.0  Access Method         = IOM\nSAS Config name  ...
>>> sd.columnInfo()
     Member  Num      Variable  Type  Len  Pos
0  WORK._DF    1          col1  Char    3    0
1  WORK._DF    2  col_with_nan  Char  474    3
>>> 
>>> df.dtypes
col1            object
col_with_nan    object
dtype: object
>>>
```

**Comment by biojerm** [comment]
So in general I agree with you having mix types in a column is going to make it a nightmare, and you/saspy should not have to figure out all the crazy stuff I could/will do.  If I start passing in dictionaries, lists and objects and trying to create values from it, it is on me to clean that up.

My only argument is that `np.nan` is a special case:

```
df_sensible = pd.DataFrame(
    {"col1": ["Y", "N", ""], "col_with_nan": ["Y", "N", np.nan]}
)
df_wild = pd.DataFrame(
    {"col1": [None, np.nan, "", {"dict!@!": "thanks_pandas"}, sas]}
)


print(df_sensible)

print("df_sensible max length using astype")
print(df_sensible["col_with_nan"].astype(str).map(len).max())

print("df_sensible max length using str methods")
print(df_sensible["col_with_nan"].str.len().max())


print("###############################")

print("\n let's now do mean things")
print(df_wild)

print("df_wild max length using astype")
print(df_wild["col1"].astype(str).map(len).max())

print("df_wild max length using pandas str methods")
print(df_wild["col1"].str.len().max())
````
this will give me this output 
```
  col1 col_with_nan
0    Y            Y
1    N            N
2               NaN
df_sensible max length using astype
3
df_sensible max length using str methods
1.0
###############################

 let's now do mean things
                                                col1
0                                               None
1                                                NaN
2
3                       {'dict!@!': 'thanks_pandas'}
4  Access Method         = STDIO\nSAS Config name...
df_wild max length using astype
450
df_wild max length using pandas str methods
1.0
```

So the max length when using `df_wild[name].str.len().max()` for `df_wild` is 1 because there is one `key` and one `object` which kinda makes sense.  But when you use `astype(str)` you get 451 which presumable is the the number of characters in the sas output text.


All this being said, and what I am realizing now, is if the max length is set to 1 and you have passed a dictionary to sas... will the value be `'{'` for the dictionary and `A` for the sas object (both the first character of the string representation)?  If so I think this would be worse and make troubleshooting harder vs a length of 451 (where you would see all the text).  I did not go an modify my source package so I am unsure what would happen here for df_char_length, and the resulting datasets.


To summarize:
  1) If I am passing objects (dicts, lists, funcs, classes) to sas and expecting good things.  This is 100% user error
  2) np.nan's `'nan'`  string representation misses the 'spirit' of nan (marking missing data).  Having a length of 3 seems odd and a length of 0 makes more sense to me. (yachts_owned = np.nan ; len(yachts_owned) => 0  _not_real_code_)
https://kegui.medium.com/what-is-the-difference-between-nan-none-pd-nan-and-np-nan-a8ee0532e2eb
  3) using the Series.str methods may accomplish point 2
  4) if point 3 leads to DEEPLY truncated data the benefit does not outweigh the cost when I invariable do point 1 and am troubleshooting 😆 


If your are still not convinced or there are other things I am not thinking about, I am completely fine with this being standard behavior the 'cost' is minimal and now that I know about it I can watch out in the future.  And like you said I can modify my data pretty easily before passing it to sas.  In my case via pd.fillna('') or something

**Comment by tomweber-sas** [comment]
Hey Jeremy, thanks for putting up with me and for providing all of this. Actually, I think I see this a little differently. This is the square case (just the nan case), but you're not really asking me to do something special for it. Rather, just use a slightly different method that will happen to solve the square, and still work for all the rectangles too, though the polygons are hosed!

Let me play around with this. When I pulled this code (calculate the char lengths) out of df2sd, the primary reason was to address the amount of time it was taking to do this on large data frames. Of course, there's more to this in there, but it was about the performance.

I tried many different patterns, one of which was df[col].str.len().max(), as it turns out (I had max(df[col].str.len()) but that's the same difference, and behaves the same). So let me go back to my test cases for this and see what it was with this: just slower than the one I picked? Consumed more memory? Could have been both. Didn't work for some case? ...?

You're not really looking for me to check for this specifically, or do the conversion for you ... just use a method that happens to get 1 instead of 3, cuz of who knows why, but it does. So let me do some more analysis on this, which I wouldn't be opposed to, assuming it works for all of the other cases and performs well.

Again, thanks for the great conversation and debate! I really appreciate it, and enjoy it. Again, I could still argue that a missing char is '', not a float of missing, but if I can kill two birds with the same line of code, and it not be problematic in some other way, then I'm not against that. Let me investigate more.

More to come ...
Tom

**Comment by tomweber-sas** [comment]
Ok Jeremy, I've dug in to this enough to remember a few things and to assess this more. So, let my try to list some things.

1) .str is is slower and uses more memory that the astype. Not terrible, but on both counts, which is why I went with astype
2) .str didn't work with the case where I was encoding to get the SAS encoded byte length, though it worked for char length.
   I have figured out how to get it to work for that case now, though. So I was able to test out that performance too.
3) .str isn't completely compatible with how df2sd (data transfer part) works, so there are inconsistencies with that

So, for 1 and 2 (now that it can work for both cases), I wouldn't be completely against switching it out to use .str. But, the 
issues w/ 3 are too much to make this change, certainly by default. One thing I'm not against, would be to add another option
so you could specify method=['astype' | 'str'], with astype being the default (current behavior), but you could override with method='str'.

So, what incompatibilities does 3 have? First, .str.len() of a nan isn't 1, it's actually nan, not 0 either, though I would treat
a length of nan as 0. If your char column has all nan's, then the .str.len() would be nan, which I'd consider 0,
and in that case you would have a SAS char length of 8, SAS's default, not 1, and certainly not 0. Secondly, for data transfer,
I do use str(col value) since it's going into a char variable. The polygon cases (list or any other object), no longer work
even close, as they actually also return nan for the .str.len(), not 1 and we're back to not having the actual length of the str()
of that value, which currently works correctly; you put a list of strings or some other object and you get the str() repr of that,
which is the string form of that object. So if you don't actually get the length of that representation, and it's the longest value,
then that data is truncated on transfer. For all I know, users are putting lists or other objects in a column, and expecting this
behavior when using df2sd. So changing to .str will break existing functionality, which is considered 'correct' (so thins wouldn't
be a fix for those cases).

I can post runs and examples of all this, but I expect you already understand these. So, although I can't change it to use .str
instead of astype, I can add an option so you could override it to use .str, accepting the incompatibilities (which you may not hit).

What are your thoughts on this?
Thanks!
Tom

**Comment by biojerm** [comment]
Honestly to me it does not sound worth the effort of changing.  

As I see if we implement using str:
1) Using .str substitutes one set of problems for another.
2) `str` method is worse with both speed and memory
3) current behavior, that some people may like, could be changed (less likely using the argument)
4) extra function options with limited value unless (you are super in the 'weeds') and the code becomes more complex
5) If you have a column of all `nan`s your length is 8 instead of 3 which I assume would make the dataset take up more memory.
    5a) I originally brought this up because a column that I thought should have a length of 2 had a length of 3.  So I thought, oh... minor savings in memory if we get the lengths right (if that is even true).  But I am at best saving 1-2 characters.  However if a column has all `nan`s  and we fall back to the default of 8.  We gain 5 characters in length vs the 3.  Which is going the wrong direction for my original intent.  

vs

If no changes are made:
1) nans have a length of 3 because of how `str(np.nan)` works, if that bothers you fill them using `.fillna("")` before creating the dataset
2) Also the above is only a problem if the _rest_ of your column has a length less than three.   



I am leaning heavily towards not doing anything.  More complexity is a pain to maintain, the benefits seem small, and data cleaning resolution seems easy enough.

I do appreciate you looking into this carefully though.  I am happy with closing the bug without changes if you are.

**Comment by tomweber-sas** [comment]
Yes, I agree with your assessment too. That's pretty much how I see it. There are a number of ways to work around this on the user side, like using fillna before calling df2ds, or even calling d1=df_char_lengths(df) do get the dict with the lengths, change the value from 3 to 1 for that column, and pass that dict to sd2df(..., char_lengths=d1) and then it will be a char 1 on SAS with the correct values.

But, even though this is the case, I hate (even effectively) saying NO to a user request, if reasonable at all. So I'm not against adding an option of which method to use for the calculation. So, if you want that, I will do it; it's easy enough and won't change the behavior unless you use it to override the default. Documenting it will be more complicated than coding it :)  haha

Thanks!
Tom

**Comment by biojerm** [comment]
I don't see this as saying 'no' to a request.  We looked at the options, and I don't think there is added benefit, and I have a solution to solve the issue in the future.   If in the someone comes across this thread and wants to reopen and asks for feature they are welcome to.

If you have already done the coding and want to push it feel free.  But from my perspective, I don't think the benefits are worth the extra complexity (both in code and docs).

**Comment by tomweber-sas** [comment]
Sounds good, and no, I hadn't coded it up; just coded test code to research it. I'm good with leaving it as is. And, I've been gonna build a new version with the handful of changes at main, so if we're not going to do this, I'll go ahead and snapshot what's there now. As always, I appreciate your help and insight! Have a great weekend!

Thanks,
Tom
