### ISSUE TITLE
SAS Dataset to Pandas too slow on windows and sas grid on Unix set up

### ISSUE THREAD

**Issue by ditordccaa** [sassoftware/saspy#356]
Hi @tomweber-sas ,

I'm opening this issue since the transfer between SAS dataset and Pandas Dataframe is a slow on my end. 
I have a Python installation and the saspy package on a Windows machine. SAS however is on a Unix environment and it's a SAS Grid Platform.

Here is the information about my SAS connexion using the saspy package : 
```
>>> sas
Access Method         = IOM
SAS Config name       = winiomlinux
SAS Config file       = P:/..../saspy/sascfg_personal.py
WORK Path             = /saswork/SAS_work49BE000057E2_my_hostname.organization.com
SAS Version           = 9.04.01M7P08052020
SASPy Version         = 3.6.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin1
Python Encoding value = latin1
SAS process Pid value = 22498
```

AS for the code that I submit to read a SAS dataset into a Pandas Dataframe. 
The dataset has 4M rows and 160 columns and it's about 3.5GB.
Sorry in advance if there are any typos since I'm working on a machine with no internet and I'm not allowed to copy/paste.
```
import saspy
import pandas as pd
import time

sas = saspy.SASsession(cfgname="winiomlinux")
sas.saslib("lib", path="my_specific_path")
hr = sas.sasdata(table= "my_dataset", libref="lib")


start = time.time()
df = fr.to_df_DISK(tempfile="local_path_on_the_windows_machine/my_dataset.csv",
                              tempkeep= True)
print(time.time() - start)

```

It's worth mentioning that when I convert small datasset (such as CARS.sas7bdat, or a dataset with 1000 observations) , the method to_df works just fine and quick. However with this dataset that' almost 3.5GB it's very very slow (it takes almost an 1h).

Do you have any leads on the matter that I can try.

Cheers.

**Comment by tomweber-sas** [comment]
Thanks @ditordccaa, 

So, I tried a similar test to see how long it took and to see where the time was being spent. With the IOM access method, this is a multi-step process. For my case, I have a 4G SAS data set with 5M rows and 115 variables, all numeric. I also ran python from windows and remotely connected to SAS on Linux. So, this should be pretty comparable to your case; obviously hardware and all of that make a difference. But, I was able to assess the amount of time for each step.

The steps are as follows.
1)	gather metadata about the dataset so I know what dataframe I’ll be building, and know how to write out the data
2)	submit data step that reads the data set and writes out the data in a format pandas can import
3)	stream that output file from the SAS server to the python side; writing it out on the client
4)	import that client side file using pandas read_csv method

For my case, the whole thing took about 42 minutes. The data set was about 4G on disk, but the exported file was about 8G, as it’s written out as text for pandas to be able to process. Step 1 takes no appreciable time. Step 2, the data step to process the data, reading in the data set and writing out the external file took about 35 minutes; the majority of the time. Transferring the 8G file over to the client, step 3, took about 4 minutes and pandas took 3 minutes to import the data to a dataframe, step 4.
```
NOTE: The file _TOMODS1 is:
      Filename=/sastmp/SAS_workF77500000A49_tom64-5/SAS_work2B5B00000A49_tom64-5/_tomods1,
      Owner Name=sastpw,Group Name=r&d,
      Access Permission=-rw-r--r--,
      Last Modified=04Jan2021:09:27:33

NOTE: 8820033256 records were written to the file _TOMODS1.
NOTE: There were 5000000 observations read from the data set X.SASPY4G.
NOTE: DATA statement used (Total process time):
      real time           34:35.01
      cpu time            34:27.73
```

Not that it matters, but the STDIO access method uses sockets for this, so steps 2 and 3 are one in the same; not having to cache the data on the SAS server first - streaming it to the client as it’s processed. I'm running that case now to see how much difference that makes. I don't think it will be significant though, as the transfer itself wasn't nearly as much as the data step took. But, I'll see what I see. This isn't really relevant for your case anyway, as you are using IOM, so what I have above is appropriate for you case.

So, this info doesn't give you anything to make it faster, but this is what is happening. So, that's the first step. I'm not sure how to make the data step any faster, and that's the step that takes the majority of the time. 

Can you see how much time the data step is taking for your case? I expect it's comparable and is the majority of the time?

Tom

**Comment by tomweber-sas** [comment]
Well, my STDIO over SSH test finished, and it was basically the same amount of time for each step; 2 and 3 combined. So, that's really just for my understanding, as again, you're using IOM. But, SAS is SAS and even though there are different options for different access methods (disk vs. socket, and recfm and blksize ...) it was still the data step writing out the data for pandas to consume that is taking most of the time. Again, just FYI at this point.

**Comment by tomweber-sas** [comment]
I've been looking at this and comparing some things. There are many ways in SAS to do what would be the same thing, with lots of options and variations; especially with external l/O. All of these options don't necessarily behave the same on different OSs and some options aren't available with different access methods, or again, don't behave identically across OSs and such. 

There are some differences in the options for external I/O in these access methods (different options in different circumstances). For this case, with large data, I am seeing one of the alternative cases perform better, even though, for other data, the default case is 'better'. So, can you try one thing for me and see how this changes the time it takes for your case? You can force this other case by setting an attribute.

On your SASsession object set this m5dsbug attribute to True and then run your code and see the difference 
sas.m5dsbug=True

For my situation with this 4G data set, it improved performance considerably. I'd like to see your timings for each case; m5dsbug=True | False

I'll continue to run more testing with this and see what I can see with data this size and see if there's something I can do to help all cases.

Thanks,
Tom

**Comment by ditordccaa** [comment]
Hi @tomweber-sas , Thanks for taking the time to make those tests and the detailed response.
I ran some random tests to see how the imports behave. Here is the results of some of the tests (Note that I can provide you with details about other tests if needed)

### Summary some random tests
| Execution read\_csv in pandas | Execution time<br>(seconds) | \# Rows | \# Columns | \# Numerical Columns | \# Character Columns | Outputed File Size | m5dsbug | Method Used                         |
| ----------------------------- | --------------------------- | ------- | ---------- | -------------------- | -------------------- | ------------------ | ------- | ----------------------------------- |
| \-                            | 6.9                         | 10000   | 307        | 275                  | 32                   | 7,61Mo             | False   | to\_df\_Disk                        |
| \-                            | 4.1                         | 10000   | 307        | 275                  | 32                   | 7,61Mo             | True    | to\_df\_Disk                        |
| \-                            | 29.9                        | 100000  | 307        | 275                  | 32                   | 76,2Mo             | False   | to\_df\_Disk                        |
| \-                            | 24.4                        | 100000  | 307        | 275                  | 32                   | 76,2Mo             | True    | to\_df\_Disk                        |
| \-                            | 300.7                       | 1000000 | 307        | 275                  | 32                   | 779Mo              | False   | to\_df\_Disk                        |
| \-                            | 256.9                       | 1000000 | 307        | 275                  | 32                   | 779Mo              | True    | to\_df\_Disk                        |
| 189                           | 1659.1                      | 4418666 | 307        | 275                  | 32                   | 3.38Go             | False   | to\_df\_Disk                        |
| 189                           | 1312.1                      | 4418666 | 307        | 275                  | 32                   | 3.38Go             | True    | to\_df\_Disk                        |
| \-                            | 1.1                         | 10000   | 32         | 0                    | 32                   | 1.32Mo             | False   | to\_df\_Disk                        |
| \-                            | 1                           | 10000   | 32         | 0                    | 32                   | 1.32Mo             | True    | to\_df\_Disk                        |
| \-                            | 188.4                       | 4418666 | 32         | 0                    | 32                   | 458Mo              | False   | to\_df\_Disk                        |
| \-                            | 152.8                       | 4418666 | 32         | 0                    | 32                   | 458Mo              | True    | to\_df\_Disk                        |
| \-                            | 1309.1                      | 4418666 | 275        | 275                  | 0                    | 2.94Go             | False   | to\_df\_Disk                        |
| \-                            | 1017.9                      | 4418666 | 275        | 275                  | 0                    | 2.94Go             | True    | to\_df\_Disk                        |
| 189                           | 1445.3                      | 4418666 | 307        | 275                  | 32                   | 3.23Go             | False   | to\_df(method="CSV", tempkeep=True) |
| 189                           | 1326.6                      | 4418666 | 307        | 275                  | 32                   | 3.23Go             | True    | to\_df(method="CSV", tempkeep=True) |

### Information about the dataset
![content-dataset](https://user-images.githubusercontent.com/58598645/103627817-1d9d9300-4f0c-11eb-89af-eae473811840.png)
![content-dataset-variables-types](https://user-images.githubusercontent.com/58598645/103627849-27bf9180-4f0c-11eb-8226-3f4da33e8f90.png)
![size-dataset](https://user-images.githubusercontent.com/58598645/103627872-31e19000-4f0c-11eb-93e2-71d36a4dd3ad.png)


### Information about the SAS Session
So as a reminder here is the info about my SAS session. 
```
Access Method         = IOM
SAS Config name       = winiomlinux
SAS Config file       = path_directory\sascfg_personal.py
WORK Path             =   /saswork/SAS_workF5910000597D_myhostname.my_organization.com/SAS_work839D0000597D_myhostname.my_organization.com/
SAS Version           = 9.04.01M7P08052020
SASPy Version         = 3.6.4
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = latin1
Python Encoding value = latin_1
SAS process Pid value = 22909
```

### Python Code
as for the code that I ran 

```
import os
import sys
import time
import saspy
import pandas as pd
from IPython.display import HTML  
#   =============================================================================
# Start Session
#   =============================================================================
sas =   saspy.SASsession(cfgname="winiomlinux")
sas.m5dsbug=True
# sas.m5dsbug=False 
#   =============================================================================
# Define dataset
#   =============================================================================
sas.saslib("mylib",   path="path_to_my_lib")
hr= sas.sasdata(table="my_dataset", libref="mylib") 

DSOPTS= {'obs':  number of records to extract, "encoding": "utf-8"}
# when  I tested with the to_df_Disk method
hr= sas.sasdata(table="my_dataset", libref="mylib",    dsopts = DSOPTS) 

#   =============================================================================
# Convert to Pandas dataframe 
#   =============================================================================
start =time.time()
# when I tested with the csv method
df = hr.to_df(method="CSV",
                     tempfile='path_output_directory/output_file.csv',
                     tempkeep=True)

# when I tested with the to_df_Disk method
df = hr.to_df_DISK(tempfile='path_output_directory/output_file.csv',
                              tempkeep=True,
                              rowsep=",")  

print(time.time() - start)
```

### Discussion

1- We know that pandas is not efficient with large dataset. From my understanding the saspy methods write the data to a csv file and then load it to a pandas Dataframe. Wouldn't be optimal to just write the flat file (csv) and let the user upload the necessary data or use some more efficient engines / libraries (for example Dask).

2- I noticed that even if my Python and SAS session uses "latin-1" encoding, I had to specify the "utf-8" encoding with the `df_to_Disk` method. Otherwise, the code throws an error of encoding.

3- Even if I explicitl specify the rowsep in the `df_to_Disk` as being the comma ",". when I peek into the written csv, the seprator is a weird character (see below pictures)
![snapshot-outputed-csv](https://user-images.githubusercontent.com/58598645/103629848-d95fc200-4f0e-11eb-81ba-a17bc46c4df4.png)

I hope this gives you more information about the issue. As on my end I'm bit confused. 
Finally, Can you please provide small snippet in order to see the logs of the submitted SAS commands. I use the method lastlog but the output needs some prettifier. So I'm wondering if you have any suggestion how to peek into logs to help with debugging.

Cheers,

**Comment by tomweber-sas** [comment]
Hey @ditordccaa thanks for all the info. It doesn't seem the different code gen (based upon m5dsbug) makes as much of a difference for you then I was seeing. The timings above are for the entire process. Do you see a bigger difference in the times of the data step itself? 

Addressing your questions:
1) There are 3 methods (mem, disk. csv) which each do this a little differently. A little explanation here: https://sassoftware.github.io/saspy/advanced-topics.html#slow-performance-loading-sas-data-into-a-pandas-dataframe-to-df-sd2df
So, the CSV method used proc export to write out a CSV file whihc is then downloaded (unless you're on the same machine) and pandas read_csv is used. DISK is the same algorithm as MEM except that instead of building the data frame in memory as the data is streamed over, it's written to disk to again use read_csv (though the format is not the same as CSV). 
To get the data and load it yourself, you can use the to_csv() method on the SASdata object (or write_csv() on SASsession) and then download() and that is basically the first steps of to_df_CSV() without calling pandas. 

2) this is disconcerting. This implies that the data in your data set isn't actually latin1 data. Your SAS session is running in latin1, and the dataset believes it's data is in latin1, so it would be read in directly. If you're setting the encoding data set option, that is telling SAS that the dataset has utf-8 data in it, not latin1 like the dataset thinks, and it should convert it to latin1 from utf-8 when reading it into SAS. So, what data is really in that? What error are you getting when you don't do that? Here's the doc on encoding=: https://go.documentation.sas.com/?cdcId=pgmsascdc&cdcVersion=9.4_3.5&docsetId=nlsref&docsetTarget=n0kzmrsdx5evkxn1ihs24h8ljg2b.htm&locale=en

3) For DISK (and MEM) I use low hex values as the column and row seperators; values that aren't valid chars in any encoding. This solves all the problems of CSV with embedded delimiters/quotes/newlines/nulls/...   So, what you are seeing is the column delimiter, which is still hex 2 while you changes the row separator to a comma (hope there are no commas anywhere in the data).

Oh, as for sas.lastlog() and sas.saslog(), you need to print() those to have their strings formated:
print(sas.lastlog())  or print(sas.saslog())

There's a lot of curious things goin on here. Would you have any interest in a web-ex or teams call to look into some of these things? 

Thanks,
Tom

**Comment by ditordccaa** [comment]
Yes sure thing @tomweber-sas. That would be so much helpful. Thanks :)

I'm available today all afternoon and tomorrow morning too. Let me know you're availabitites and if it's you who's going to send the webex invitation.

Note that I'm on the US eastern time (UTC/GMT-5).

Meanwhile, I'll test the write to_csv methods and reverify the encodings too.

Cheers

**Comment by tomweber-sas** [comment]
Cool, how about after lunch, I'm EST as well. Email me and I'll reply back with the link to connect. How is 1 or 2 oclock this afternoon? oh, I'm tom.weber@sas.com

**Comment by ditordccaa** [comment]
Perfect. I've sent you an email.

**Comment by tomweber-sas** [comment]
To follow up here, we had a good debugging session and found a bug which was causing the transcoding issues and figured out the problem with displaying the log. The log was that the UI being used, spyder, couldn't handle Form Feed (next page) character that SAS uses in the log; removing those allowed the log to be displayed nicely formatted as expected. The transcoding issue was due to the output file being written, for pandas read_csv to parse, was being converted from utf-8 (which was being written) to whatever latin encoding windows was using. The fix was to add 'encoding=utf8' to the python open() for that file to force the data on disk to stay utf-8, as it was supposed to be. On linux it's written as the utf-8 it's given, but windows changes it to the other encoding. I was able to reproduce that on my windows system and also verified the fix.

That brings us back to performance for the sd2df_DISK  method. I observed that the SAS code being generated by default (lrecl=1 recfm=F encoding-binary) does not perform as well as the alternate code being used to circumvent a bug in the data step in M5, which causes that code to hang (recfm=V delim=, termstr=).  I expect the performance difference is due to no buffering (single byte I/O) for the Fixed case and buffering for the Variable case. Even though the Variable case generates a larger file on disk, transferring that file over to the client is much less a performance issue than how long it takes SAS wo write the slightly smaller Fixed file to begin with. 

So, we were going to rerun the original test case, with the encoding fix, with m5dsbug= True and False to compare the two different code gens with this original test case. I expect the True case to end up performing better, like I saw here with my test case. 

Tom

**Comment by ditordccaa** [comment]
I rerun the tests with the same dataset using both m5dsbug= True and False and here are the results. Seems quite intersting that this time the processing was much quicker than the first time I opened the issue :). I guess it's related to the bug that we fixed but not quite sure. Anyway below are the results:

#### m5dsbug = True

> Total execution time : 16 min
>  ```
> NOTE: There were   4418666 observations read from the data set MY_LIB.MY_DATASET.
> NOTE: DATA statement used (Total process   time):
> real time           2:11.23
> cpu time            2:05.00
> ```

#### m5dsbug = False
 > Total execution time : 20 min
>  ```
> NOTE: There were   4418666 observations read from the data set MY_LIB.MY_DATASET.
> NOTE: DATA statement used (Total process   time):
> real time           5:53.08
> cpu time           5:46.44
> ```
  
Cheer

**Comment by tomweber-sas** [comment]
Thanks @ditordccaa . I can't say that the transcoding issue was somehow causing the extra time. And without equivalent timings, it's hard to say. These both seem much better and still show the difference in the two code gen's (Fixed vs Variable) of SAS's external I/O. I would expect the data transfer from server to client and read_csv() processing would be similar. Since you had SAS transcoding the data (which wasn't necessary nor correct, due to the bug), and, as it turned out, windows python was transcoding the data being written to the file (again, bug) from utf-8 to wlatin1 (or whatever 
```
>>> locale.getpreferredencoding() 
'cp1252'
>>>
```
)
turned out to be, those two transcoding steps would add time to the overall time for the whole process. Just can't see that being as much time as the difference between these runs and the 'it's very very slow (it takes almost an 1h).' from the original run.

But, with this bug fixed and the process running in a more reasonable amount of time, not to mention correctly, I think this is looking much better. I still want to see about this difference and maybe see about changing the default code being used. But you  can choose the 16 min over thee 20 by setting the attribute to True and that will be better performance for what you're doing.

I really appreciate your time and help debugging this!
Tom

**Comment by ditordccaa** [comment]
Same here :). With that I'll close this issue.
Cheers
