### ISSUE TITLE
Loading SAS data in bulk fails to raise an Error and loads wrong data

### ISSUE THREAD

**Issue by aschoenauer-sebag** [sassoftware/saspy#361]
Hi,

We face a bug when trying to load into pandas multiple SAS files in a for loop, and use the wrong _keep_ list for one of them without closing the SAS session. 

Let us be more specific, and say that varB is missing in one of the files we are interested in. However, when we try to load all SAS files and transfer from saspy.SASData to pandas.DataFrame in a for loop, it does not raise the usual error. It just reloads into pandas the previous database, instead of raising an eror or loading the right one without varB.
We only get the error if not calling endsas() after each data loading, suggesting it might be loading something that staid in memory/cache.

Here is the loop that causes problem, with SASsession inheriting from saspy.SASsession with minor additional methods:

```
df = dict()
dsopts = {
            "where": '',
            "keep": [varA, varB]
        }
# Wrong_file only has varA in it, all the other have both variables.
files = [correct_file_1, wrong_file, correct_file_2, correct_file_3]

session = SASsession()
for data_file in files :
     data = session.sasdata(table=data_file, libref=libref_name, results="Pandas",
                                       dsopts=dsopts)
     df[data_folder] = data.to_df_CSV()

session.endsas()
```
In that case, _df_ will contain twice the data from _correct_file_1_, instead of raising an error when trying to load into pandas _wrong_file_. It would be nice to fix this, as it does not seem a good idea to load something else than the expected file without throwing an error if using the same SAS session. Two people in my team have reproduced this bug with distinct file lists.

Software versions:
Saspy version is 3.3.6
SAS 9.4 TS Level 1M0 X64 DSRV12 platform 
windows 6.2.9200

**Comment by tomweber-sas** [comment]
Hey @aschoenauer-sebag, I can help with this. I tried to replicate the problem and I'm not getting what you're describing. So, I'm probably not doing exactly what you are. I see SAS is windows (SAS 9.4 TS Level 1M0 X64 DSRV12 platform
windows 6.2.9200), so I expect you are using the IOM access method? Can you submit your SASsession object, and I'll get a bunch of useful info from that. For instance:
```
>>> sas
Access Method         = IOM
SAS Config name       = winlocal
SAS Config file       = C:\Users\sastpw/.config/saspy\sascfg_personal.py
WORK Path             = C:\Users\sastpw\AppData\Local\Temp\SAS Temporary Files\_TD24056_d10a626_\Prc2\
SAS Version           = 9.04.01M5P09132017
SASPy Version         = 3.3.6
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = wlatin1
Python Encoding value = cp1252
SAS process Pid value = 24056
```
I tried this on windows, and I installed 3.3.6 that you say you are using, to be sure I would see what you get. The latest (3.6.4), which I am running, produces the same thing as 3.3.6, so that hasn't changed, but best to use what you are for things like this.
Here's what I get. Can you run this same thing w/ your case and let me see the output?
```
>>> cars = sas.sasdata('cars','sashelp',dsopts={'keep' : ['make','tom']})
>>> allcars.columnInfo()['Variable']
0       Cylinders
1      DriveTrain
2      EngineSize
3      Horsepower
4         Invoice
5          Length
6        MPG_City
7     MPG_Highway
8            MSRP
9            Make
10          Model
11         Origin
12           Type
13         Weight
14      Wheelbase
Name: Variable, dtype: object
>>>
>>> cars = sas.sasdata('cars','sashelp',dsopts={'keep' : ['make','tom']})
>>> cars
Libref  = sashelp
Table   = cars
Dsopts  = {'keep': ['make', 'tom']}
Results = Pandas

>>> df = cars.to_df_CSV()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\saspy-3.3.6\saspy\sasdata.py", line 1131, in to_df_CSV
    return self.to_df(method='CSV', tempfile=tempfile, tempkeep=tempkeep, opts=opts, **kwargs)
  File "C:\saspy-3.3.6\saspy\sasdata.py", line 1102, in to_df
    return self.sas.sasdata2dataframe(self.table, self.libref, self.dsopts, method, **kwargs)
  File "C:\saspy-3.3.6\saspy\sasbase.py", line 1383, in sasdata2dataframe
    return self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "C:\saspy-3.3.6\saspy\sasioiom.py", line 1586, in sasdata2dataframe
    return self.sasdata2dataframeCSV(table, libref, dsopts, **kwargs)
  File "C:\saspy-3.3.6\saspy\sasioiom.py", line 1865, in sasdata2dataframeCSV
    lrecl = int(l2[0])
ValueError: invalid literal for int() with base 10: 'vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1'
>>> print(sas.lastlog())
11                                                         The SAS System                             09:27 Friday, January 22, 2021

60
61         data sasdata2dataframe / view=sasdata2dataframe; set sashelp.'cars'n (keep=make tom );run;
ERROR: The variable tom in the DROP, KEEP, or RENAME list has never been referenced.

NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.01 seconds


62         data _null_; file LOG; d = open('sasdata2dataframe');
63         length var $256;
64         lrecl = attrn(d, 'LRECL'); nvars = attrn(d, 'NVARS');
65         lr='LRECL='; vn='VARNUMS='; vl='VARLIST='; vt='VARTYPE=';
66         put lr lrecl; put vn nvars; put vl;
67         do i = 1 to nvars; var = compress(varname(d, i), '00'x); put var; end;
68         put vt;
69         do i = 1 to nvars; var = vartype(d, i); put var; end;
70         run;

NOTE: Argument 1 to function ATTRN(0,'LRECL') at line 64 column 9 is invalid.
NOTE: Argument 1 to function ATTRN(0,'NVARS') at line 64 column 36 is invalid.
LRECL= .
VARNUMS= .
VARLIST=
ERROR: Invalid DO loop control information, either the INITIAL or TO expression is missing or the BY expression is missing, zero,
       or invalid.
d=0 var=  lrecl=. nvars=. lr=LRECL= vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1
NOTE: Mathematical operations could not be performed at the following places. The results of the operations have been set to
      missing values.
      Each place is given by: (Number of times) at (Line):(Column).
      1 at 64:9    1 at 64:36
NOTE: The SAS System stopped processing this step because of errors.
NOTE: DATA statement used (Total process time):
      real time           0.00 seconds
      cpu time            0.00 seconds


71
```

So, that's not a pretty error, but it fails and doesn't produce any result, not wrong data or anything. This exception would also break out of the loop and just fail the whole thing. So, there's something different in your case that I still need to understand. Then I can see what to do about it.

Thanks!
Tom

**Comment by tomweber-sas** [comment]
BTW, if you don't want to post the actual output here (would need to go through and obfuscate anything you don't want posted on here), you can just email the results to me. If that's an issue. my email's on my userid here. Some customers prefer to do that. So, whatever you'd like.
Tom

**Comment by aschoenauer-sebag** [comment]
Hi Tom,

Thanks for your quick reply. I would expect that the code does not reproduce our bug. This bug happens only in a for loop trying to load multiple datasets, with one (not the first) not containing one of the variables. Say you have `['cars_2018', 'cars_2019', 'cars_2020']`, and for some reasons, the variable `make` was not included in 2019, but you're using the same `dsopts = {'keep':['make']}`. Can you reproduce the bug in that setting?

Thank you,
Alice

**Comment by tomweber-sas** [comment]
Ok, yes, I see what's happening, and yes, I can get your same results. there's an intermediate view I'm using in the multi step SAS code to do all of this, which I wasn't deleting when done with, so that view is still there from the previous table, and thus is is being used in the last step for the table w/out the column, which then succeeds with the data from the previous table. I just added the delete into the sequence, and now it does fail, in the loop case, like in my previous stand alone case. I can push a fix for this, this afternoon.

My test case, which gave the same issue as you described.
```
import saspy
sas = saspy.SASsession(cfgname='iomj')
sas

sas.submitLOG("data cars1; set sashelp.cars;run;")
sas.submitLOG("data cars2; set sashelp.cars(drop = model);run;")
sas.submitLOG("data cars3; set sashelp.cars;run;")

dfd = dict()
tables = ['cars1','cars2','cars3']

for table in tables:
   cars = sas.sasdata(table, dsopts={'keep' : ['make','model']})
   cars
      
   df = cars.to_df_CSV()
   dfd[table] = df
```
When I clean up the view in to_df_CSV when I'm done with it so it isn't there for subsequent iterations
```
>>> dfd = dict()
>>> tables = ['cars1','cars2','cars3']
>>>
>>> for table in tables:
...    cars = sas.sasdata(table, dsopts={'keep' : ['make','model']})
...    cars
...
...    df = cars.to_df_CSV()
...    dfd[table] = df
...
Libref  = WORK
Table   = cars1
Dsopts  = {'keep': ['make', 'model']}
Results = Pandas

Libref  = WORK
Table   = cars2
Dsopts  = {'keep': ['make', 'model']}
Results = Pandas

Traceback (most recent call last):
  File "<stdin>", line 5, in <module>
  File "/opt/tom/github/saspy/saspy/sasdata.py", line 1235, in to_df_CSV
    return self.to_df(method='CSV', tempfile=tempfile, tempkeep=tempkeep, opts=opts, **kwargs)
  File "/opt/tom/github/saspy/saspy/sasdata.py", line 1206, in to_df
    df = self.sas.sasdata2dataframe(self.table, self.libref, self.dsopts, method, **kwargs)
  File "/opt/tom/github/saspy/saspy/sasbase.py", line 1649, in sasdata2dataframe
    df = self._io.sasdata2dataframe(table, libref, dsopts, method=method, **kwargs)
  File "/opt/tom/github/saspy/saspy/sasioiom.py", line 1665, in sasdata2dataframe
    return self.sasdata2dataframeCSV(table, libref, dsopts, **kwargs)
  File "/opt/tom/github/saspy/saspy/sasioiom.py", line 1973, in sasdata2dataframeCSV
    lrecl = int(l2[0])
ValueError: invalid literal for int() with base 10: 'vn=VARNUMS= vl=VARLIST= vt=VARTYPE= i=1 _ERROR_=1 _N_=1'
>>>
```

So, with this fix it will fail like I was expecting. This then begs your next questions, I'm sure. 
Should I somehow be validation what you're submitting, and fail gracefully when you provide bad variables? Should you be validating that yourself in your program and catch this yourself? 

I would say, that I can't catch every different thing that could go wrong, and that some of this is on you, the programmer. But, for drop/keep, specifically, that is something that is relatively easy to validate. I would have to code it in a lot of places, or perhaps provide a convenience method that does it, then the programmer can call when necessary and handle the error case however you like.

Something like this is an easy way to verify the columns:
```
>>> cars = sas.sasdata('cars','sashelp')
>>> dsopts={'keep' : ['make','tom']}
>>> vars = [v.lower() for v in cars.columnInfo()['Variable']]
>>> for col in dsopts['keep']:
...    print(col, col in vars)
...
make True
tom False
>>>
```

So, I'll code up this fix, in all the various places it's needed, and push that out later today, gonna go get some lunch now.
Let me know what you think about the other, as with this fix your code will get the error, and fail, like I expected. Obviously, it won't work right, because it's an error case, but what are your thoughts on validating it in your code and handling it however you want to? If you find the columns aren't in the table, set your dict value for that table to None, throw your own exception, get my exception and fix your code so you really get the correct results? Some other thought?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I've pushed the changes to main. Can you pull from there and see that you're now getting the failure on any data set w/out the variable in it? There should no longer be any residual data sets nor views from any methods. All of the various sd2df* routines, in the different access methods had this, as well as a number of other methods which required multi step operations. This was a good thing to go clean up.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Were you able to test this out and verify it it now throws the expected error? Thoughts on how to address the wrong columns being provided?

**Comment by tomweber-sas** [comment]
This change is now in the latest production version; V3.6.5
Is there anything else I can help with? Else I was looking to close this. If you had thoughts on the rest of it, let me know. Otherwise I'll go ahead and close this out.
Thanks!
Tom

**Comment by aschoenauer-sebag** [comment]
Hi Tom, sorry, the last weeks have been intense! I'll import the code now into our secured server and will let you know tomorrow. Thank you!

**Comment by tomweber-sas** [comment]
No trouble! I know how it goes. I've been pulled off on other things myself the past number of weeks too :)

**Comment by tomweber-sas** [comment]
I'm going to go ahead and close this; the functionality is in the current production release. If you still have any concerns with this, you can reopen it. And, of course, anything else just open other issues too!
Thanks!
Tom
