### ISSUE TITLE
STDIO over SSH identity keys

### ISSUE THREAD

**Issue by simontao01** [sassoftware/saspy#363]
**Expected behavior**
What's the format of .pem file and how to identify sshpath?

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Linux
 - SAS Version: SAS Grid 9.4M6
 - SASPy Version: 3.6.4

**Additional context**

**Comment by tomweber-sas** [comment]
You can google 'passwordless ssh' to lean about setting up ssh. On linux, typing 'which ssh' will show you which ssh executable is found in your search path, if one is, which is very likely. But it depends on your system.

**Comment by simontao01** [comment]
Let's talk on my work email: zhu.yong.tao@citi.com, thanks.

Best regards,

Simon

________________________________

**Comment by simontao01** [comment]
Hi Tom,

I google for .pem file but still not very clear how to make a correct one, do you have time today? Thanks.

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
Hey Simon,

I can't help you set up ssh to servers in your company. That's something someone there would need to help you  with. I
thought you mentioned that your manager knows linux, so he should be able to help you set that up and gain access to those
machines, if you are supposed to have permission to do so. ssh is a decades old, common technology; not something that has
anything to do with saspy. You have to be able to connect to a machine over ssh correctly to then simply configure saspy to use
that existing ability. ssh isn't part of saspy.

Tom

**Comment by simontao01** [comment]
Hi Tom,

Maybe I did not word correctly, I talked STDIO over SSH, which is one access method listed in saspy 3.6.4 as parallel with IOM, that's why I ask your help.

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
I don't understand "I talked STDIO over SSH", do you mean you are using it? Yes, I am familiar with my access methods I wrote for
saspy. STDIO has been part of saspy since version 1. It's the first interface I wrote. All of the access methods are documented here:
https://sassoftware.github.io/saspy/install.html#choosing-an-access-method

It sounds like you don't have the ability to ssh to the machines where SAS is installed. To use the STDIO access method, over ssh,
you have to already be capable of ssh'ing to the machines where SAS is installed. I can't set up ssh to your servers in you company
for you. You have to be able to do that as a prerequisite to using the STDIO access method over an ssh connection. Is there anyone
there who knows what ssh is and whether you even have permission to use it to connect to the servers in question? They need to
set it up for you or show you how. There are multiple ways you can set up ssh, and I can't show you how to do it at your company.

Or am I missing something?
Tom

**Comment by simontao01** [comment]
Thanks Tom, understood and good weekend.

Best regards,

Simon

________________________________

**Comment by tomweber-sas** [comment]
I'm gonna close this, as I can't help you do this. But, were you able to set up ssh to the machines you're trying to get to?

**Comment by simontao01** [comment]
Ok, you can close it although I'm still unable to get connection with Grid, sounds my authorization doesn't have the right to ssh-add xxx.pem to Grid server...

Now I'm applying to share screen with you for another weird issue: SAS code running well and updating the previous dataset on the same folder in SAS EG but the output was 'eaten' (gone) instead of updating the previous dataset as expected...

Best regards,

Simon

________________________________
