### ISSUE TITLE
SASPy: Connection to SAS Viya3.5 on containers (programming only): Fails: token not found

### ISSUE THREAD

**Issue by SASCloudLearner** [sassoftware/saspy#393]
a)	Configuration used:
In /usr/local/lib/python3.6/site-packages/saspy/sascfg_personal.py, below are parameters used

          SAS_config_names=['httpviya']

httpviya = {'ip'      : 'sas-programming',
            'port'    : '8081',
            'ssl'     :  False,  # this will use port 80
            'context' : 'Data Mining compute context',
            'authkey' : 'viya_user-pw',
            'options' : ["fullstimer", "memsize=1G"]

b) Testing fails as below:
Python 3.6.8 (default, Mar 19 2021, 05:13:41)
[GCC 8.4.1 20200928 (Red Hat 8.4.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import saspy
>>> sas = saspy.SASsession()
Using SAS Config named: httpviya
Did not find key viya_user-pw in authinfo file:/root/.authinfo

To connect to Viya you need either an authcode or a userid/pw. Neither were provided.
Please enter which one you want to enter next. Type one of these now: [default=authcode | userid]: userid
Please enter userid: sasdemo
Please enter password:
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/saspy/sasbase.py", line 530, in __init__
    self._io = SASsessionHTTP(sascfgname=self.sascfg.name, sb=self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/saspy/sasiohttp.py", line 515, in __init__
    self.sascfg     = SASconfigHTTP(self, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/saspy/sasiohttp.py", line 328, in __init__
    self._token   = self._authenticate(user, pw, authcode, client_id, client_secret)
  File "/usr/local/lib/python3.6/site-packages/saspy/sasiohttp.py", line 442, in _authenticate
    raise SASHTTPauthenticateError(msg)
saspy.sasexceptions.SASHTTPauthenticateError: Failure in GET AuthToken.
Failure in GET AuthToken. Status=404
Response=b'<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">\n<html><head>\n<title>404 Not Found</title>\n</head><body>\n<h1>Not Found</h1>\n<p>The requested URL /SASLogon/oauth/token was not found on this server.</p>\n</body></html>\n'

**Comment by tomweber-sas** [comment]
Hey, so this error implies that SASLogon isn't running, or perhaps the connection info isn't correct for the deployment. Can you connect to this via SASStudio? Are you sure about the host and port, and if it's using TLS/SSL? BTW, you can use URL= instead of having to specify IP, PORT, and SSL, if you like. I find it more convenient. Especially since, in Viya, the UI's, like Studio, are accessed via a URL, it's easy to know that and code it. So, for your info above, it would just be url='http://sas-programming:8081'. (from the info in your config above)
Can you go to http://sas-programming:8081/SASStudio in a web browser and connect, or do you get this same error trying that?

**Comment by SASCloudLearner** [comment]
Hi Tom,
Thanks for your response.
 I am not able to access sasstudio using http://sas-programming:8081 but instead i can access it through http://<server hostname>:8081 and from the firefox on server as well, i cannot access sasstudio when i use sas-programming as hostname.

I have created a sas ts ticket as well (7613387662) for this issue with all the information needed but seems like this hasnt been picked up along with other issue (7613387669)with jupyter add on though docker file.

Also, i have done all the deployment using root account. Does it make a difference?

**Comment by tomweber-sas** [comment]
Ok, thanks, I've looked at the tracks. So, this is 3.5 programming only (which you provided here already). I don't believe that kind of deployment has the components to be able to use the HTTP access method. That deployment doesn't have the compute service, nor the other 'mid tier' services that a full Viya deployment has; thus the SASLogon not being there, as that is one of those services. The programming only is more of just SAS and CAS and Studio for you to use.
It sounds like you are trying to install and run Python from in that container? Is that the case? Or are you trying to connect to that container from Python (saspy) from an external client? If you're installing python in the container, along w/ jupyter so you can use jupyter from a browser from an external client, but jupyter is running in the container w/ SAS, then you can configure saspy using STDIO in that case. 
So, let e know the configuration of what you're trying to do, as that will determine if/how this could work.

Thanks,
Tom

**Comment by SASCloudLearner** [comment]
Hi Tom,
Thanks for the confirmation on SASLogon unavailability in 3.5 programming only version. This is what i was suspecting as i couldn't see the browser redirect as well.
So i was actually trying to connect from Python (SASPy) installed on host machine (not on container). I tried to customize the image with Jupyter notebook addition as per SAS documentation, there was an issue while running the docker file (unable to find pip3 though it was installed on host machine) so i have created a ticket for this as well. any suggestions on this?
PS: I am a newbie and this is my first deployment using dockers, so i have learned a bit more yesterday about docker file so will review the SAS's docker file as well and see if something requires a fix

**Comment by tomweber-sas** [comment]
I'm afraid I haven't worked on Viya that much, and what I've been doing recently has been against Viya 4, the whole deployment with all the mid tier (services). That's where the HTTP access method runs, as it uses the public rest api provided by the compute service. For your case, HTTP isn't available, nor is IOM. So, STDIO (from the inside) or over SSH from a remote client, is the only option. I don't know if you can SSH into that container; I suppose if you have the ip of the container and it's not locked out. Sounds like you can augment and manipulate the container (use it a the base image when you  build your own container using it)? Again, I've never used this deployment so I'm not sure what kind of restrictions there are or aren't, nor what's already in it as opposed to what you would need to install in another layer. For instance, you said pip3 wasn't found; is that supposed to be installed in the base container or is that something you'd need to install on top of that image?

**Comment by tomweber-sas** [comment]
@SASCloudLearner I've been digging around to see what I can find with this Viya 3.5 container stuff. I'm guessing this is the doc that you're following? https://go.documentation.sas.com/doc/en/calcdc/3.5/dplyml0phy0dkr/n1764pfqi6bc13n1mvibgybqzics.htm
It certainly looks like what you're describing. I haven't seen that before, as I  haven't worked on Viya directly, so I haven't tried out that container or trying to use it to build out my own. This does seem to show that you can use it as a base for your own container and customize your container to your liking. So you should be able to do either STDIO from inside, or allow SSH connection to get at it from the outside. That doc shows installing saspy and others in the container, so that's the STDIO case. This does all require understanding of docker and some linux admin knowledge, but it shows that it should be doable. I'm not sure why pip3 isn't found in your case. I would start the container and log into it and poke around to see if pip3 is there, if it's just not in the path, so you need to specify the full path to it, or add it to the path. Seems you're trying to install python and pip in the previous step, so I would comment out the failing parts, build the container, then go explore in it to see what was installed, where and see where pip is (or isn't). That's what I would do to try to figure it out. Just iterate one one error at a time and track it down. I've done this kind of thing w/ docker for other things and that's just kinda the way you have to go about it. 
Of course, maybe TS can provide some answers, but if not, I'm happy to help out. So try to build what works, and check it out and see what's there, then figure out the next part. If you want to do a screen share meeting next week sometime, I'm happy to help you debug it.
Tom

**Comment by SASCloudLearner** [comment]
Hi Tom,
We basically are trying to ensure to be able to connect from JupyterNotebook which is outside the container to SAS using SASPy package, so seems like we will need STDIO (which requires ssh access) method from what i see as HTTP is not an option in Programming only environment deployed on container. I tried including additional base image in the dockerfile to be able to install SSH service in the container but i had issue while start the service itself which doesn't seem to be possible with systemctl/ service commands. I will need to try other options.
It would be really helpful to have a screen share and look into it together. Can you let me know what is the best time to plan for this?

Thanks,
Raghu

**Comment by tomweber-sas** [comment]
Hey Raghu, I'm currently trying to get one of these 3.5 program only containers so that I'll be able to at least see what's in it and try out building my own container with it as the base image, seeing if I can get ssh working and connect to it. As I've never even seen one of these, I think being able to try this out, if I can get it, will be the most helpful. Let me see if I can get this image and try some things, and then, hopefully, I can get back with you and have some useful input. 
Thanks,
Tom

**Comment by SASCloudLearner** [comment]
Hi Tom,
I finally was able to install ssh in the container and was able to use ssh protocol in saspy configuration and connect to sas from saspy and jupyter notebook. But i had to configure passwordless ssh to have this connection working for now, but will try to see if i can pass the password, either in saspy session itself or from saspy configuration file. 
I am still eager to hear how it all works for you as well.
Thanks,
Raghu

**Comment by tomweber-sas** [comment]
Wow, that's great. Actually, it has to be passwordless ssh, so you have it right. As for me, I seem to have an image downloaded, and so I see there's SAS in there at /opt/sas/spre/home/SASFoundation/bin/sas_u8, so that's what you're running, I assume. But I'm sure I'm missing (untold) steps in trying to configure this thing; the setinit's expired and I can't start SAS. But, that's independent of trying to use it as a base image and getting ssh all set up, so I could start looking into that. 
Glad to hear you've got it going, that's awesome!

**Comment by tomweber-sas** [comment]
Sounds like you're up and running. Is there anything else you need from me? Do you want to close this? 
Thanks!
Tom

**Comment by frayos** [comment]
Hello,
Just a FYI @tomweber-sas, SAS TS received on the 21st July, 7613393980 which was the same query where we advised on the 23rd to use STDIO over SSH among other things which seems to have answered @SASCloudLearner needs.

Thank you for your time,
Younes

**Comment by SASCloudLearner** [comment]
Hello @tomweber-sas  @frayos 
Sorry, i haven't got back to both of you. For now, i am able to setup a passwordless ssh connection for root to the container, and then connect using SASPy package from Python/ External Jupyter Notebook as well via SSH. 
I am yet to build the final image with all these changes and password less ssh for a different user.
Thanks to you both for your response :) For now, i believe we can consider this closed and i will create a new request if i need assistance and once i figure it all out, i will put an update here with my configuration so it helps someone else as well.

Thank you,
Raghu

**Comment by tomweber-sas** [comment]
That sounds great, thanks Raghu! I'll close this and any info you can provide will be great! Anything you can post is great, and it there's more than you'd want out here, you can always email more to me if that make more sense.

Thanks!
Tom
