### ISSUE TITLE
authkey not found when authinfo file is not ASCII/ANSI

### ISSUE THREAD

**Issue by tm-schwartz** [sassoftware/saspy#396]
Hi,

I encountered this on windows using IOM connection, python 3.9 and saspy 3.7.2. Not necessarily something that needs to be fixed, just wanted to document this for future users. 

## Issue

If the authinfo file encoding is not ANSI or ASCII the file is not parsed, ```Did not find key <authkey> in authinfo file:C:\Users\my_user\_authinfo``` is displayed, and the prompt for credentials is shown. I created and saved my _authinfo with notepad and again with neovim on windows10 both of which saved it with UTF-16 LE BOM encoding for some reason. I was able to manually enter my credentials and successfully connect to a remote server, but was unable to use automatic authentication until I used notepad++ to change the encoding.

[link to sas community post](https://communities.sas.com/t5/SAS-Programming/Saspy-not-finding-authkey-in-authinfo-windows-IOM/m-p/757937/highlight/false#M239280)

## Cause

[This line](https://github.com/sassoftware/saspy/blob/4d65583b9583daefc1a66c7101332c710fc77657/saspy/sasiocom.py#L96) 
                                       `parsed = (shlex.split(x, posix=False) for x in f.readlines())`
uses shlex to process text. [Shlex doesn't like unicode](https://bugs.python.org/issue742290).

## Solution
Because of the impossibility of determining encoding accurately 100% of the time, the easiest thing is probably to indicate somewhere that authinfo needs to be ASCII/ANSI encoding. Or to mention checking encoding in the trouble shooting section of documentation.

**Comment by tomweber-sas** [comment]
Hey @tm-schwartz, actually the encoding of the file should be utf-8. ASCII and ANSI aren't actually encodings, but rather character set definitions. ASCII is a 7bit char set that does happen to be the first 128 chars of most ANSI (8 bit char set) single or variable byte (utf-8 is one of these) encodings. Fixed width multibyte encodings (like UTF16), obviously don't/can't include ASCII as their low order set. 
I'm happy to add this to the doc for authinfo, saying it needs to be utf-8, to avoid any confusion on that. It is curious that your editor would choose UTF-16 without you knowing. Usually Windows uses it's form of latin1 encoding: 1252 (which is single byte, and thus ASCII is the low order, 7-bit, half of that encoding). 
I'll add this to the doc, since I don't have it in there, and it can cause some less than obvious problems, as you've found out!
Thanks!
Tom

**Comment by tm-schwartz** [comment]
Ah I see, yeah I am not as aware of encoding/char sets as I should be, and now I vaguely remember the single charset lecture I got in school so I'm going have to brush up on it lol. Thanks for the info, and yeah its definitely an edge case for issues. I am confused about the use of  UTF-16 as well, originally used notepad and saved as `all files` successfully. 

I really appreciate this project, its worked seamlessly for me so far. I just started using it this week and will be using it on a daily basis for work.

**Comment by tomweber-sas** [comment]
haha, yeah, no problem. I've been dealing w/ encodings and char sets and transcoding for a long time! I still think in EBCDIC, but that's a whole nuther thing :)  haha. Glad you like the package, I did update the doc file in the repo, though I haven't built and pushed it out to the actual doc site. I'm on the verge of building the next prod version and will update the doc then, Thanks again, happy to keep making this better, even with doc changes; that helps too.
Tom
