### ISSUE TITLE
SAS dataset pulled to python to_df not working IOM COM method

### ISSUE THREAD

**Issue by SusanZZZZ** [sassoftware/saspy#403]
**Describe the bug**
Hi Tom,
I'm trying to pull data from SAS server to local python using the saspy package via IOM using COM.
I was able to connect to the SAS session, and count how many of rows there are in the dataset.
However, when I try to convert the SAS dataset to Pandas dataframe using to_df method the session just hangs.
Can you please help me with this issue?

**To Reproduce**
import saspy

sas = saspy.SASsession(cfgfile=path_to_config)
sasdata = sas.sasdata(libref='sashelp', table='cars', results='text')

These commands work:
sasdata.obs()
sasdata.columnInfo()
sasdata.head()

This doesn't work:
df = sasdata.to_df()

**Expected behavior**
I expected the to_df method to convert the SAS dataset to Pandas dataframe.

**Desktop (please complete the following information):**
 - OS: Windows 10
 - SAS Version: 9.3M2
 - SASPy Version: 3.7.4

Thanks

**Comment by tomweber-sas** [comment]
So, how many rows are in the dataset? If it's a lot, I would first see if if works with a subset of rows; to see if it's really hung, or just slow. You can test that with your above code by either setting results to pandas on the sasdata object and doing head(), or setting dsopts={'obs' : 5} on the sasdata object and doing to_df(). You can adjust the obs to a higher number and see if it's just taking a long time as you get more rows; figuring how long it would be for the whole table.
Since the COM access method uses 3rd party modules and was user contributed, I really can't do much with it in the way of performance, nor really keeping it up to par with the functionality I have in the other access methods I wrote and support. If it's just too slow, or even if it's something else, I would suggest using the IOM access method, as I fully support that and it performs better and better features and functionality. 
But, let's see if COM is really hung in your case, or just slow.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Were you able to check on if it was really hanging or just slow? Or to try the IOM access method instead of COM? 
Tom

**Comment by tomweber-sas** [comment]
@SusanZZZZ do you still need any help with this? Or can we close the issue. Is there anything I can do?

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I'm going to close this, as I haven't heard back in a month. Hopefully you switched to using the IOM access method and are up and running. If you need anything else, just open another issue, or reopen this if need be.
Thanks,
Tom
