### ISSUE TITLE
SASpy on Azure Databricks

### ISSUE THREAD

**Issue by lhg2** [sassoftware/saspy#407]
Description of the issue:
First, this is being tracked also under SAS case - SAS 7613413036. 
SASpy is installed, configured and makes initial connection without issue (using SSH over STDIO). We can run commands against the built-in dataset with cars, etc. When our research team uses an input file (mounted in Azure Databricks), it gets to a certain point, but then errors out at the same stage. The job seems to be looking for an node in the Databricks cluster that existed in a prior cluster build. Databricks clusters are designed to be ephemeral. They are configured, start up, run jobs, then shutdown til next start up. Each start up builds new nodes with new IP's. Since the IP's become part of the Databricks cluster nodenames (hostname includes Databricks cluster ID, as well as the node IP), the hostnames will change each time the cluster is rebuilt. SAS seems to be caching old hostnames from prior clusters perhaps? 

Initial error then the SAS log error is as follows-
import saspy
import pandas as pd

# hr_pd = pd.read_csv("./HR_comma_sep.csv")
# hr = sas.df2sd(hr_pd) 
df_pd = pd.read_sas('/dbfs/tmp/discharges.sas7bdat')
df_pd.fillna(value=0,inplace=True)
df_pd.replace(to_replace='',value='''missing''',inplace=True)
df_pd2 = df_pd
df_pd2
df = sas.df2sd(df_pd2)

 
error occured in SAS during data transfer. Check the LOG for issues.
/databricks/python/lib/python3.7/site-packages/saspy/sasiostdio.py:970: UserWarning: Noticed 'ERROR:' in LOG, you ought to take a look and see if there was a problem
  warnings.warn("Noticed 'ERROR:' in LOG, you ought to take a look and see if there was a problem")

NOTE: Unable to connect to host 0817-174838-mover297-10-152-182-8. Check validity of host name.
ERROR: Host name 0817-174838-mover297-10-152-182-8 not found.
NOTE: The SAS System stopped processing this step because of errors.
WARNING: The data set WORK._DF may be incomplete.  When this step was stopped there were 0 observations and 141 variables.

SAS Host is a Linux VM in Azure  with RHEL-8.4
SAS version is 9.4
SASPy version is 2.2.7 - 3.7.5

thanks,
Lloyd

**Comment by tomweber-sas** [comment]
Hey Lloyd, I can help with this. Can I see your configuration definition you're using to connect to SAS? Since these 'machines' are all ephemeral, DSN may very well not work in that environment (I don't know enough about the environment either way). But if that's the issue, have you tried using the 'tunnel' and 'rtunnel' configuration options which allow saspy to use the existing SSH connection, which you say is working, as the socket connection that's needed for moving data between SAS and Python? 
https://sassoftware.github.io/saspy/configuration.html#stdio-over-ssh
Also, and again I don't have enough info about this environment, but there a 'localhost' config option as well, which can be used to provide the ip of the client side, for cases where DSN doesn't resolve the host name. So they might also be something that could solve this.

I'd really have to have a little more detail on the overall configuration to be more specific. If you'd like to get on a teams call so I can see more, I'm happy to do that. If you want to try the config options and see if they get you past this, give that a try. Since the error is it can't resolve the host name, those may very well address it.

Oh, and one thing I saw in the track, was something about this being jupyter notebook in databricks.  Again, I don't know the whole environment you're using, but databricks is it's own notebook server, different than jupyter; doesn't mean you couldn't have started up jupyter though. But I mention this because I support Jupyter, DataBricks, and Zeppelin with saspy. All 3 Notebook Servers have different HTML rendering API's so saspy has to make different calls to display output. So, if it's really DataBricks, you should configure saspy for that so it works correctly, since the default (Jupyter) won't render things right on DataBricks:
See the 'display' configuration key in that same config doc link above, or, here it is for quick reference:

display -
This is a new key to support Zeppelin (saspy V2.4.4). The values can be either ‘jupyter’ or ‘zeppelin’, or, as of version 3.1.7, ‘databricks’. The default when this is not specified is ‘jupyter’. Jupyter uses IPython to render HTML, which is how saspy has always worked. To support other Notebooks display methods, different display interface have to be added to saspy. If you want to run saspy in Zeppelin, set this in your configuration definition: ‘display’ : ‘zeppelin’,

Thanks,
Tom

**Comment by lhg2** [comment]
SASPy config-
ssh      = {'saspath' : '/usr/local/apps/SASHome/SASFoundation/9.4/bin/sas_u8',
            'ssh'     : '/usr/bin/ssh',
            'host'    : 'sasuser@my-sas-host.domain.edu', 
            'identity': '/databricks/python/lib/python3.7/site-packages/saspy/id_ed25519_saspyuser',
            'options' : ["-fullstimer", "-nodms"]
            }


We have only tested the above, without tunnel/rtunnel. 

Yes, this is all being initiated from Jupyter notebook within Azure Databricks environment. I don't think Zeppelin is available for our researchers in this environment. 

An MS Teams session to show you is a good idea.  I'd have to coordinate that with our developer running the SAS job. If we should test with tunnel/rtunnel, i can try that. Help me understand if this is comparable to an SSH tunnel back to the SAS Host. 

thanks much,
Lloyd

**Comment by tomweber-sas** [comment]
Hey Lloyd, sure see about seeing that up, it will help. And, try the 3 options I mentioned to see if they solve it. Yes, tunnel and rtunnel ARE the ssh -t and -r options. It explains that in the config doc, here it is below. Also, Zeppelin is a completely different notebook server; it's on hadoop. Jupyter is Jupyter. But DataBricks, is it's own Notebook server. They all look the same to the end user, for the most part; they are all notebooks. So, if it's really Jupyter, then your set, but if it's actually DataBricks, then you would want to set 'display' : 'databricks' so things render correctly for you. Guess you'd already see that if it was an issue, so I suppose you're really running Jupyter itslelf and not using the databricks notebooks.
Tom

tunnel -
(Optional: integer) Certain methods of saspy require opening a local port and accepting a connection and data streamed from the SAS instance to saspy. If the remote SAS server would not be able to reach ports on your client machine due to a firewall or other security configuration, you may pass a port number to used for SAS to connect to on the remote side, which will be forwarded to the local side (using the -R ssh option) so that the remote SAS server can connect using this port.

rtunnel -
(Optional: integer) Certain methods of saspy require opening a remote port and allowing a connection to be made and data streamed to the SAS server from saspy; the Reverse of the tunnel case. In these cases, saspy needs to provide a port for the SAS server to use to accept a connection so data can be streamed to the SAs server. This is simply the reverse of the tunnel case, where SAS creates the socket and saspy connects. This will use the -L ssh option so that the saspy can connect to the remote SAS server on this port.

localhost -
This is a rarely needed options for providing the ip of the client machine (where SASPy/python is running). Normally this is resolved by gethostname() but in the case where the ip from that isn’t correct, you can override it by providing the ip here. The only case this has been seen is on a home network with no domains nor dns, such that a local machine name (‘MyPC’) ends up resolved to some arbitrary internet ip (i.e.: 128.64.32.16), not the actual local ip (i.e.: 10.0.0.10).

**Comment by lhg2** [comment]
Thank you - would you recommend that we just start with tunnel/rtunnel first and use any available open port on the SAS Host side? Other than adding that to the SASPy config, is there anything else on the SAS Host that needs to be modified? Since the Databricks hosts get rebuilt each time we start the cluster, i am not sure adding localhost would make a difference. We won't know what IP will be used upon startup since it grabs new IPs from the Databricks subnet.

**Comment by tomweber-sas** [comment]
Yes, the first thing I would try is the tunnel/rtunnel to see if that addresses it. Should take no more than even just adding them in on the SASsession() call itself with your existing configuration definition. The key to the tunneling is that with those, it's all 'localhost', so there's no DSN involved. That's why I'm suggesting trying them, since you have a DNS error.

sas = saspy.SASsession(cfgname='current', tunnel=nnnn, rtunnel=nnnnn)

As for localhhost. you would just need to acquire the host IP (in python code) and add that to the SASsesion . I'd have to go figure out how to get the ip of the machine you on (some python call), but that should be easy too. But, it would have to be in the same network (subnet) as the SAS machine you're getting to, for it to work.  
As for the SAS server, no nothing has to be done w/ it. SAS had no idea saspy exists; there's nothing in SAS that has anything to do with it. That's why it works with existing 10 year old SAS deployments :)

**Comment by lhg2** [comment]
Just tested with tunnel and rtunnel and we have successful results! That is great. We are still testing, but wanted to provide this update.

**Comment by tomweber-sas** [comment]
Yes, the problem you were having would be address by this. If DSN worked, it wouldn't have been a problem, but since those machines are cycling quicker than DSN is able to keep up, it wasn't getting the correct IPs. This eliminates the need for DSN, as the socket's being tunneled are considered 'localhost' host name, on both sides; so no DSN.

**Comment by lhg2** [comment]
Got it! no problem. I was thinking you meant DNS, but wanted to confirm:)

**Comment by tomweber-sas** [comment]
I was saying DNS in my head, but my fingers just weren't cooperating, over and over

**Comment by lhg2** [comment]
Tom - I think we are good. wonder if you can answer one more question for us? We were under the impression all processing is done on Databricks side of things, but when we met with the SAS Tech support on a call, they thought our SAS Host was undersized. If it was only used to host the SAS software, does it matter what size VM instance the SAS Host is? Or is there some processing done on the SAS Host side of things where we need to think about properly sizing that VM?

**Comment by tomweber-sas** [comment]
Hey Lloyd, well, it depends what you are doing, In general, everything saspy does (all of it's methods), are things where SAS code is submitted to SAS. So, for the most part, yes, everything you do with saspy, accessing SAS resources and running SAS code, happens on SAS. That's kinda the whole point. But whatever you do in Python, other than saspy stuff, happens in Python. Obviously, even the saspy code IS Python, so that is executing there too, but it generates SAS code and submits it to SAS. When you pull data from SAS over to Pandas DataFrames, then that's a Pandas object in Python, and anything you do with that is only on the Python side; same as all other Python things you do. 
It should be pretty clear what's happening in SAS and what you're doing in Python, based upon whatever code you are executing. Do you have some example code, and I can be more specific?

**Comment by lhg2** [comment]
Yes, this is very helpful. My thinking initially was that we were leveraging the power and scalability of the Databricks cluster for processing SAS code within the Jupyter notebook. The SAS datasets are mounted in the Databricks Filesystem. It seems that we do need to give attention to the size of our SAS Host that runs the software as well. Let me see if our developer can share the code.

**Comment by tomweber-sas** [comment]
Ah, yeah, not really. SASPy is a Python interface TO SAS, not an implementation OF SAS in Python. The later would be quite a trick :)

**Comment by lhg2** [comment]
So, is the datasets actually transferred to the SAS Host VM then? They current live on the Databricks platform. Would it be recommended they live on the SAS Host? Or does that not really matter since some processing is happening both on the SAS Host as well as the DB platform?

**Comment by tomweber-sas** [comment]
SAS processes the SAS data sets. Python doesn't process SAS data sets. Python processes Pandas DataFrames. How is SAS accessing the SAS data sets? You're saying SAS is on prem, but Python and the SAS data sets are on the cloud in DataBricks?
If that's the case, then that would be a poor configuration. SAS data sets ought to be where SAS is for performance. But, as long as SAS can access them, it would work.

**Comment by lhg2** [comment]
Our env is 1x SAS Host VM (note this is an Azure VM with Linux and SAS-9.4). Azure Databricks is the cluster built for processing SAS datasets from the Jupyter Notebook. The SAS host and the Databricks cluster (where the user is working) are all in Azure, and the datasets are mounted in Databricks.

**Comment by jld23** [comment]
The processing could be happening on the Azure Databricks (AD) node if you've configured the SAS/ACCESS engine to do so. I found this SAS Communities [article](https://communities.sas.com/t5/SAS-Communities-Library/Accessing-Azure-Databricks-from-SAS-9-4/ta-p/758137) for how to set it up.
If you're not using the access to do "in-database" processing, then data is being moved out of AD into SAS for processing.

**Comment by lhg2** [comment]
Excellent article - looking forward to reviewing and fine-tuning. One other thing to note, is that our researchers do not have access to the SAS Host VM. They only have access to the cluster. Since the article is entitled "Accessing Azure Databricks -from- SAS 9.4" not sure that would be a requirement. Our researchers are working the other way around - accessing the SAS software -from- Azure Databricks. We will review this article though. In the opening remarks is this - "A new SAS/ACCESS engine for Databricks is schedule for the Aug-Sept release." Do you know if this is available?

**Comment by tomweber-sas** [comment]
So, are you saying that you have your SAS Data Sets that you want to process w/ SAS, stored on the Databricks filesystem w/in the data bricks cluster, as opposed to anywhere that the SAS VM can access and read them itself? There's no filesystem with the datasets mounted to the SAS VM?

Looking back at the only code I've seen, at the beginning of this, which I didn't notice because your issue was w/ DNS (typed it right this time:) ) and SSH, it appears you are using Pandas to read SAS Data Sets into Python, and then trying to use saspy's df2sd() to move that data over to SAS, creating a copy of that SAS data set on the filesystem of the SAS VM, to then be able to process, however it is that you're planning on processing it.

As opposed to having the SAS data sets available to the SAS container so it can just directly read them to begin with when you're doing whatever it is you would be doing after you got the data over there that other convoluted way. Why wouldn't you have the data sets on, or mounted to, the SAS vm so it can already just read them itself when you're trying to use them?

That didn't occur to me, which is probably where some confusion, on my part at least, was about this.

**Comment by lhg2** [comment]
Glad we are having this discussion in case we made a wrong turn somewhere. By the time our researchers worked with our DevOps team to create this solution, they already had the datasets mounted in Azure Databricks. They do not exist on the SAS Host Linux VM at all. The researchers do not have access to the VM and only work in Databricks. The SASPy library is enabled, configs copied in place when the cluster starts, and SAS connection is made with SSH over STDIO and using ssh keys - this is initiated FROM Databricks TO the SAS Host. The connection is made and then the researchers are writing code in Jupyter notebooks to process the data. Once we got the rtunnel/tunnel ports configs in place, this tested successfully. Is this approach not typical? Do users typically work directly on the SAS Host, then connect to the Databricks environment, with datasets residing on the SAS Host? To date, the only thing we used the SAS Host for was to host the SAS software since there is no direct way to use it within the Databricks cluster.

**Comment by tomweber-sas** [comment]
No, everything you're saying is correct, except for where the data sets are. The users don't have to get at the SAS machines in any way; that's what SASPy is; that's what you're using it for. It's the Python interface to SAS. Users are only in Python typing Python code. 

To use SAS and access SAS data sets, SAS has to be the one reading the SAS data sets. It's not about users, it's SAS reading it's files off disk. You have SAS's data sets somewhere it can't read them. 

If you had the files mounted to somewhere SAS can read them; its filesystem on the vm or some filesystem mounted to the vm, then everything you're wanting to do would already work, without users having to read the SAS datasets into python using Pandas, bootleg read_sas() method (not even correctly or at all sometimes), and then transfer them to the SAS VM's filesystem, writing them out there as SAS data sets on that VM's filesystem, so that THEN, they can FINALLY start to use them to do what they are trying to do with SAS; from Python. And they have to do this whole crazy data movement piece every time they connect and try to do anything.

Have the SAS data sets where SAS can read them. There's nothing users have to do or be able to get at. And they never have to do all this moving the data from the wrong filesystem to the only one that matters (where SAS can read the files), so they can be processed by SAS.

**Comment by lhg2** [comment]
ok I think I understand. Since the users don't have access to the SAS Host VM, there would be no way to move there datasets into that environment, so I think that is why they decided to use the Databricks Filesystem. I do think that moving the data around and back and forth between environments is not ideal. Maybe we can build a pipeline in Azure Datalake to the SAS Host and have dataset reside there, mounted as a filesystem on the SAS Host VM. Just thinking out loud here.  Of course, if those datasets are small, then this might not be a big issue anyway.

**Comment by tomweber-sas** [comment]
Again, I have about 12 pieces of your 1000 piece puzzle put together on my end :)  I don't know where these data sets came from, or why they are in a filesystem SAS can read, or who put them there or ...
Given this is what you have, I might suggest a better way to do all the data movement every time they want to run anything. saspy has both an upload and download methods. You could simply upload the sas7bdat file to the SAS vm instead of using pandas to try to read it, and then using df2df to transfer it to the SAS vm. Just a thought, but whatever way they want to do it.

**Comment by lhg2** [comment]
these comments are all very helpful. I'd like to compile them for our research and dev teams to consider. Using SAS in this way is different than what we usually do. We are open to suggestions on more efficient or better performing ways to achieve this. The setup we have though, is not complex, and apparently, SAS can read the data so we are good there. We will still explore options to this setup based on your observations. I'm not a SAS user, but just the DevOps guy helping to facilitate this connection.

**Comment by lhg2** [comment]
Also - in the article i was given above to read, the opening paragraphs said - "We will review this article though. In the opening remarks is this - "A new SAS/ACCESS engine for Databricks is schedule for the Aug-Sept release." Do you know if this is available?

**Comment by tomweber-sas** [comment]
Well, the comment about 'SAS can read the data' isn't the case, from what what I've been hearing. What you showed is Pandas reading the data sets into python and then using saspy to move the data over to the SAS machine, writing them out as SAS data sets on the SAS VM's filesystem, so that then they can be read by SAS. But, unless I can actually see what you're doing and how this is set up, I'm only speculating based upon what you're trying to describe to me. Why the SAS data sets wouldn't be accessible from the SAS server still confuses me.

As for that article, I don't know about any of that. If just showed trying to use jdbc from SAS to read a file from the databrick filesystem. I don't see that databricks is a database in any way, such that there could be any kind of real 'in-database' technology there, no EP's or any of that. I would have to guess that an access engine would just still be reading files from the databricks filesystem using whatever remote protocols are provided, that's all. But, I haven't even heard of it till now, so I can't say for sure. Since that's on the communities web site, you can post questions to it and whoever posted that ought to then provide some answers.

**Comment by lhg2** [comment]
Do you have an architecture diagram on the recommended or best practice for this?

**Comment by tomweber-sas** [comment]
It's not that complicated. SAS data sets are files on disk. For SAS to read them they need to be accessible to SAS; on a filesystem SAS can see (so it can open the file and read it). You're telling me the filesystem where you have your SAS data sets, can't be accessed by the machine you run SAS on. 
So, you have to copy the files or the data from where they are, to SAS (one way or another) and have them written to the filesystem SAS can read, before you can ever actually process them w/ SAS. 
I just don't know how to explain it any more than that.  The best practice for having SAS process it's data is to have the data where SAS can read it.

**Comment by tomweber-sas** [comment]
Hey Lloyd, is there anything else you need on this, or can we close this issue. Using tunneling over SSH is the way to address not being able to resolve hostnames on a system like this. Could be others, but that solves it nicely. 
Thanks,
Tom

**Comment by lhg2** [comment]
You've been extremely helpful and insightful. I've shared your thoughts with the team and they are reviewing things. Yes, we are working fine for now, but our discussion here may prompt an architecture change on where the datasets live, especially since they seem to be processed on the SAS Host. Please close out. Your help was much appreciated.

**Comment by tomweber-sas** [comment]
Thanks, and no problem. If you need any more help on this, just reach out again.
Thanks!
Tom
