### ISSUE TITLE
Calling Python script Via SAS Enterprise Guide using X command Part - 2..

### ISSUE THREAD

**Issue by pradkum001** [sassoftware/saspy#414]
Hi @tomweber-sas.,
Hope you are doing good. 

Following up with issue  - https://github.com/sassoftware/saspy/issues/405.

As I have mentioned earlier., the aim is to decrypt variables in a dataset. And we pass those variables via python script to a third party tool where it does the decryption part and returns the values. This was working fine in tableau as we could deploy the python function on tableau server (using tabpy component - client.deploy https://tableau.github.io/TabPy/docs/tabpy-tools.html). But with SAS we cannot deploy the python function and hence we need to call it. And since we use the older version of SAS we cannot use the latest procedures and hence I am using X-command to run the python script. Please find the below python script.

`
def var_decryption(inputList)
   import azure.common.credentials
   import azure.keyvault.secrets
   import azure.identity
   keyvalultCredentials = *******
   headers = ****
   body = ****
   url = ****
   response = requests.post(url, data=body, headers)
   jsonData=response.json()
   accessToken = jsonData["access_token"]

   variable = '~!'.join([str(item) for item in inputlist])
   task = {'plaintext': variable}
   header = {
       'accesstoken' : accesstoken
     }
   resp = request.post('http://URL', json=task , headers = header,verify=False)
   resTempList = resp.text.split('~!')
   return resTempList
#for deploying on Tableau server we use the below line
#client.deploy('var_decryption', var_decryption, 'decrypt text via api', override=True)

#from Tableau we call it with the below command
#SCRIPT_STR("return tabpy.query('var_decryption', variable1)['response']",ATTR(varaible2]))
`

The above code is the actual python script that we use for decryption. 
But when it comes to EG, we are using X command which means we cannot tell the script where the SAS dataset is, what the dataset name is and etc. 

Hence, I need your advice in this regards of how to pass the dataset name., path and the variable without changing the core script. I tried passing the dataset name, path and variables into the script using sys.argv() but it didn't work. The aim is to decrypt the output variable of a dataset ran from SAS Enterprise Guide Query.

`Example:
Data New(var1,var2);
  Set db.table;
Run;

The above query is ran from SAS EG Where var1 is encrypted and hence we need to decrypt the value of that using the python script. 
`

Hope you have understood the situation. Let me know if you need more clarification on this..

Thank you in advance Tom.

**Comment by pradkum001** [comment]
I have no idea why the code is striked out. Please find the copy paste version. 

`variable = '~!'.join([str(item) for item in inputlist])
task = {'plaintext': variable}
header = {
'accesstoken' : accesstoken
}
resp = request.post('http://URL', json=task , headers = header,verify=False)
resTempList = resp.text.split('!')`

**Comment by tomweber-sas** [comment]
You can use proc fcmp; just not the python integration that's in the newer versions, which you don't have. There's also a proc HTTP, which you can use to make rest calls; the same one they implemented in their python function. All it's doing is making a rest call to decode the value; you can do that from languages other than python. Maybe you can use that to call the decrypt function for the values you want to decode, from SAS. 

I understand what you want; the implementation the other department wrote, to just work, as is, in your workspace server. But it doesn't. You have to understand what it's doing and figure out how to implement something that accomplishes the same thing in a completely different environment. Maybe you can use the CALL SYSTEM (https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/lefunctionsref/p089n536m1spv9n1cpuo8u34hw5m.htm#p07557v5ngn10mn1e8cu1ye4drw8) routine in the datastep to call your python script for each value to decrypt? That seems like it's the right place in the flow.

I think that this would be a good post for the communities site; https://communities.sas.com
It's for asking SAS users for help with general SAS questions, like how do I make a rest call for each variable  being read in a data step. That's all I think you're really trying to do. Maybe the call system routine is the answer, maybe not. But the Communities Site had thousands of SAS programmers happy to help with things like this.

**Comment by tomweber-sas** [comment]
So the only way you can make this work is with that Python function? I don't know how to implement that with the version of SAS you have that has none of the python integration we've had in SAS for the past 3 years. The FCMP Python function (in M6; 3 years old) would be able to be used to do what you want. I don't know of any other mechanism to make this work as you identify it has to. Then again, I'm not a SAS application programmer, so I could be missing something.
To do it a less than optimal way, would be to execute a python program via the X command and use saspy to go read the table into a dataframe then use that function to iterate over the columns decrypting the values and then writing that dataframe as a SAS dataset, that you then read in after that X command finishes and that's your decrypted table in your SAS session. That's not the same at all, and a whole lot more work. but that's all that jumps out at me since you have none of the python integration to use but have to use that python function.
Or, update your SAS deployment, then you can do it right w/ a an FCMP Python function in the datastep, just like the other implementation. That's all I see.

**Comment by tomweber-sas** [comment]
@pradkum001 is there anything else I can do; I know I haven't done anything but you know what I mean :)
Can we close this issue? 
Thanks,
Tom

**Comment by pradkum001** [comment]
Tom., 
That’s not correct., you gave me a lot of ideas to look into which I absolutely didn’t have any idea about. 

And coming to the actual task.. I have found a inefficient way to work through the task by making modifications to the Python script in such a way that first it reads the sas dataset and converts that to a data frame and then list which is passed onto the decryption api and then the decryption happens. And it generates the decrypted values and creates that variable. 

I run the above script using x command and read the above decrypted value variable and set it to the original dataset which has encrypted and decrypted values. 

It all worked finally..! And thanks to you in the process Tom…!

**Comment by tomweber-sas** [comment]
Ok, so that did work like I thought, but you are right, it's ugly and not the 'good' implementation you could create if you had the newer version of SAS w/ the proc FCMP, where you could define that python function and use it in the data step; the implementation you want to have. Well, I'm glad the 'work around' worked for you until you can upgrade!

Do you want to close this out? Or is there anything else I can do?

Thanks!
Tom

**Comment by pradkum001** [comment]
yes., until they upgrade the package. And sure We can close it Tom. 

Thanks again.

**Comment by tomweber-sas** [comment]
Cool, let me know if you need anything else!
Tom
