### ISSUE TITLE
OOO

### ISSUE THREAD

**Issue by FriedEgg** [sassoftware/saspy#427]
Tom, you there?

**Comment by tomweber-sas** [comment]
outhouse didn't work

From: Matthew Kastin ***@***.***>
Sent: Friday, December 3, 2021 3:48 PM
To: sassoftware/saspy ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [sassoftware/saspy] OOO (Issue #427)


EXTERNAL

Tom, you there?

-
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsassoftware%2Fsaspy%2Fissues%2F427&data=04%7C01%7Ctom.weber%40sas.com%7Cfb9deec7cafa494f197008d9b69e416e%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637741613086475056%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=cucGYf7CAUYbsFOkCgE31dDBAzDtg64szib%2BRhcLrLo%3D&reserved=0>, or unsubscribe<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAEHDYZVREETIBZ7XOBFPNJLUPEUJVANCNFSM5JKTAC4A&data=04%7C01%7Ctom.weber%40sas.com%7Cfb9deec7cafa494f197008d9b69e416e%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637741613086485047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=Ib2GwYci5IWNqZLY2yiUs%2FgWVpb3iktGTQ92sdEExmQ%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Ctom.weber%40sas.com%7Cfb9deec7cafa494f197008d9b69e416e%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637741613086495047%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=VW7sznDLJ6%2Fx9P5CVNJ3K9uv%2FWVKLyo2y7wv2gT3yjI%3D&reserved=0> or Android<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Ctom.weber%40sas.com%7Cfb9deec7cafa494f197008d9b69e416e%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637741613086505050%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000&sdata=19IJBpvRG1QOWNZ3ZgOIKhZ729%2BOSkcsyIvE2rf5Apk%3D&reserved=0>.
