### ISSUE TITLE
Decoding problem in COM mode

### ISSUE THREAD

**Issue by saspyrate** [sassoftware/saspy#454]
**Describe the bug**
Results of `submit()` are not decoded correctly when using COM, since the SAS encoding is used instead of UTF-8.

It's not possible to change the encoding via the config as follows:
```
sascfg = {
  "iomhost": "...",
  "encoding": "utf-8"
}
```
Namely, `SASsession.__init__()` overwrites the setting and logs the following message:
```
The encoding value provided doesn't match the SAS session encoding.
SAS encoding is latin9. Specified encoding is utf-8.
Using encoding iso8859_15 instead to avoid transcoding problems.

You can override this change, if you think you must, by changing the encoding attribute of the SASsession object, as follows.
If you had 'sas = saspy.SASsession(), then submit: "sas._io.sascfg.encoding='override_encoding'" to change it.
```
(By the way, probably the message should be logged with `logger.debug` instead of `logging.debug` to make it visible.)

Indeed, the following code fixes the issue for me:
```
sas = SASsession()
sas._io.sascfg.encoding='utf-8'
```

Is there a cleaner way to fix this? In particular, I'd like to have it work with the SAS Kernel for Jupyter.

I'd appreciate any suggestion or fix. Thank you.

**Comment by tomweber-sas** [comment]
Oh, I think I misunderstood what you were saying. I thought it was not working right except for using utf-8. The HTTP access method doesn't do transcoding, like the others, because the http api it calls transcodes everything to/from utf8 and whatever SAS is running in. So, I was thinking this was something like that.

What I see now is that you were trying to provide the wrong encoding to saspy, which isn't valid. It then fixes that to use the correct encoding that matches what SAS is running in. If you override the encoding to one which isn't what SAS is running in, then you will end up with transcoding problems (unless everything you do is 7bit ASCII). 

So, can you explain why you want the wrong encoding? Your SAS session is apparently running in latin9, so the encoding value for saspy has to match that. That's what that value is for; it's the python encoding name that is the same as what SAS is running in so I can correctly transcode between SAS session encoding and UTF-8 (Python). If you want to run SAS in some other encoding, you have to do that w/ SAS. 

Thanks,
Tom

**Comment by tomweber-sas** [comment]
And, looking at the COM code and running some example cases, it seems that transcoding is being done somewhere in the middle as there's only one place in the code where it sometimes transcodes anything itself. So, are you getting a transcoding problem or is it just the message when you provide the wrong encoding in the config? I'm trying to test out some things myself, but if you are getting an error of some kind, showing what it is, and what code is being run would help.
Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, I finally found a problem with it using the session encoding to transcode the html output it gets. The HTML output (at least in current versions of SAS; used to be session encoding on older versions) is already in utf8 while other places where COM is transcoding the same stream it reads (as it get's html from) it needs to transcode using SAS Session encoding. I've got a fix for this so that it uses utf-8 for html results, but to support the older versions of SAS, tries session encoding if that has an issue. The only problems I've see with this are fixed by that change. So, I've pushed that to main.
I'm guessing you were getting errors trying to use this in the SAS_Kernel, as HTML is the only thing it can return, unlike in saspy where results can be text or Pandas or HTML. That's why I didn't find this till stepping through many different cases.
Can you pull from main and see if this fixed whatever you were seeing?

Thanks,
Tom

**Comment by saspyrate** [comment]
> I'm guessing you were getting errors trying to use this in the SAS_Kernel, as HTML is the only thing it can return, unlike in saspy where results can be text or Pandas or HTML.

Exactly.

> Can you pull from main and see if this fixed whatever you were seeing?

Yes, the problem disappeared and everything seems to work fine here.

Thank you very much indeed for dealing with this so quickly!
