### ISSUE TITLE
Create Spark Table on SAS from Python

### ISSUE THREAD

**Issue by AnandReddy23** [sassoftware/saspy#461]
We read/write SAS datasets to HDFS paths. We user SPDE libraries to connect and process the data.

However, from ptyhon we use saspy to access the same data sets. Reading large data is relatively slow.

Can we create spark tables from Python on these SAS datasets stored on HDFS ?

I mean like create RDDs on the edge nodes RAM out of these SAS datasets ?

**Comment by tomweber-sas** [comment]
Hey @AnandReddy23, it's been a good 8 years or so since I worked on I/O to Hadoop. I know the SPDEngine supports a number of means to interact with SAS data on HDFS (distributed data sets), from just engine things, to using the EP (Embedded Process) to support InDataBase functionality in Hadoop. However, I not really up on what the latest/greatest functionality is with any of that these days. Here's a link to some doc on that (just FYI): https://go.documentation.sas.com/doc/en/pgmsascdc/9.4_3.5/engspdehdfsug/titlepage.htm

As for spark, I also happened to prototype SAS RDDs back then too, but that never went anywhere as we had what was considered, at the time, a competing parallel SAS platform (CAS). So I don't believe we have any direct integration with Spark. But, it would be best to check with others about what any current functionality in this area happens to be. I'm not the right resource for this anymore. I think that opening up a Tech Support ticket about ways to do what you're looking for might be the best course of action.

SASPy doesn't have any interaction with Spark either, other than simply they are both Python interfaces you can use to build out workflows in Python. But like you mentioned, accessing large data from Hadoop to Python isn't as fast as using other dedicated interfaces that actually take advantage of the distributed nature of Hadoop. Our EP does that by supporting parallel access to the data and by providing InDataBase push down of processing directly into the cluster; though full reads/writes of data wouldn't take advantage of that.

Tom
