### ISSUE TITLE
Databricks display setting leads to  NameError: name 'displayHTML' is not defined

### ISSUE THREAD

**Issue by cwilson-cra** [sassoftware/saspy#462]
**Describe the bug**
The displayHTML function available within Databricks doesn't seem to be recognized when running submitLST. Instead, I get a NameError, indicate that the displayHTML function isn't found/defined. 

**To Reproduce**
1. Go to Databricks, importing saspy into the notebook
2. Create a SAS session, setting the value of the dsiplay parameter to 'databricks'.
3. Import any data into SAS session
4. Run submitLST to execute a simple command, like proc print, within a Databricks cell.

**Expected behavior**
Expected for HTML to render using Databricks' built-in displayHTML function.

**Screenshots**
![image](https://user-images.githubusercontent.com/43970323/169350786-33f34856-9d2f-4f30-95e5-05c624439e47.png)

**Desktop**
 - OS: Linux
 - SAS Version: SAS On Demand for Academics
 - SASPy Version: 4.3.0

**Additional context**
I can run the displayHTML command from a cell in Databricks - it just seems that it is not available to saspy when it is executed.

**Comment by tomweber-sas** [comment]
Hey, so I've spent the past hour trying to get a cluster started on the free trial azure databricks, so I could run a notebook to type in two lines to see what I see. The simplest default clusters (even single node) won't start for me, so I can't run a notebook. I'll keep trying, I don't know what it's issue is. 
Here's the doc for the displayHTML: https://docs.microsoft.com/en-us/azure/databricks/notebooks/visualizations/#displayhtml-function
It's their function for displaying HTML in their notebooks. Since I can't seem to get a simple cluster to run so I can execute a command in a notebook, Is there anything else you can provide about your environment that can help?

If you use results = submit(), to run something, then results['LST'] will be the HTML output (run something that creates output). How can you render that HTML in your environment? If it's a python notebook, it should be `displayHTML(results['LST'])`


![image](https://user-images.githubusercontent.com/17710182/169568765-301d9cec-475a-484b-a27f-2f453ac112f2.png)

![image](https://user-images.githubusercontent.com/17710182/169568845-e9c983c1-eb3e-43bd-8406-e48b688f34a1.png)

![image](https://user-images.githubusercontent.com/17710182/169568978-c5d14e50-79f4-4d5b-a72e-04654bfda837.png)

**Comment by tomweber-sas** [comment]
Hey @cwilson-cra, I'm requesting an account from our IT group so that I'll be able to get onto databricks and look into this. Hopefully that will happen soon and I'll be able to investigate!

Thanks,
Tom

**Comment by tomweber-sas** [comment]
So, good news, bad news. I've gotten an account on azure and I've been able to reproduced this. However, I'm not seeing how to remedy it, YET. Only just starting to try to figure out what the actual problem is. Seems a scoping issue or something I'm not that familiar with. Googling, I'm finding other issues for this on [stackoverflow](https://stackoverflow.com/questions/71474139/how-to-import-displayhtml-in-databricks) too. 

I've looked back to when I added this support, almost 3 years ago, thinking something changed. But even though I added the sas.DISPLAY() and sas.HTML() methods for this (I had them for Jupyter and zeppelin at the time, just added them for databricks), the user I was working with (I didn't have access to databricks at the time) may have only kept typing in displayHTML() in their notebooks manually; which seem the only way this thing works. I can't find record of sas.DISPLAY(sas.HTML(html_output)) from any of our communications back then. I 'may' have assumed it worked since typing in displayHTML() worked; it's just too long ago to remember. So, I'll assume this has never worked instead of something changed. Either way, it doesn't work now and it seems to be a known issue.

I'll try to open communication w/ databricks to find out what the deal is. I found a hit on their site about this and the answer they provided was like that note in the doc for displayHTML about it being serviced from some domain, bla bla bla. I don't know what that's about really, but seems like this isn't a normal Python function but rather some special 'their notebook only' thing that isn't part of Python but rather higher level in their UI.

I've been playing around with different ways to try to get this to work, but haven't found the magic incantation yet. It says it's a bound method of PythonShell, but I can't import that to gain access to it. I can't reference it from that. Nothing seems to get it to function other than typing it directly into a cell in one of their notebooks (it doesn't seem to be a real Python function). I can't find any other way to render HTML, like actual Ipython display/HTML .

I'll continue to investigate though, and will try to figure something out.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
I posted a [question](https://community.databricks.com/s/feed/0D58Y00008l8WMwSAM) to their Communities forum; I can't find a way to open an issue (like this) for developers. So I don't know that I'll get a real answer or not. But, digging further in that site for this issue I've come across this other [question](https://community.databricks.com/s/question/0D53f00001QkSIuCAN/how-to-handle-ipythoncoredisplayhtml-object) which is almost the same, but it also seems to imply that the only way to be able to render an html object in their notebooks is for the end user to have access to the html object and hand type `displayHTML(obj)` into a cell. 

Seems crazy to have no way to do this programmatically, but that seems to be the case. Maybe we'll get someone on the community to provide some clarity via the question I posted. I guess for now you'll have to use `res = submit()` and type 
`displayHTML(res['LST'])` to use databricks. Seems a shame, but I haven't found a workaround so far :(
Tom

**Comment by cwilson-cra** [comment]
Thanks so much for looking into this Tom! Yeah that's definitely odd that the `displayHTML` function is only available to the end user. I'll plan on manually rendering the the HTML via `displayHTML(res['LST'])` as a workaround and hopefully Databricks provides a fix for this moving forward. Thanks again!

**Comment by tomweber-sas** [comment]
Hey, I was just looking into this again this morning. Still couldn't figure a way around this on my end. But, I did post one more time to the issue I opened with databricks. Maybe they will provide a way to have executing code render results, like in other notebooks. But, I can find no indication of that yet.

BTW, this is also problematic when using other methods which render results, like the analytic methods which return a results object with all of the plots, tables, ... as attributes. SASPy will render those when you submit them; which also fails here. So, for functions that try to render results (which work fine anywhere else), you can set batch mode to True, and then those methods will return the HTML (maybe as one object, maybe as dict of LOG/LST; varies by method), and that way you can get back the string of HTML to render manually.

```
cars = sas.sasdata('cars', 'sashelp')
res = stat.reg(model='horsepower = cylinders', data=cars)
dir(res)
# this will render the graph in the cell, but not on databricks
res.DIAGNOSTICSPANEL

# for databricks, you need to do extra work. Set Batch and then call their method on the HTML string you can access
sas.set_batch(True)
displayHTML(res.DIAGNOSTICSPANEL['LST'])
sas.set_batch(Fals)

# or the same thing for other methods
cars.hist('cylinders')  # except for databricks

sas.set_batch(True)
displayHTML(sd.hist('cylinders')['LST']) # this method also returns the LOG/LST dict in Batch mode
sas.set_batch(Fals)
```
Tom
