### ISSUE TITLE
How to set the local language of SAS LOG and output (LST/HTML)?

### ISSUE THREAD

**Issue by ShuguangSun** [sassoftware/saspy#485]
As what to do in SAS cfg the "-LOCALE en_US", it can force the SAS LOG and outputs in English, and "-ENCODING UTF-8" can make the encoding of UTF8 in the same session.

How can I do that in saspy? I tried below in saspy configure but it does not work
```
winlocal = {
    "options" : ["-config", r"C:\Program Files\SASHome\SASFoundation\9.4\nls\u8\sasv9_en.cfg"]
}
```
Where the LOCAL nad ENCODING are set accordingly in the file "sasv9_en.cfg".

**Comment by tomweber-sas** [comment]
The IOM access method doesn't have an 'options' key, because IOM doesn't allow overriding startup options. Windows SAS has a sasv9.cfg file in the installation ('C:\Program Files\SASHome\SASFoundation\9.4\sasv9.cfg', by default), where you can specify which nls config to use. So you just provided that there:
![image](https://user-images.githubusercontent.com/17710182/193600451-09f80d31-c4f0-4fda-b5af-b018d5b6d55f.png)
Only options that can be set after SAS starts up are allowed over IOM, and those you just submit on the options statement. Any startup options must be configured via SAS itself, in it's usual way.

**Comment by ShuguangSun** [comment]
Thanks for the quick response.

**Comment by tomweber-sas** [comment]
No problem. Hopefully you've set this and you're good to go. I'll close this out, but just let me know if you need anything else!
Thanks,
Tom
