### ISSUE TITLE
IOM Error from Windows to Unix

### ISSUE THREAD

**Issue by Jennyyangyzy** [sassoftware/saspy#506]
Hello,

I'm trying to use the IOM method to connect a Unix server where SAS is installed from a Windows client. However, I got the error that "We failed in getConnection. This release of IOM Bridge for Java does not understand the command sent by the peer: 83." when trying to build the connection.

Could you please assist with this issue? Appreciate your help!

**Comment by tomweber-sas** [comment]
Hey, can you provide your configuration, and what kind of SAS deployment you're trying to connect to? That's not a usual error, but it shows you're making a connection to some kind of SAS server (it seems). My guess is your host/port is wrong and not the host for the object spawner, or the port not being that for the workspace server. Any information you can provide would be helpful! Providing the code being submitted with all of the output can also helpful.

Thanks,
Tom

**Comment by Jennyyangyzy** [comment]
Hi Tom, Thanks so much for your reply, I've actually managed to resolve this issue with SSH method instead of IOM. Please go ahead and close this ticket. I do have another issue, I'll open a separate ticket instead.

**Comment by tomweber-sas** [comment]
Ok, thanks for the heads up. I'll close this one, and feel free to reach out again. Jut FYI, if this is a production deployment (Metadata servers, Object spawners, Workspace servers, ...) then using STDIO (over SSH or not) won't be using any of that; it's just starting it's own SAS process from the installation. So, if your workspace server you were trying to use had things like metadata permissions set, preassigned libraries, (no end of things), then you won't have any of that since you're just starting a stand alone SAS process (it won't actually be a Workspace server even though it's started from the same installation on disk). If that's not a concern, or this isn't actually a deployment like that, then STDIO /SSH is fine. 

Thanks!
Tom
