### ISSUE TITLE
python pandas is so slowly

### ISSUE THREAD

**Issue by cfkstat** [sassoftware/saspy#509]
Pandas  is the very low computational efficiency. Why not use polars or data.table for higher computational efficiency, especially in reading and writing IO?

**Comment by tomweber-sas** [comment]
Well, I wrote this 7 years ago, and Pandas was the defacto table interface for Python. I looked up these two you mention. Polars appears to be less than a year old since its first release, so that's only just being made up. The data.table seems like its first version was 5 years ago. I haven't heard of these before, so I haven't looked into trying to interface with them. 
Guess that's the answer to 'why'.
