### ISSUE TITLE
Java version required for IOM

### ISSUE THREAD

**Issue by rebyates** [sassoftware/saspy#589]
Hi,
I'm currently setting up saspy for SAS using the IOM connection. The configuration page highlights it requires Java 7 or higher. Is there a minimum requirement r.e. 32 bit or 64 bit for Java7+?
Thanks.

**Comment by tomweber-sas** [comment]
Ah, good question. Java 7 has long past it's EOL date. It's no longer supported, though it still works w/ SASPy. Just yesterday I was thinking about deprecating 7 from saspy which would clean up some of the mess caused by that log4j issue from a couple years ago. I haven't found 32bit java or 64 bit java have an issue. 

That said, I would install a much more recent version of java than 7 and if you have a choice, I would use 64 bit. 32bit architecture has been out of date for decades now, so why choose that if software supports 64bit. I expect the newer java versions only come in 64.

**Comment by rebyates** [comment]
Thanks for the swift response!
