### ISSUE TITLE
Can not establish a connection at another folder

### ISSUE THREAD

**Issue by turanbul** [sassoftware/saspy#59]
Hello,

I am able to import saspy and establish connection using the example from the GitHub page (saspy_example_github)

![image](https://user-images.githubusercontent.com/13017356/30181188-c2032472-9412-11e7-8e84-3aa23531ef2c.png)

but when I run the script from another directory I got the following:
![image](https://user-images.githubusercontent.com/13017356/30181260-f50e8dd4-9412-11e7-8b3a-01ad343a44eb.png)

Can you explain me why this happens?

**Comment by tomweber-sas** [comment]
@turanbul, this looks to me like you have 2 different sascfg.py files. One in the install directory for python, and one in some directory that's not in the search path (or later in the search path). It look like the one you configured is the later. 
Pythons search path is usually, current dir, followed by the rest of the path dirs. You can see this by submitting:
```
import sys
sys.path
```
I think you will find that you want to configure the sascfg file that is in the install location (in the real search path), so that is found regardless of what directory you happen to start python from.

Thanks,
Tom

**Comment by turanbul** [comment]
You are right! There was a mismatch between the Github pull and pip install module.

Thanks for quick response. You can close the issue.

**Comment by tomweber-sas** [comment]
Great. I love the easy ones :)
Let me know if you need anything else!

Thanks,
Tom
