### ISSUE TITLE
add pyarrow in saspy dependency

### ISSUE THREAD

**Issue by Debbby57** [sassoftware/saspy#612]
hello

I think it will be great to have pyarrow in saspy dependency or in saspy optional dependency like `pip install saspy[parquet]`

what do you think ?

Thank you !

**Comment by tomweber-sas** [comment]
Yes!, I agree that I should have added that when including this user contributed method since it requires pyarrow, even though the rest of saspy doesn't. I have a couple others of those in the setup.py file:
```
      extras_require = {'iomcom': ['pypiwin32'], 'colorLOG': ['pygments']},
```
So, I'm thinking this is what would I would need for that?

```
      extras_require = {'iomcom': ['pypiwin32'], 'colorLOG': ['pygments'], 'parquet':['pyarrow']},
```
Is that what you're expecting? I don't have the most experience w/ how this works. I'm guessing when you issue pip install like that it's telling it to include the optional dependencies you list in that `[]` where you list the keys in the `extras_require` dict?

Tom

**Comment by Debbby57** [comment]
Yes ! I was talking about the extra requires. Sorry if it wasn't clear.
If you add it in the extra require only users who use parquets methods will install this extra dependency.

Thanks for your help !

**Comment by tomweber-sas** [comment]
Hey @Debbby57 I've built this into the newest production release, V5.100.2. Feel free to try it out. I'll close this now as complete. If you need anything else, just let me know!
Thanks,
Tom
