### ISSUE TITLE
Connection to SAS EG from Docker container

### ISSUE THREAD

**Issue by anvoytenko** [sassoftware/saspy#614]
Dear colleagues, please help! I can't establish connection to remote SAS EG server.  **The error message is**
We failed in getConnection

SAS process has terminated unexpectedly. Pid State= (2787, 64000)
SAS Connection failed. No connection established. Double check your settings in sascfg_personal.py file.

Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-classpath', '/usr/local/lib/python3.8/dist-packages/saspy/java/saspyiom.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-1.2-api-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-api-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-core-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.security.sspi.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.core.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.svc.connection.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.rutil.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.rutil.nls.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sastpj.rutil.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-internal-api.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-omgapi.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-orb.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/pfl-basic.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/pfl-tf.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '48333', '-stdoutport', '47985', '-stderrport', '38343', '-iomhost', 'some.server', '-iomport', '8591', '-user', 'user', '-lrecl', '1048576', '']

No SAS process attached. SAS process has terminated unexpectedly.
Invalid response from SAS on inital submission. printing the SASLOG as diagnostic

**I use this code** 
SAS_Enviroment = {
    "java": "/usr/bin/java",
    "iomhost": "some.server",
    "omruser": "user",
    "omrpw": "password",
    "iomport": 8591,
    "encoding": "cyrillic",
}
sas = saspy.SASsession(cfgname="default", results="TEXT", **SAS_Enviroment)

and it succesfuly works in other containers and even on this server where docker container is running on Python 3.6 and saspy 3.5.1. Also I use Java 8, OS version Ubuntu 20.04. I tried saspy 3.7.8, 4.3.1, 5.10.0 with the same result. JAR files are present
-rwxr-xr-x 1 root staff   67163 Jul 29 14:54 log4j-1.2-api-2.12.4.jar*
-rwxr-xr-x 1 root staff  208005 Jul 29 14:54 log4j-1.2-api-2.17.1.jar*
-rwxr-xr-x 1 root staff  276756 Jul 29 14:54 log4j-api-2.12.4.jar*
-rwxr-xr-x 1 root staff  301873 Jul 29 14:54 log4j-api-2.17.1.jar*
-rwxr-xr-x 1 root staff 1682736 Jul 29 14:54 log4j-core-2.12.4.jar*
-rwxr-xr-x 1 root staff 1790452 Jul 29 14:54 log4j-core-2.17.1.jar*
-rwxr-xr-x 1 root staff  997855 Jul 29 14:54 sas.core.jar*
-rwxr-xr-x 1 root staff    6589 Jul 29 14:54 sas.security.sspi.jar*
-rwxr-xr-x 1 root staff 2289298 Jul 29 14:54 sas.svc.connection.jar*
content of sascfg.py is default and the same as on other servers... What else I can check?

**Comment by tomweber-sas** [comment]
Hey @anvoytenko, looking at what's provided above, the config definition looks reasonable. The output about what was trying to be run looks reasonable; the classpath looks as I would expect. In the initial error, We Failed in getConnection ...  there isn't an error message from the IOM client itself. There are a number of 'usual' error messages that may come from that client. Since there's nothing there, and there's not an explicit Java failure (such that the client didn't even run), my first guess would be a network issue; not being able to even get to the server from the client (my SASPy Java code). 

You say this works from other containers, so that's good and shows that you can connect, so most other things fall away there. The question now is, what's different with this container than the others where this works? 
The lack of an IOM error (like you can see [here](https://sassoftware.github.io/saspy/troubleshooting.html#iom-specific-errors)) make me think there's no connectivity from your client to the server. 

That's what I would look at next. 
Tom

**Comment by anvoytenko** [comment]
Hi, Tom! Thank you for attention to my question. All network settings looks similar... also I can connect via SSH to SAS EG, so if it network issue it related to port/protocol. What ports I should check? This '-stdinport', '48333', '-stdoutport', '47985', '-stderrport', '38343' are random?

**Comment by tomweber-sas** [comment]
Yes, those are ephemeral ports, chosen by the OS as available. (random). So, you can ssh from this container to the host where the object spawner is running? Is that true? That's what I expect from your statement. And, just for clarity, you aren't connecting to EG, EG is just a client, same as SASPy. Both clients connect to a SAS Workspace server by connecting to the Object Spawner on the workspace server port (object spawners listen on various ports for connection, and then start up that specific SAS server for the client). Without knowing more, the next thing I'd try is to run the same command SASPy is trying to run, in that container yourself and see if that produces any more diagnostic info. Given your output in the original post, that command would be

```
/usr/bin/java -classpath /usr/local/lib/python3.8/dist-packages/saspy/java/saspyiom.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-1.2-api-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-api-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/log4j-core-2.12.2.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.security.sspi.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.core.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.svc.connection.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.rutil.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sas.rutil.nls.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/iomclient/sastpj.rutil.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-internal-api.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-omgapi.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/glassfish-corba-orb.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/pfl-basic.jar:/usr/local/lib/python3.8/dist-packages/saspy/java/thirdparty/pfl-tf.jar pyiom.saspy2j -host localhost -stdinport 48333 -stdoutport 47985 -stderrport 38343 -iomhost some.server -iomport 8591 -user user -lrecl 1048576
```
There is an expected error this should produce, see number 4 [here](https://sassoftware.github.io/saspy/troubleshooting.html#classpath-problems). Getting the socket error is the expected failure, since saspy didn't start java (you did), so there's no listening socket. If the error is anything other than that, then we'll see what it is and go from there. 

Is there any information you can provide about what's different about this container then the ones that work?

**Comment by anvoytenko** [comment]
Hi! The problem was solved by changing network mode of container from host to bridge. Some security changes were provided and they block communication through those ephemeral ports for docker. That's why ssh was working. I took tcpdump and there was seen thats SAS server sent answers but they weren't accepted by client because lack of information through ephemeral ports. Thank you for support!

**Comment by tomweber-sas** [comment]
Yes, that would explain it! Glad you got it tracked down. Thanks for letting me know!
Tom
