### ISSUE TITLE
to_df String Trailing Space

### ISSUE THREAD

**Issue by kevinjfoley** [sassoftware/saspy#66]
I'm getting trailing spaces when using the to_df method with strings.  

Below is an example:

---

```python
import saspy
```

```python
sas = saspy.SASsession(cfgname="winlocal")
sas.set_batch(True)
```

```python
generate_data = sas.submit('DATA test; var = "no_space"; RUN;')
# print(generate_data["LOG"])
sas_dataset = sas.sasdata('test')
```

```python
sas_df = sas_dataset.to_df()
```

```python
print(repr(sas_df["var"][0]))
```

    'no_space '

**Comment by tomweber-sas** [comment]
That looks like my bad. I believe I've fixed this. rather than create a branch and all that, I'll attach sasioiom.py with my changes for you to try. I'll want to validate a few more cases as well before pushing it. I've made the corresponding changes to the stdio access method, as it had the same issue. 

Let me know if you see any other issues! Silly github, you can't add a source file!? rename this to get rid of the .txt :)

Thanks,
Tom
[sasioiom.py.txt](https://github.com/sassoftware/saspy/files/1402876/sasioiom.py.txt)

**Comment by kevinjfoley** [comment]
Hey Tom,

I tested the file you added and it fixes the issue I outlined above

**Comment by tomweber-sas** [comment]
Cool, thanks for finding this and opening the issue!
I'll probably push this out next week. Not a show stopper and I'm kinda caught up with other things at the moment.

Thanks again!
Tom

**Comment by kevinjfoley** [comment]
Happy to help, thanks for fixing it so quickly!

**Comment by tomweber-sas** [comment]
Thanks for verifying. I've pushed this,. So closing this issue.
Let me know if you find any other issues!

Thanks,
Tom
