### ISSUE TITLE
Working with Python Unicode and SAS Session WLATIN1

### ISSUE THREAD

**Issue by hsej** [sassoftware/saspy#71]
I am using SASPy with Python 3.6 to connect to a SAS session with default encoding set to WLATIN1. Some string values include local characters like "ø",  "æ",  etc. Thus, for example, when I use the methods submit or sasdata2dataframe these characters are not converted correctly from Python code to SAS code and visa versa.

To fix this, I try: 
`sas.submit(CODE.encode('utf-8').decode('windows-1252'))`

However, this does not fix the problem. In addition, all methods appear to "ignore" Unicode. How should I deal with this encoding problem?

Right now my only option is to write the SAS code to a temporary file that I submit via the %include statement. I also may need to export the SAS data file to CSV and then manually convert it to a pandas DataFrame. This is not optimal! Here is a link to the code that I am currently using: http://www.henriksejersen.com/saspy-tryout-session/

**Comment by tomweber-sas** [comment]
Hey, I believe that I was looking into this a couple weeks ago; assuming it's the same problem. I got pulled off on other things, but I will dig into this again this week. The other issue was filed against sas_kernel number 44. Again, I don't know just yet if it's the same, but I suspect it is. 
I do consider this a bug in saspy; you shouldn't have to do anything regarding transcoding at your layer; it should be handled w/in saspy.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
OK, I believe I've tracked this down and fixed it. This did appear to be the same as sas_kernel 44 issue too.
I've pushed these changes to a new branch (nls) so that you can try it out before merging it into master. Just in case you find any other discrepancy. It all works for me - famous last words. :)

Can you pull 'nls' branch and set your 'encoding' config definition key to match your SAS encoding -  should be 'windows-1252' as you were trying before. Also, just try this native saspy without any special 'work around' code, as you shouldn't need anything like that. 

And, be aware that this required changes to the java code, so this branch has a new saspyiom.jar, so you'll need to be sure that what you have in your classpath for that jar does point to this new version after you pull the code.

Thanks!
Tom

**Comment by hsej** [comment]
Hi Tom, I dowloaded your nls version and tested it. It works fine also from here! As I expected, your efforts are quite successful. Thus I dropped any 'work around' code yesterday. Please see the code I used on my webpage (I do not know if I am supposed to put my code here?): http://www.henriksejersen.com/saspy-tryout-session/

Thanks!
Henrik

**Comment by hsej** [comment]
Here is the session information:

11-01-2017 11:07:00 odksas.sas INFO:
Access Method         = IOM
SAS Config name       = winiomwin
WORK Path             = G:\SASWORK\_TD3056_SAS-APP-U-01_\Prc2\
SAS Version           = 9.04.01M3P06242015
SASPy Version         = 2.1.7
Teach me SAS          = False
Batch                 = True
Results               = html
SAS Session Encoding  = WLATIN1
Python Encoding value = windows-1252

**Comment by tomweber-sas** [comment]
That's great! I'm waiting to hear back on sas_kernel issue 44 too, the Korean code page between SAS and saspy, which this fix also works well with for me. That one may have other variables I don't have, like Windows itself running in Korean too, and thus Java maybe using system code page too (I don't know).
So that's one I really can't be sure to replicate on my system myself. But, in my environment it works right, and didn't without this fix.

Thanks,
Tom

**Comment by hsej** [comment]
I see, you need a Korean Windows version :o) Thank you very much for fixing this so quickly!

All the best, Henrik

**Comment by tomweber-sas** [comment]
Well, I haven't heard back on the other issue, but this is clearly 'more better' than not. I'm going to go ahead and merge it in so it's at master, then delete this branch. Thanks again for helping us make saspy better!

Thanks,
Tom
