### ISSUE TITLE
dsopts={} fails on sasdata2dataframe when dataset is read with read_csv('http://...')

### ISSUE THREAD

**Issue by RandyBetancourt** [sassoftware/saspy#80]
Really love the feature set you guys are building!  Am experimenting with sas.read_csv.

When I call sasdata2dataframe with an existing SAS dataset from SASHELP with dsopts kwargs, no issue.  When I call sasdata2dataframe with an existing SAS dataset created with a call to sas.read_csv, there is no issue.  Its when the SAS dataset created with sas.read_csv has dsopts kwargs there is an error with sasdata2dataframe.  Please see image below.

![capture](https://user-images.githubusercontent.com/22532833/32799294-472e56a0-c945-11e7-99fd-f70268548962.PNG)

**Comment by tomweber-sas** [comment]
Hey Randy,

After that error, can you submit:

print(sas.saslog())

I wonder if the where clause produced no rows? It looks like an error in the gathering metadata about the table in order to do the data transfer and create the data frame.

Also, since you’re working on this. I just pushed a new branch with some performance enhancements for sasdata2dataframe. The process of creating a dataframe in-memory; from streaming data doesn’t scale.
I’ve fixed it so it doesn’t consume all the memory and cpu on the system, but that is still slow (pandas problem). So I’ve also added the ability to use an intermediary csv file.
Creating a dataframe from a file on disk is the only way to load large data into a dataframe. Kinda like looping over an insert statement to load data instead of using a bulk loader in database speak.

If you wouldn’t mind trying out the new methods, that’s be great.

Hey, did the proc import take that year column as char or numeric? That’s the other thing to look at. Could be the where clause is invalid, so no rows.
Run:
medals.contents()

to see the column data types.

Thanks,
Tom

**Comment by RandyBetancourt** [comment]
Hi Tom,

Thank you--you were correct.  An unforced error on my part!  The import mapped the year column as numeric and my WHERE clause treated it as character.

I appreciate the quick response.

Best,
Randy

**Comment by tomweber-sas** [comment]
Cool Randy. But, I will look into this to see if there's something I can to to make this more obvious. That's kind of an ugly traceback that isn't readily apparent as to the real cause. Checking the log is always a good idea, but still not the first thing anyone would think of when seeing this. It presents like a bug in my python code.

Thanks,
Tom
