### ISSUE TITLE
Using sas_clients queue when connecting to SAS Grid

### ISSUE THREAD

**Issue by iagomez** [sassoftware/saspy#82]
Hello saspy team,

**Context:** 
We are using `saspy` and `sas_kernel` to connect to a SAS Grid. I was able to follow the setup instructions - thank you for making it so straight forward! - and now I can connect and submit code to the grid.

When I check the grid jobs, I noticed the LSF job started through saspy is running in the `normal` queue instead of the `sas_clients` queue. I think the wrinkle here is that the SASApp Workspace is setup to use the SASApp Grid Server to launch the LSF jobs. Currently there is NO default queue setup there and the queue the SAS clients get is based on an "option set". The option sets available are:

![image](https://user-images.githubusercontent.com/2080150/33023454-38f07646-cdd6-11e7-8915-bf92875c7e1b.png)

Since none of those are Jupyter, we are getting the default queue for the SASApp server context which is currently the "normal" queue. 

**Question:**
Is there any way to specify the `Grid Option Set` in the `sascfg.py` configuration to pass through to the IOM server and on down to LSF. If not it would seem that the only way to force that to happen would be to create an app server context for Jupyter and force it to have a default queue of sas_clients. I'm assuming that would work, but we would have to test and ideally would want to avoid that configuration overhead if possible.

Thanks!

**Comment by tomweber-sas** [comment]
Hey, glad to hear you got it up and running with no problem! I will have to check w/ our Grid team to see how we can do this. I'm not familiar enough, myself, with how this works. But, if it's just a matter of passing an option through via IOM or something, then adding that to the config definition and passing it along shouldn't be a problem. 

One thing that is currently being done is to set the application name to 'SASPy'. I'm not sure if that is the actual value you want to specify yourself, or is that is the 'key' to use to specify which queue this should be routed to. Here's a line from the IOM log showing a connection from saspy:
```
NOTE: 20171116:12.01.22.67: 00024919:NOTE: New client connection (18) accepted from server port 8591 for user sas. Encryption level
      is Credentials using encryption algorithm SASPROPRIETARY. Peer IP address and port are [::ffff:10.23.16.149]:55232 for
      APPNAME=SASPy.
```
I'l track this down, though this being Thanksgiving week, I may not be able to get it figured out till next week, depending who's here these couple days.

Let me know if the APPNAME=SASPy is the thing that would make this work for you. As that's already working, I can easily add an option so you can set that value yourself in the config def.

Thanks,
Tom

**Comment by tomweber-sas** [comment]
Ok, the 2 people who would know this off the top of their head are out this week. But, others in the group have walked me through how this works and we have an idea that I think should get this working for you. It appears that the only thing missing, for you to define what you are trying to do in the grid option set mapping wizard (in your picture), is the app name  in the pulldown. We see that if we define an application in SMC and set the isGridCapable keyword in it's properties, then that application will show up in the pulldown so that you can select it and specify your grid option set mappings.

So, if you're up for trying this out, it should just be 2 simple steps, which you can easily undo and won't cause any problem if it doesn't just work. For reference, here's a link to doc regarding this:
http://support.sas.com/documentation/cdl/en/gridref/67371/HTML/default/viewer.htm#n1inymfs0b7go2n147xdknz0ygpx.htm

The part in that doc is at the bottom, named 'Specifying That an Application Is Grid Capable'. The list of applications in the dropdown comes from the application having the 'isGridCapable' keyword set in it's properties. As there is no SASPY application in the metadata, we can simple define one and set this property.

1) in the 'Folders' view in SMC (like in the picture in the doc link), there's a list of applications. The doc has the  SAS Addin for Microsoft Office selected. 
If you right click on Applications, you can selct 'New'->'Folder.
2) Do that and set the name of the folder to SASPy. Then right click and select Properties - just like in the picture in the doc. Then add a Keyword-> 'isGridCapable' and save it. Just like the picture in the doc.

After creating the SASPy folder (application), and setting it to grid capable, when you go back in to the grid options mapping wizard, SASPy should now be available to choose and you can set this up as you want to.

This is as far as I can go here, so I can't prove that it will just work when you try running this, but I really do expect it will. You may need to restart something, I don't know. When you created other Grid Option Set Mappings, do they take effect dynamically or do you need to restart the object spawner or something? Same protocol, whatever that is.

If there is still something else that needs to happen and this doesn't just work as expected, you can simple delete the mapping you created and the SASPy folder, and you should be back to where you were before. And, next week I can track down any other disconnect with the developers who know this best.

I think having the appname set by saspy (like in the log recors I showed), and you being able to specify which app server (in the saspy config def), should get you everything you need here. 

Looking at the doc, it looks like if the new folder you create is named 'SASPy' (exactly the same as what saspy is setting for it's appname=) then you just need to set 'isGridCapable'. If you name that folder differently, say 'TomSaysThisShouldWork', then you would need to set the keyword property to 'isGridCapable: TomSaysThisShouldWork'.  That seems like the only other piece that makes this all match up and work.

Sorry I can't really validate that here, but again, this should be a very simple thing you can try and see, and easily back out if it doesn't work. Let me know if you have any questions, and whether it works or not. If so, I'll document it in the saspy doc so others can get this configured too!

Thanks,
Tom

**Comment by iagomez** [comment]
Hey Tom,

Thank you for all the details! I will review these with my team and get back to you.

Thanks!
Ivan

**Comment by tomweber-sas** [comment]
@iagomez , just checking back to see if you were able to try this out and if it worked as expected.
Were you, and did it?
Thanks!
Tom

**Comment by iagomez** [comment]
@tomweber-sas 
Thank you for checking in. Unfortunately we've had a series of high priority tasks come up that have kept us from testing this. We're planning on testing this in the next 2 weeks.

**Comment by tomweber-sas** [comment]
No trouble. I completely understand that.

**Comment by iagomez** [comment]
Hey @tomweber-sas 
We were able to test this and it worked perfectly! Thank you very much for your help!

Best,
Ivan

**Comment by jld23** [comment]
@iagomez that is great to hear. I'll close the issue.

Jared

**Comment by tomweber-sas** [comment]
@iagomez Thanks for verifying this! Glad it worked as expected for you. I'll add this into the documentation so others can set this up too!

Thanks,
Tom

**Comment by venkattoluchuri** [comment]
My SASPy session runs only in normal queue thought I have created at SMC SASPy application route to different queue. Am I missing anything here. Please help.

**Comment by tomweber-sas** [comment]
Hey @venkattoluchuri . Creating the SASPy application in SMC and setting it 'isGridCapable' is the first step. The next is to create the Grid Option Set. The instructions for that are in the link in my second post above.
Have you done that? Creating the SASPy app in SMC was required to be able to then create the Grid Option Set, using that App. 

Thanks,
Tom

**Comment by venkattoluchuri** [comment]
Yes Tom. I have followed the same still issue persist. Will you able to join me on web-ex

**Comment by tomweber-sas** [comment]
@venkattoluchuri yes, I can do that. Do you have web-ex set up or do you need me to start one and invite you?
Tom

**Comment by venkattoluchuri** [comment]
can you do it for me please

**Comment by tomweber-sas** [comment]
ok, I think this is what you need. Else, email me at tom.weber@sas.com and I will then be able to invite you which will email you the correct way to connect.
https://sas.webex.com/join/Tom.Webersas.com
