### ISSUE TITLE
JRE 9 does not expose java.corba by default

### ISSUE THREAD

**Issue by dustinfarris** [sassoftware/saspy#89]
I ran into this error when trying to run on Windows with JRE 9 installed:

```
Using SAS Config named: winiomwin
Java Error:
Error: Unable to initialize main class pyiom.saspy2j
Caused by: java.lang.NoClassDefFoundError: org/omg/CORBA/UserException
```

The [dependency here](https://github.com/sassoftware/saspy/blob/c6f57f72185cf0826a68180b76b7e117f8c070ad/saspy/java/pyiom/saspy2j.java#L8) is the culprit.  This module is [not available by default as of JRE 9](https://www.reddit.com/r/java/comments/4mzz7w/java_9_will_remove_corba_from_default_classpath/).

Resolved by adding the module explicitly in my `sascfg_personal.py`, e.g. for me this looks like:

```py
winiomwin = {
  "java": "java",
  "encoding": "windows-1252",
  "classpath": cpW,
  "javaparms": ["--add-modules=java.corba"],
}
```

**Comment by tomweber-sas** [comment]
Wow, that's a great catch and workaround! That javaparms option is coming in handy :)
You never know what will change out from under you. I'm out of the office the rest of the week, but I'll look into this when I get back. I don't think I have java9 yet, so I'll install that and see what I see too. 
This will certainly help others who might run into this too! Thanks for the heads up!
Tom

**Comment by tomweber-sas** [comment]
Ok, I haven't installed java9 yet. I believe what you've described. I have had a chance to look at my java (IOM interface) code to see where this corba stuff is used and to see if I could do something in the source to perhaps eliminate the need for this.
There is only one reference to this, and it is for a return parameter from one of the IOM interfaces. And, I don't really care about that return parm, but I haven't been able to see a way around using it. The signature is explicitly typed, such that I can't seem to pass it any other type of 'sting' object that it 'could' use. I also can't get away with passing null, because I don't even care about the returned string; could have eliminated corba altogether if that had worked. The IOM method won't accept null and just not return me the value; it crashes instead. So, I'm not finding a work around for needing corba.
I will ping one of the IOM developers to see if they have any tricks I might not be aware of, but if not, I guess I'll just have to document your solution (which is nice and clean) in the saspy doc so others don't stumble over this.
Tom

**Comment by FriedEgg** [comment]
@tomweber-sas, corba is the foundation on which IOM is built, so it cannot be avoided.  In Java 9 the add-modules parameter would be the most elegant solution.

**Comment by tomweber-sas** [comment]
Yes, and that's what the developer just came back with too. Even if I could remove that one variable declared as a corba object from my jar, it wouldn't matter because all the other IOM jars I call completely depend on it.
Yes, I think I'll add this bit into the doc so it's there for everyone else to see as they upgrade to Java9.

He also mentioned that as of Java11, corba isn't even delivered. So it would have to be first installed from somewhere, and then added in to the search path. We'll I guess we can burn that bridge when we come to it :)

Thanks to both of you!
Tom

**Comment by tomweber-sas** [comment]
Ok, I've added a paragraph in the IOM configuration section, as well a section in the Troubleshooting chapter about this. Thanks again for tracking this down! Guess I'll close this as it seems resolved.
Tom
