### ISSUE TITLE
which configuration is suitable for linux client and windows sas server?

### ISSUE THREAD

**Issue by kaiwang0112006** [sassoftware/saspy#91]
I installed saspy on a ubuntu server and our sas is installed on a windows server.  I'm confused which configuration is suitable for our case.

**Comment by tomweber-sas** [comment]
Hey, this would require the IOM access method. That is the only way to connect to SAS running on Windows. Also, to connect remotely to SAS on a Windows machine, SAS will need to be running as a Workspace server, via the Object Spawner. Since you described it as 'a windows server', I'm guessing you are running an Object Spawner and have Workspace servers configured.
If it is really just PC SAS that you run locally, via 'sas.exe', then you cannot connect to that remotely. You can use that SAS kind of an install via IOM, but only with saspy running on the same windows machine.
In sascfg.py, there is a configuration definition named 'iomwin', which would be the appropriate template for your situation; connecting from saspy on Linux to a Windows Workspace server.
Let me know how this works for you and if you have any other questions!
Thanks,
Tom

**Comment by kaiwang0112006** [comment]
Thanks for the hint. First, there is a problem with the sas path on our windows server -- there is a blank. The classpath llike *"C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94250__prt_xx_sp0__1\deploywiz\sas.svc.connection.jar"* cannot be interpreted and raise "C:Program： command not found".
 
I tried to test the java command and even if I fix the blank problem in shell， there's still a java error:

    root@ebj-fk-03:~# java -classpath "C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94250__prt_xx_sp0__1\deploywiz\sas.svc.connection.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94250__prt__xx__sp0__1\deploywiz\log4j.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz_94250__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz_94250__prt__xx__sp0__1\deploywiz\sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar" pyiom.saspy2j -host localhost -stdinport 40444 -stdoutport 27908 -stderrport 48831 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1
Error: Could not find or load main class pyiom.saspy2j

I'm quite lost here

**Comment by tomweber-sas** [comment]
Hmm, I'm not sure it's really about the blank in the path. I have blanks in my classpath as well, and there's no issue.
Can you show me your config file and the whole results from the code you're submitting?
Can you verify that the paths to these jars are correct? 

I copied your command from above and looked at the classpath. It appears that the section of the paths with 'deploywiz...' are not consistent; there are varying numbers of underscores in the path for the different jars. This looks likely to be the problem. Can you verify the correct paths and try again?
```
C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94250__prt_xx_sp0__1\deploywiz\sas.svc.connection.jar;
C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz__94250__prt__xx__sp0__1\deploywiz\log4j.jar;
C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz_94250__prt__xx__sp0__1\deploywiz\sas.security.sspi.jar;
C:\Program Files\SASHome\SASDeploymentManager\9.4\products\deploywiz_94250__prt__xx__sp0__1\deploywiz\sas.core.jar;
/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar
```

Thanks!
Tom

**Comment by FriedEgg** [comment]
What pops out immediately to me is that these are Windows paths and you stated this is a Linux client.  These are client side jars and need to exist on the Linux machine and should this have Linux paths, such as that for saspyiom.jar

**Comment by tomweber-sas** [comment]
Oh, good catch @FriedEgg ! Yes, I forgot this is linux; focused on the paths. 
@kaiwang0112006 , you would need to copy the jars from that window machine to your linux machine and set your classpath correctly for them. 
Thanks @FriedEgg !

**Comment by kaiwang0112006** [comment]
Sorry, my bad. Here's my details:

saspy is installed on a ubuntu server and sas is run on a windows server. My config is:

    SAS_config_names=['test']

    testnew = "/data2/team/kw/sas.svc.connection.jar"
    testnew += ";/data2/team/kw/log4j.jar"
    testnew += ";/data2/team/kw/sas.security.sspi.jar"
    testnew += ";/data2/team/kw/sas.core.jar"
    testnew += ";/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar"

    test = { 'java'    : 'java',
             'iomhost'   : '192.168.1.207',
             'iomport'   : 8561,
             'classpath' : testnew,
             'omruser':'wangkai1',
             "omrpw":"password"
            }

I've copied 4 jar file (sas.svc.connection.jar, log4j.jar, sas.security.sspi.jar, sas.core.jar) from our sas server to ubuntu server and start saspy as:

    >>> import saspy
    >>> saspy.SASsession(cfgname="test")
    Java Error:
    
    The OS Error was:
    No such file or directory
    
    SAS Connection failed. No connection established. Double check you settings in sascfg.py file.
    
    Attempted to run program java with the following parameters:['java', '-classpath', '/data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '2249', '-stdoutport', '17610', '-stderrport', '63053', '-iomhost', '20.1.1.207', '-iomport', '8561', '-user', 'wangkai1', '']
    
    If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong:
    java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1
    
    
    SAS Connection failed. No connection established. Staus=(5358, 64000)  Double check you settings in sascfg.py file.
    
    Attempted to run program java with the following parameters:['java', '-classpath', '/data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '2249', '-stdoutport', '17610', '-stderrport', '63053', '-iomhost', '20.1.1.207', '-iomport', '8561', '-user', 'wangkai1', '']
    
    If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
    java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1
    
    No SAS process attached. SAS process has terminated unexpectedly.
    No SAS process attached. SAS process has terminated unexpectedly.
    No SAS process attached. SAS process has terminated unexpectedly.
    Access Method         = IOM
    SAS Config name       = test
    WORK Path             = /
    SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
    SASPy Version         = 2.2.1
    Teach me SAS          = False
    Batch                 = False
    Results               = Pandas
    SAS Session Encoding  = No
    Python Encoding value = utf-8

I run the java command in linux shell 

     java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1

and got a mess error like:

    /data2/team/kw/log4j.jar: line 1: $'PK\003\004': command not found
    /data2/team/kw/log4j.jar: line 2: $'\267\003\0317': command not found
    鈻?b鈻扖ohb鈻? No such file or directoryv鈻扢ETA-INF/MANIFEST.MFm鈻掆枓鈻?鈻掆枓M鈻?/data2/team/kw/log4j.jar: command substitution: line 56: unexpected EOF while looking for matching `"'
    /data2/team/kw/log4j.jar: command substitution: line 58: syntax error: unexpected end of file
    /data2/team/kw/log4j.jar: command substitution: line 31: syntax error near unexpected token `)'
    /data2/team/kw/log4j.jar: command substitution: line 31: 
    ...


which make me feel that copy these jar file to linux machine is not enough

**Comment by tomweber-sas** [comment]
Actually, that looks better. Just on my phone, so I may miss something. But. The error you are getting now is due to needing the fully qualified path to java, not just 'java' for the Java keyword. That can work on Windows, but on Linux you must specify the full path.
Try that and you may be there!
On Jan 23, 2018 9:31 PM, kaiwang <notifications@github.com> wrote:

EXTERNAL

Sorry, my bad. Here's my details:

saspy is installed on a ubuntu server and sas is run on a windows server. My config is:

SAS_config_names=['test']

testnew = "/data2/team/kw/sas.svc.connection.jar"
testnew += ";/data2/team/kw/log4j.jar"
testnew += ";/data2/team/kw/sas.security.sspi.jar"
testnew += ";/data2/team/kw/sas.core.jar"
testnew += ";/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar"

test = { 'java'    : 'java',
         'iomhost'   : '192.168.1.207',
         'iomport'   : 8561,
         'classpath' : testnew,
         'omruser':'wangkai1',
         "omrpw":"password"
        }


I've copied 4 jar file (sas.svc.connection.jar, log4j.jar, sas.security.sspi.jar, sas.core.jar) from our sas server to ubuntu server and start saspy as:

>>> import saspy
>>> saspy.SASsession(cfgname="test")
Java Error:

The OS Error was:
No such file or directory

SAS Connection failed. No connection established. Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', '/data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '2249', '-stdoutport', '17610', '-stderrport', '63053', '-iomhost', '20.1.1.207', '-iomport', '8561', '-user', 'wangkai1', '']

If no OS Error above, try running the following command (where saspy is running) manually to see what is wrong:
java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1


SAS Connection failed. No connection established. Staus=(5358, 64000)  Double check you settings in sascfg.py file.

Attempted to run program java with the following parameters:['java', '-classpath', '/data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '2249', '-stdoutport', '17610', '-stderrport', '63053', '-iomhost', '20.1.1.207', '-iomport', '8561', '-user', 'wangkai1', '']

If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1

No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
No SAS process attached. SAS process has terminated unexpectedly.
Access Method         = IOM
SAS Config name       = test
WORK Path             = /
SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
SASPy Version         = 2.2.1
Teach me SAS          = False
Batch                 = False
Results               = Pandas
SAS Session Encoding  = No
Python Encoding value = utf-8


I run the java command in linux shell

 java -classpath /data2/team/kw/sas.svc.connection.jar;/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 2249 -stdoutport 17610 -stderrport 63053 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1


and got a mess error like:

/data2/team/kw/log4j.jar: line 1: $'PK\003\004': command not found
/data2/team/kw/log4j.jar: line 2: $'\267\003\0317': command not found
??b??ohb?? No such file or directoryv??ETA-INF/MANIFEST.MFm????????M??/data2/team/kw/log4j.jar: command substitution: line 56: unexpected EOF while looking for matching `"'
/data2/team/kw/log4j.jar: command substitution: line 58: syntax error: unexpected end of file
/data2/team/kw/log4j.jar: command substitution: line 31: syntax error near unexpected token `)'
/data2/team/kw/log4j.jar: command substitution: line 31:
...


which make me feel that copy these jar file to linux machine is not enough

-

**Comment by kaiwang0112006** [comment]
Thanks for your patience. Yes, it seems make more sense now. 

I changed the config as:

    test = { 'java'    : 'java',
             'iomhost'   : '192.168.1.207',
             'iomport'   : 8561,
             'classpath' : testnew,
             'omruser':'wangkai1',
             "omrpw":"password"
            }

And run as:

	>>> import saspy
	>>> saspy.SASsession(cfgname="test")
	Java Error:
	Error: Could not find or load main class pyiom.saspy2j
	
	
	SAS Connection failed. No connection established. Staus=(26975, 256)  Double check you settings in sascfg.py file.
	
	Attempted to run program /usr/bin/java with the following parameters:['/usr/bin/java', '-classpath', '/data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar', 'pyiom.saspy2j', '-host', 'localhost', '-stdinport', '43216', '-stdoutport', '50105', '-stderrport', '7785', '-iomhost', '20.1.1.207', '-iomport', '8561', '-user', 'wangkai1', '']
	
	If no Java Error above, try running the following command (where saspy is running) manually to see if it's a problem starting Java:
	/usr/bin/java -classpath /data2/team/kw/log4j.jar;/data2/team/kw/sas.security.sspi.jar;/data2/team/kw/sas.core.jar;/opt/conda3/lib/python3.6/site-packages/saspy/java/saspyiom.jar pyiom.saspy2j -host localhost -stdinport 43216 -stdoutport 50105 -stderrport 7785 -iomhost 20.1.1.207 -iomport 8561 -user wangkai1
	
	No SAS process attached. SAS process has terminated unexpectedly.
	No SAS process attached. SAS process has terminated unexpectedly.
	No SAS process attached. SAS process has terminated unexpectedly.
	Access Method         = IOM
	SAS Config name       = test
	WORK Path             = /
	SAS Version           = No SAS process attached. SAS process has terminated unexpectedly.
	SASPy Version         = 2.2.1
	Teach me SAS          = False
	Batch                 = False
	Results               = Pandas
	SAS Session Encoding  = No
	Python Encoding value = utf-8

The message is more clear. But I tried to comment out each JAR file as [Troubleshooting](https://sassoftware.github.io/saspy/troubleshooting.html#iom) says, still got no clue why it's not working

**Comment by tomweber-sas** [comment]
So, this is still a classpath issue. Normally, I would suggest running the whole command from the command line because you may get a traceback with more information sometimes, which I don't always get inside saspy. But, I believe that you are using semicolons ';' to separate the jars, which is correct on Windows. But on Linux, you need to use colons ':'. I suspect that's the last thing to fix regarding this.

The next thing will be making sure your iomhost/iomport are correct. The host needs to be where the Object Spawner is running and the port needs to be the Workspace Server port. Sometimes people get those mixed up with the OMR (Metadata Server) host and port.

Also, look at the doc about using a .authinfo file for your password. Without that, you will be prompted for your OMR password (you specified your OMR userid I see). The .authinfo file is very convenient for that.
Hopefully you will be up and running now!
Tom

**Comment by kaiwang0112006** [comment]
Thanks so much. Yes，finally I got it right

**Comment by tomweber-sas** [comment]
Great!
Let me know if you have any other issues,
Tom
