### ISSUE TITLE
Get result of `submit` as a pandas dataframe

### ISSUE THREAD

**Issue by dustinfarris** [sassoftware/saspy#92]
Is it possible to get the result of a `sas.submit` call as a pandas DataFrame (or a list of)?

The closest I've been able to get is this:

```py
sas_output = sas.submit("my sas code;")
data = pd.read_html(sas_output["LST"])
```

Is there a better way to do this?

**Comment by tomweber-sas** [comment]
Hmmm, this is interesting. My first though, of course, is all of the reasons and situations this can't work.
But ignoring that for the moment, I've been trying to go down a couple different trains of thought to see if there could be a reasonable case for when it could work. So far those are dead ends too. 

There already are methods to import a SAS Data Set into a Pandas data frame. You can do that in one line of code already. Any arbitrary set of code you could submit, may or may not produce 'data', and it could produce any amount of output, some of which could be considered 'data', and plenty that is not. I'm not seeing a way for me to magically extract arbitrary parts of output. Trying to parse the listing to get data just isn't a plausible solution.

Any code you submit that produces 'data', if you simply write it to a SAS Data Set as opposed to writing it to the listing, you can then just use the sasdata2dataframe() (sd2df(), sd2df_CSV(), to_df(), to_df_CSV(), ...) methods as your next statement to import them to data frames. This is the way to do this.

I was trying to come up with some kind of global statement, to wrap whatever code you're submitting, which would make any kind of 'data' output from any code you submit be written to data sets instead of going to the listing, then I could do the sd2df()'s and return them to you but that isn't panning out. Even though this could never work reliably for any possible code you run, I thought that for some simple cases it 'could' work. So maybe it would be worth trying and seeing where I could go with it. But, I can't come up with anything, even for what would be plausible cases.

Do you have some example of code you would be submitting, just to see what you're thinking of?
If nothing else, I could show you how to tweak that code so you could then just import the data to data frames after the code runs.

Thanks,
Tom

**Comment by dustinfarris** [comment]
Hi Tom,

Thank you for your thoughtful reply.

I am trying to build a tool that can inspect 20 years' worth of legacy SAS code (thousands of .sas files), spread out all over a drive, and come up with some kind of map or searchable index to help my client locate relevant sas code when they have a certain need.

My initial idea was to programmatically execute all of the SAS files, using saspy.  Something like:

```py
for path in paths:
  output = sas.submit(open(path).read())
  do_something_clever(pandas.read_html(output["LST"]))
```

While conceptually ideal, this idea is a little problematic for a couple of reasons (hidden macros, and such) including not being able to reliably convert the output into some kind of Python object.  Pandas `read_html` is the closest I've been able to get.  It works for very simple cases, but I'm not sure if that will scale.

Any suggestions?  It sounds like I will have to manually look through each file and ensure the final output is a SAS data set, and then pick that up in Python.  But there are thousands of these files — I'm hoping I can automate this somehow.

**Comment by tomweber-sas** [comment]
Wow, that does sound like a daunting task. It also sounds like you are more interested in the SAS code itself, as opposed to data it may interact with? Trying to find interesting, useful code snippets that would be usable for other cases? This is different than even what I was thinking. Though I still might not have the whole picture.
I haven't used read_html, but just thinking about what all could be written to the listing for any given entire SAS program, somehow parsing that into data frame and then deciphering something coherent out of that; wow! 
So, it's not that you want actual data that the program may create, imported to a dataframe. It's more of capturing all output a program may produce and import that into some type of object you can then 'mine' somehow. Is that it (in a nutshell, obviously)? Hmmmm.

**Comment by dustinfarris** [comment]
> capturing all output a program may produce and import that into some type of object you can then 'mine' somehow.

Yes, that's it exactly.

**Comment by dustinfarris** [comment]
Have not been working on this recently.  Will let you know if anything else comes up!  Thanks for all the help!
-- 
Dustin Farris

**Comment by tomweber-sas** [comment]
Thanks!. I'll go ahead and close this. Just open up another if you run into anything or need my help at all!
Thanks,
Tom

**Comment by gcamargo1** [comment]
@tomweber-sas I would be interested in what @dustinfarris asked. Having an object which you could get different parts of the sas output. Similar to what exists in this style:

stat = sas.sasstat()
stat_results = stat.reg(model='horsepower = Cylinders EngineSize',data=cars)
dir(stat_results)
['ANOVA',
 'COOKSDPLOT',
 'DFBETASPANEL',
 'DFFITSPLOT',
 'DIAGNOSTICSPANEL',
 'FITSTATISTICS',
...
Should we re-open this issue?
Thanks for looking into this!
Gustavo

**Comment by tomweber-sas** [comment]
@gcamargo1 , this issue was about any given SAS program/job that could be doing anything, and creating who knows what, who knows where. I really don't see how I would be able to somehow get at all of that and wrap it up in an object you can use to access all of whatever may have been done by that job.
Do you have a particular case you're thinking of? Something more tangible? 
The analytic result object can access all of the various pieces of the proc output, because those are known and under our control, as to where they are created. That's how we can provide that result object and access the parts for you.
Any given SAS code could do anything. I don't see a plausible way to do the equivalent.
And, sorry this took so long. Been on too many things lately.
Thanks,
Tom

**Comment by Narendra5005** [comment]
hi all, I am using SASpy to query the datasets and getting results into HTML.. is there a way to get those datasets into pandas dataframes.. please help me with the syntax or method. Thanks in advance

**Comment by tomweber-sas** [comment]
Hey @Narendra5005 would you mind opening a new ticket and I'll help you with what you need. posting to an old, closed issue about, probably, something different isn't as good as just opening a new issue.  Can you incluse an example of what it is you're submitting?
Thanks!
Tom

**Comment by Narendra5005** [comment]
Sure
